# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Canonical technology taxonomy.

The normalized, deterministic catalogue of technologies HunterX recognises.
Every detected technology — whatever the tool calls it — is resolved against
this catalogue so ``Apache``, ``apache``, ``Apache httpd`` and ``Apache HTTP
Server`` collapse onto one canonical name while the original observation is
always preserved.

The catalogue is deliberately curated and deterministic: it covers the
technologies exercised by the golden datasets and the signature database, and
is extensible by appending entries. Entries are pure data; resolution logic
lives in :mod:`hunterx.domain.technology.resolver`.
"""

from __future__ import annotations

from dataclasses import dataclass

from hunterx.domain.technology.models import TechnologyCategory, TechnologyFamily


@dataclass(frozen=True, slots=True)
class TechDefinition:
    """A canonical technology entry in the taxonomy.

    Attributes:
        canonical_name: the canonical display name (e.g. ``Nginx``).
        category: the canonical taxonomy category.
        family: the canonical technology family.
        aliases: alternative spellings/names that resolve to this technology.
        vendor: technology vendor when known.
        product: canonical product name (e.g. ``nginx``).
        description: short human description.
        base_confidence: confidence of a weak-signature-only detection.

    """

    canonical_name: str
    category: TechnologyCategory
    family: TechnologyFamily
    aliases: tuple[str, ...] = ()
    vendor: str = ""
    product: str = ""
    description: str = ""
    base_confidence: float = 0.9

    def to_dict(self) -> dict[str, str | float]:
        """Return a JSON-safe dictionary."""
        return {
            "canonical_name": self.canonical_name,
            "category": self.category.value,
            "family": self.family.value,
            "vendor": self.vendor,
            "product": self.product,
            "description": self.description,
        }


#: Canonical technology catalogue. Aliases are matched case-insensitively and
#: are the mechanism that collapses free-form tool output onto one identity.
TECHNOLOGY_CATALOG: tuple[TechDefinition, ...] = (
    # -- web servers --------------------------------------------------------
    TechDefinition(
        "Apache HTTP Server",
        TechnologyCategory.WEB_SERVER,
        TechnologyFamily.WEB_SERVER,
        aliases=("apache", "apache http server", "apache httpd", "apache/2", "apache/2.4", "httpd"),
        vendor="Apache Software Foundation",
        product="apache",
        description="Open-source HTTP server maintained by the Apache Software Foundation.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Nginx",
        TechnologyCategory.WEB_SERVER,
        TechnologyFamily.WEB_SERVER,
        aliases=("nginx", "nginx/1", "nginx/2", "openresty"),
        vendor="F5 / Nginx",
        product="nginx",
        description="High-performance HTTP and reverse proxy server.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Microsoft IIS",
        TechnologyCategory.WEB_SERVER,
        TechnologyFamily.WEB_SERVER,
        aliases=("iis", "microsoft iis", "microsoft-internet-information-services", "iis/"),
        vendor="Microsoft",
        product="iis",
        description="Microsoft Internet Information Services web server.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "LiteSpeed",
        TechnologyCategory.WEB_SERVER,
        TechnologyFamily.WEB_SERVER,
        aliases=("litespeed", "litespeed webserver", "openlitespeed"),
        vendor="LiteSpeed Technologies",
        product="litespeed",
        description="High-performance commercial and open-source web server.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Caddy",
        TechnologyCategory.WEB_SERVER,
        TechnologyFamily.WEB_SERVER,
        aliases=("caddy", "caddy/"),
        vendor="Caddy",
        product="caddy",
        description="Automatic-HTTPS web server written in Go.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Tomcat",
        TechnologyCategory.APPLICATION_SERVER,
        TechnologyFamily.APPLICATION_SERVER,
        aliases=("apache tomcat", "tomcat", "apache-tomcat", "coyote"),
        vendor="Apache Software Foundation",
        product="tomcat",
        description="Apache Tomcat Java servlet and application server.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Jetty",
        TechnologyCategory.APPLICATION_SERVER,
        TechnologyFamily.APPLICATION_SERVER,
        aliases=("jetty", "eclipse jetty"),
        vendor="Eclipse Foundation",
        product="jetty",
        description="Eclipse Jetty Java servlet container.",
        base_confidence=0.8,
    ),
    # -- CMS ----------------------------------------------------------------
    TechDefinition(
        "WordPress",
        TechnologyCategory.CMS,
        TechnologyFamily.WEB_FRAMEWORK,
        aliases=("wordpress", "wp", "wp-content"),
        vendor="Automattic",
        product="wordpress",
        description="Open-source content management system written in PHP.",
        base_confidence=0.9,
    ),
    TechDefinition(
        "Drupal",
        TechnologyCategory.CMS,
        TechnologyFamily.WEB_FRAMEWORK,
        aliases=("drupal", "drupal 8", "drupal 9", "drupal 10", "drupal 11"),
        vendor="Drupal Association",
        product="drupal",
        description="Open-source content management system written in PHP.",
        base_confidence=0.9,
    ),
    TechDefinition(
        "Joomla",
        TechnologyCategory.CMS,
        TechnologyFamily.WEB_FRAMEWORK,
        aliases=("joomla", "joomla!"),
        vendor="Open Source Matters",
        product="joomla",
        description="Open-source content management system written in PHP.",
        base_confidence=0.9,
    ),
    # -- web frameworks -----------------------------------------------------
    TechDefinition(
        "Django",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("django", "django framework"),
        vendor="Django Software Foundation",
        product="django",
        description="High-level Python web framework.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Flask",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("flask", "flask framework"),
        vendor="Pallets",
        product="flask",
        description="Micro web framework for Python.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "FastAPI",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("fastapi", "fast api"),
        vendor="FastAPI",
        product="fastapi",
        description="Modern Python web framework for APIs.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Ruby on Rails",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("rails", "ruby on rails", "ruby-on-rails"),
        vendor="Rails Core Team",
        product="rails",
        description="Full-stack web framework written in Ruby.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Laravel",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("laravel", "laravel framework"),
        vendor="Laravel",
        product="laravel",
        description="PHP web application framework.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Spring",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("spring", "spring framework", "spring boot"),
        vendor="VMware",
        product="spring",
        description="Java application framework.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Express",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("express", "expressjs", "express.js"),
        vendor="OpenJS Foundation",
        product="express",
        description="Node.js web application framework.",
        base_confidence=0.75,
    ),
    # -- frontend frameworks -------------------------------------------------
    TechDefinition(
        "React",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("react", "react.js", "reactjs", "react-dom"),
        vendor="Meta",
        product="react",
        description="JavaScript library for building user interfaces.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Vue.js",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("vue", "vue.js", "vuejs", "vue-router"),
        vendor="Vue.js",
        product="vue",
        description="Progressive JavaScript framework.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Angular",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("angular", "angularjs", "angular.js", "ng"),
        vendor="Google",
        product="angular",
        description="TypeScript-based web application framework.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Next.js",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("next.js", "nextjs", "next"),
        vendor="Vercel",
        product="nextjs",
        description="React framework for production-grade applications.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Nuxt",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("nuxt", "nuxt.js", "nuxtjs"),
        vendor="Nuxt Labs",
        product="nuxt",
        description="Vue.js framework for server-side rendered applications.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "jQuery",
        TechnologyCategory.JAVASCRIPT,
        TechnologyFamily.JAVASCRIPT,
        aliases=("jquery", "jquery.js"),
        vendor="OpenJS Foundation",
        product="jquery",
        description="Fast, small JavaScript library.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Bootstrap",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("bootstrap", "bootstrap 3", "bootstrap 4", "bootstrap 5"),
        vendor="Bootstrap Core Team",
        product="bootstrap",
        description="Frontend component library.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Tailwind CSS",
        TechnologyCategory.FRONTEND,
        TechnologyFamily.FRONTEND_FRAMEWORK,
        aliases=("tailwind", "tailwindcss", "tailwind css"),
        vendor="Tailwind Labs",
        product="tailwindcss",
        description="Utility-first CSS framework.",
        base_confidence=0.7,
    ),
    TechDefinition(
        "Webpack",
        TechnologyCategory.JAVASCRIPT,
        TechnologyFamily.JAVASCRIPT,
        aliases=("webpack", "webpack.js"),
        vendor="Webpack",
        product="webpack",
        description="Static module bundler for JavaScript applications.",
        base_confidence=0.7,
    ),
    TechDefinition(
        "Vite",
        TechnologyCategory.JAVASCRIPT,
        TechnologyFamily.JAVASCRIPT,
        aliases=("vite", "vite.js"),
        vendor="Vite",
        product="vite",
        description="Frontend build tooling.",
        base_confidence=0.7,
    ),
    # -- programming languages / runtimes ------------------------------------
    TechDefinition(
        "PHP",
        TechnologyCategory.PROGRAMMING_LANGUAGE,
        TechnologyFamily.PROGRAMMING_LANGUAGE,
        aliases=("php", "php7", "php8"),
        vendor="PHP Group",
        product="php",
        description="General-purpose scripting language widely used on the web.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Node.js",
        TechnologyCategory.RUNTIME,
        TechnologyFamily.RUNTIME,
        aliases=("node", "node.js", "nodejs"),
        vendor="OpenJS Foundation",
        product="nodejs",
        description="JavaScript runtime built on Chrome's V8 engine.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Python",
        TechnologyCategory.PROGRAMMING_LANGUAGE,
        TechnologyFamily.PROGRAMMING_LANGUAGE,
        aliases=("python", "python3", "cpython"),
        vendor="Python Software Foundation",
        product="python",
        description="High-level general-purpose programming language.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Java",
        TechnologyCategory.PROGRAMMING_LANGUAGE,
        TechnologyFamily.PROGRAMMING_LANGUAGE,
        aliases=("java", "openjdk"),
        vendor="Oracle",
        product="java",
        description="General-purpose programming language and runtime.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Ruby",
        TechnologyCategory.PROGRAMMING_LANGUAGE,
        TechnologyFamily.PROGRAMMING_LANGUAGE,
        aliases=("ruby", "mri"),
        vendor="Ruby Core Team",
        product="ruby",
        description="Dynamic, open-source programming language.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "ASP.NET",
        TechnologyCategory.FRAMEWORK,
        TechnologyFamily.BACKEND_FRAMEWORK,
        aliases=("asp.net", "aspnet", "aspnetcore", "asp.net core", "dotnet"),
        vendor="Microsoft",
        product="aspnet",
        description="Microsoft web application framework.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Go",
        TechnologyCategory.PROGRAMMING_LANGUAGE,
        TechnologyFamily.PROGRAMMING_LANGUAGE,
        aliases=("go", "golang"),
        vendor="Google",
        product="go",
        description="Statically typed programming language.",
        base_confidence=0.75,
    ),
    # -- databases ----------------------------------------------------------
    TechDefinition(
        "MySQL",
        TechnologyCategory.DATABASE,
        TechnologyFamily.DATABASE,
        aliases=("mysql", "mysql server"),
        vendor="Oracle",
        product="mysql",
        description="Open-source relational database management system.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "PostgreSQL",
        TechnologyCategory.DATABASE,
        TechnologyFamily.DATABASE,
        aliases=("postgresql", "postgres", "pgsql"),
        vendor="PostgreSQL Global Development Group",
        product="postgresql",
        description="Open-source relational database management system.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "MongoDB",
        TechnologyCategory.DATABASE,
        TechnologyFamily.DATABASE,
        aliases=("mongodb", "mongo"),
        vendor="MongoDB",
        product="mongodb",
        description="Document-oriented NoSQL database.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Redis",
        TechnologyCategory.DATABASE,
        TechnologyFamily.DATABASE,
        aliases=("redis", "redis server"),
        vendor="Redis Ltd.",
        product="redis",
        description="In-memory data structure store.",
        base_confidence=0.8,
    ),
    # -- CDN / WAF / proxy --------------------------------------------------
    TechDefinition(
        "Cloudflare",
        TechnologyCategory.CDN,
        TechnologyFamily.CDN,
        aliases=("cloudflare", "cloudflare cdn", "cloudflare-nginx", "__cfduid"),
        vendor="Cloudflare",
        product="cloudflare",
        description="CDN, edge network and security provider.",
        base_confidence=0.9,
    ),
    TechDefinition(
        "Cloudflare WAF",
        TechnologyCategory.WAF,
        TechnologyFamily.WAF,
        aliases=("cloudflare waf", "cloudflare bot management", "cf-ray"),
        vendor="Cloudflare",
        product="cloudflare-waf",
        description="Cloudflare web application firewall and bot management.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Amazon CloudFront",
        TechnologyCategory.CDN,
        TechnologyFamily.CDN,
        aliases=("cloudfront", "amazon cloudfront", "amazon.cloudfront"),
        vendor="Amazon Web Services",
        product="cloudfront",
        description="Amazon Web Services content delivery network.",
        base_confidence=0.85,
    ),
    TechDefinition(
        "Amazon ELB",
        TechnologyCategory.LOAD_BALANCER,
        TechnologyFamily.LOAD_BALANCER,
        aliases=("amazon elb", "aws elb", "elastic load balancer", "awsalb"),
        vendor="Amazon Web Services",
        product="aws-elb",
        description="Amazon Web Services elastic load balancer.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Amazon ALB",
        TechnologyCategory.LOAD_BALANCER,
        TechnologyFamily.LOAD_BALANCER,
        aliases=("aws alb", "application load balancer", "awsalb"),
        vendor="Amazon Web Services",
        product="aws-alb",
        description="Amazon Web Services application load balancer.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Fastly",
        TechnologyCategory.CDN,
        TechnologyFamily.EDGE_NETWORK,
        aliases=("fastly", "fastly cdn"),
        vendor="Fastly",
        product="fastly",
        description="Edge cloud platform.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Akamai",
        TechnologyCategory.CDN,
        TechnologyFamily.CDN,
        aliases=("akamai", "akamai cdn", "akamaighost"),
        vendor="Akamai",
        product="akamai",
        description="Content delivery network and cloud services.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Nginx Reverse Proxy",
        TechnologyCategory.PROXY,
        TechnologyFamily.REVERSE_PROXY,
        aliases=("nginx reverse proxy", "nginx proxy"),
        vendor="F5 / Nginx",
        product="nginx-proxy",
        description="Nginx acting as a reverse proxy.",
        base_confidence=0.7,
    ),
    TechDefinition(
        "Varnish",
        TechnologyCategory.PROXY,
        TechnologyFamily.REVERSE_PROXY,
        aliases=("varnish", "varnish cache"),
        vendor="Varnish Software",
        product="varnish",
        description="HTTP accelerator / caching reverse proxy.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "HAProxy",
        TechnologyCategory.PROXY,
        TechnologyFamily.LOAD_BALANCER,
        aliases=("haproxy", "haproxy load balancer"),
        vendor="HAProxy Technologies",
        product="haproxy",
        description="TCP/HTTP load balancer and proxy server.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "AWS WAF",
        TechnologyCategory.WAF,
        TechnologyFamily.WAF,
        aliases=("aws waf", "amazon waf"),
        vendor="Amazon Web Services",
        product="aws-waf",
        description="Amazon Web Services web application firewall.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "ModSecurity",
        TechnologyCategory.WAF,
        TechnologyFamily.WAF,
        aliases=("modsecurity", "mod_security"),
        vendor="OWASP / Trustwave",
        product="modsecurity",
        description="Open-source web application firewall engine.",
        base_confidence=0.75,
    ),
    # -- cloud / hosting ----------------------------------------------------
    TechDefinition(
        "Amazon Web Services",
        TechnologyCategory.CLOUD,
        TechnologyFamily.CLOUD_PLATFORM,
        aliases=("aws", "amazon web services", "amazonaws"),
        vendor="Amazon Web Services",
        product="aws",
        description="Amazon Web Services cloud platform.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Microsoft Azure",
        TechnologyCategory.CLOUD,
        TechnologyFamily.CLOUD_PLATFORM,
        aliases=("azure", "microsoft azure", "azurewebsites"),
        vendor="Microsoft",
        product="azure",
        description="Microsoft Azure cloud platform.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Google Cloud",
        TechnologyCategory.CLOUD,
        TechnologyFamily.CLOUD_PLATFORM,
        aliases=("google cloud", "gcp", "google cloud platform", "googleusercontent"),
        vendor="Google",
        product="gcp",
        description="Google Cloud Platform.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Heroku",
        TechnologyCategory.HOSTING,
        TechnologyFamily.HOSTING_PROVIDER,
        aliases=("heroku", "herokuapp"),
        vendor="Salesforce",
        product="heroku",
        description="Platform-as-a-service hosting provider.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "GitHub Pages",
        TechnologyCategory.HOSTING,
        TechnologyFamily.HOSTING_PROVIDER,
        aliases=("github pages", "github.io"),
        vendor="GitHub",
        product="github-pages",
        description="Static site hosting provided by GitHub.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Netlify",
        TechnologyCategory.HOSTING,
        TechnologyFamily.HOSTING_PROVIDER,
        aliases=("netlify", "netlify cdn"),
        vendor="Netlify",
        product="netlify",
        description="Static web hosting and CDN.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Vercel",
        TechnologyCategory.HOSTING,
        TechnologyFamily.HOSTING_PROVIDER,
        aliases=("vercel", "vercel cdn"),
        vendor="Vercel",
        product="vercel",
        description="Frontend deployment and hosting platform.",
        base_confidence=0.8,
    ),
    # -- operating systems ---------------------------------------------------
    TechDefinition(
        "Linux",
        TechnologyCategory.OPERATING_SYSTEM,
        TechnologyFamily.OPERATING_SYSTEM,
        aliases=("linux", "linux kernel"),
        vendor="Linux Foundation",
        product="linux",
        description="Open-source operating system kernel.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Ubuntu",
        TechnologyCategory.OPERATING_SYSTEM,
        TechnologyFamily.OPERATING_SYSTEM,
        aliases=("ubuntu", "ubuntu linux"),
        vendor="Canonical",
        product="ubuntu",
        description="Ubuntu Linux distribution.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Debian",
        TechnologyCategory.OPERATING_SYSTEM,
        TechnologyFamily.OPERATING_SYSTEM,
        aliases=("debian", "debian gnu/linux"),
        vendor="Debian Project",
        product="debian",
        description="Debian Linux distribution.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Windows Server",
        TechnologyCategory.OPERATING_SYSTEM,
        TechnologyFamily.OPERATING_SYSTEM,
        aliases=("windows server", "windows server 2012", "windows server 2016", "windows server 2019", "windows server 2022"),
        vendor="Microsoft",
        product="windows-server",
        description="Microsoft Windows Server operating system.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "CentOS",
        TechnologyCategory.OPERATING_SYSTEM,
        TechnologyFamily.OPERATING_SYSTEM,
        aliases=("centos", "centos linux"),
        vendor="Red Hat",
        product="centos",
        description="CentOS Linux distribution.",
        base_confidence=0.75,
    ),
    # -- security / authentication / analytics --------------------------------
    TechDefinition(
        "Google reCAPTCHA",
        TechnologyCategory.SECURITY,
        TechnologyFamily.SECURITY,
        aliases=("recaptcha", "google recaptcha", "g-recaptcha"),
        vendor="Google",
        product="recaptcha",
        description="Anti-bot verification service.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "Google Analytics",
        TechnologyCategory.ANALYTICS,
        TechnologyFamily.ANALYTICS,
        aliases=("google analytics", "gtag", "ga.js", "analytics.js"),
        vendor="Google",
        product="google-analytics",
        description="Web analytics service.",
        base_confidence=0.8,
    ),
    TechDefinition(
        "OAuth",
        TechnologyCategory.AUTHENTICATION,
        TechnologyFamily.AUTHENTICATION,
        aliases=("oauth", "oauth2", "oauth 2.0"),
        vendor="IETF",
        product="oauth",
        description="Open standard authorization framework.",
        base_confidence=0.7,
    ),
    TechDefinition(
        "JWT",
        TechnologyCategory.AUTHENTICATION,
        TechnologyFamily.AUTHENTICATION,
        aliases=("jwt", "json web token", "jose"),
        vendor="IETF",
        product="jwt",
        description="JSON web token authentication.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Datadog",
        TechnologyCategory.MONITORING,
        TechnologyFamily.MONITORING,
        aliases=("datadog", "dd-rum"),
        vendor="Datadog",
        product="datadog",
        description="Monitoring and analytics platform.",
        base_confidence=0.75,
    ),
    # -- infrastructure -------------------------------------------------------
    TechDefinition(
        "Docker",
        TechnologyCategory.INFRASTRUCTURE,
        TechnologyFamily.INFRASTRUCTURE,
        aliases=("docker", "docker container"),
        vendor="Docker Inc.",
        product="docker",
        description="Containerisation platform.",
        base_confidence=0.75,
    ),
    TechDefinition(
        "Kubernetes",
        TechnologyCategory.INFRASTRUCTURE,
        TechnologyFamily.INFRASTRUCTURE,
        aliases=("kubernetes", "k8s"),
        vendor="CNCF",
        product="kubernetes",
        description="Container orchestration platform.",
        base_confidence=0.75,
    ),
)


def catalog_by_name() -> dict[str, TechDefinition]:
    """Return a mapping of canonical name to its definition."""
    return {definition.canonical_name: definition for definition in TECHNOLOGY_CATALOG}
