"""api intelligence tables

Revision ID: 371b8ca7642d
Revises: c51bafedb05e
Create Date: 2026-08-09 05:56:36.682935

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '371b8ca7642d'
down_revision: str | Sequence[str] | None = 'c51bafedb05e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tidb_api_authentications',
    sa.Column('api_id', sa.String(length=26), nullable=True),
    sa.Column('host_id', sa.String(length=26), nullable=True),
    sa.Column('scheme_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_location', sa.String(length=64), nullable=False),
    sa.Column('flows', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('documented', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_authentications_api_id'), 'tidb_api_authentications', ['api_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_authentications_correlation_id'), 'tidb_api_authentications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_authentications_host_id'), 'tidb_api_authentications', ['host_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_authentications_mission_id'), 'tidb_api_authentications', ['mission_id'], unique=False)
    op.create_table('tidb_api_authorizations',
    sa.Column('api_id', sa.String(length=26), nullable=True),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_authorizations_api_id'), 'tidb_api_authorizations', ['api_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_authorizations_correlation_id'), 'tidb_api_authorizations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_authorizations_mission_id'), 'tidb_api_authorizations', ['mission_id'], unique=False)
    op.create_table('tidb_api_changes',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('previous', sa.Text(), nullable=False),
    sa.Column('current', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_changes_correlation_id'), 'tidb_api_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_changes_mission_id'), 'tidb_api_changes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_changes_subject'), 'tidb_api_changes', ['subject'], unique=False)
    op.create_index('ix_tidb_api_changes_subject_type', 'tidb_api_changes', ['subject_type', 'subject'], unique=False)
    op.create_table('tidb_api_conflicts',
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('selected', sa.String(length=512), nullable=False),
    sa.Column('selected_source', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_conflicts_correlation_id'), 'tidb_api_conflicts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_conflicts_mission_id'), 'tidb_api_conflicts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_conflicts_subject'), 'tidb_api_conflicts', ['subject'], unique=False)
    op.create_table('tidb_api_evidence',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=26), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('integrity', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_evidence_correlation_id'), 'tidb_api_evidence', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_evidence_mission_id'), 'tidb_api_evidence', ['mission_id'], unique=False)
    op.create_index('ix_tidb_api_evidence_subject', 'tidb_api_evidence', ['subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_evidence_subject_id'), 'tidb_api_evidence', ['subject_id'], unique=False)
    op.create_table('tidb_api_filters',
    sa.Column('operation_id', sa.String(length=26), nullable=False),
    sa.Column('filter_param', sa.String(length=128), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('operators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_filters_correlation_id'), 'tidb_api_filters', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_filters_mission_id'), 'tidb_api_filters', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_filters_operation_id'), 'tidb_api_filters', ['operation_id'], unique=False)
    op.create_table('tidb_api_hosts',
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('scheme', sa.String(length=8), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('origin_key', sa.String(length=512), nullable=False),
    sa.Column('api_kinds', sa.JSON(), nullable=False),
    sa.Column('api_count', sa.Integer(), nullable=False),
    sa.Column('endpoint_count', sa.Integer(), nullable=False),
    sa.Column('documented', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_hosts_correlation_id'), 'tidb_api_hosts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_hosts_execution_id'), 'tidb_api_hosts', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_hosts_host'), 'tidb_api_hosts', ['host'], unique=False)
    op.create_index(op.f('ix_tidb_api_hosts_mission_id'), 'tidb_api_hosts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_hosts_origin_key'), 'tidb_api_hosts', ['origin_key'], unique=False)
    op.create_index(op.f('ix_tidb_api_hosts_target_key'), 'tidb_api_hosts', ['target_key'], unique=False)
    op.create_table('tidb_api_operations',
    sa.Column('api_id', sa.String(length=26), nullable=False),
    sa.Column('host_id', sa.String(length=26), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('normalized_path', sa.Text(), nullable=False),
    sa.Column('path_hash', sa.String(length=64), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('documented', sa.Boolean(), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('response_content_type', sa.String(length=128), nullable=False),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('pagination', sa.String(length=16), nullable=False),
    sa.Column('has_filters', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_hint', sa.String(length=16), nullable=False),
    sa.Column('parameter_count', sa.Integer(), nullable=False),
    sa.Column('security_schemes', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_operations_api_id'), 'tidb_api_operations', ['api_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_operations_correlation_id'), 'tidb_api_operations', ['correlation_id'], unique=False)
    op.create_index('ix_tidb_api_operations_hash_method', 'tidb_api_operations', ['path_hash', 'method'], unique=False)
    op.create_index(op.f('ix_tidb_api_operations_host_id'), 'tidb_api_operations', ['host_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_operations_method'), 'tidb_api_operations', ['method'], unique=False)
    op.create_index(op.f('ix_tidb_api_operations_mission_id'), 'tidb_api_operations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_operations_path_hash'), 'tidb_api_operations', ['path_hash'], unique=False)
    op.create_table('tidb_api_paginations',
    sa.Column('api_id', sa.String(length=26), nullable=True),
    sa.Column('operation_id', sa.String(length=26), nullable=True),
    sa.Column('style', sa.String(length=16), nullable=False),
    sa.Column('limit_param', sa.String(length=64), nullable=False),
    sa.Column('offset_param', sa.String(length=64), nullable=True),
    sa.Column('cursor_param', sa.String(length=64), nullable=True),
    sa.Column('total_source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_paginations_api_id'), 'tidb_api_paginations', ['api_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_paginations_correlation_id'), 'tidb_api_paginations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_paginations_mission_id'), 'tidb_api_paginations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_paginations_operation_id'), 'tidb_api_paginations', ['operation_id'], unique=False)
    op.create_table('tidb_api_parameters',
    sa.Column('operation_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('param_type', sa.String(length=64), nullable=False),
    sa.Column('schema_digest', sa.String(length=64), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('enum_values', sa.JSON(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_parameters_correlation_id'), 'tidb_api_parameters', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_parameters_mission_id'), 'tidb_api_parameters', ['mission_id'], unique=False)
    op.create_index('ix_tidb_api_parameters_op_name', 'tidb_api_parameters', ['operation_id', 'name'], unique=False)
    op.create_index(op.f('ix_tidb_api_parameters_operation_id'), 'tidb_api_parameters', ['operation_id'], unique=False)
    op.create_table('tidb_api_rate_limits',
    sa.Column('api_id', sa.String(length=26), nullable=True),
    sa.Column('host_id', sa.String(length=26), nullable=True),
    sa.Column('style', sa.String(length=16), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('declared', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_rate_limits_api_id'), 'tidb_api_rate_limits', ['api_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_rate_limits_correlation_id'), 'tidb_api_rate_limits', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_rate_limits_host_id'), 'tidb_api_rate_limits', ['host_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_rate_limits_mission_id'), 'tidb_api_rate_limits', ['mission_id'], unique=False)
    op.create_table('tidb_api_runs',
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('hosts', sa.Integer(), nullable=False),
    sa.Column('apis', sa.Integer(), nullable=False),
    sa.Column('operations', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.Integer(), nullable=False),
    sa.Column('schemas', sa.Integer(), nullable=False),
    sa.Column('auth_schemes', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_runs_correlation_id'), 'tidb_api_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_runs_mission_id'), 'tidb_api_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_runs_target_key'), 'tidb_api_runs', ['target_key'], unique=False)
    op.create_table('tidb_api_schemas',
    sa.Column('operation_id', sa.String(length=26), nullable=True),
    sa.Column('api_id', sa.String(length=26), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_schemas_api_id'), 'tidb_api_schemas', ['api_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_schemas_correlation_id'), 'tidb_api_schemas', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_schemas_digest'), 'tidb_api_schemas', ['digest'], unique=False)
    op.create_index(op.f('ix_tidb_api_schemas_mission_id'), 'tidb_api_schemas', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_schemas_operation_id'), 'tidb_api_schemas', ['operation_id'], unique=False)
    op.create_table('tidb_api_specs',
    sa.Column('host_id', sa.String(length=26), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('spec_type', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('spec_version', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('operation_count', sa.Integer(), nullable=False),
    sa.Column('schema_count', sa.Integer(), nullable=False),
    sa.Column('integrity', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_specs_correlation_id'), 'tidb_api_specs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_specs_execution_id'), 'tidb_api_specs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_specs_host_id'), 'tidb_api_specs', ['host_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_specs_mission_id'), 'tidb_api_specs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_specs_target_key'), 'tidb_api_specs', ['target_key'], unique=False)
    op.create_table('tidb_api_versions',
    sa.Column('host_id', sa.String(length=26), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('api_version', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.String(length=64), nullable=False),
    sa.Column('path_prefix', sa.String(length=255), nullable=False),
    sa.Column('documented', sa.Boolean(), nullable=False),
    sa.Column('operation_count', sa.Integer(), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_api_versions_correlation_id'), 'tidb_api_versions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_api_versions_host_id'), 'tidb_api_versions', ['host_id'], unique=False)
    op.create_index('ix_tidb_api_versions_host_name', 'tidb_api_versions', ['host_id', 'api_name'], unique=False)
    op.create_index(op.f('ix_tidb_api_versions_mission_id'), 'tidb_api_versions', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tidb_api_versions_mission_id'), table_name='tidb_api_versions')
    op.drop_index('ix_tidb_api_versions_host_name', table_name='tidb_api_versions')
    op.drop_index(op.f('ix_tidb_api_versions_host_id'), table_name='tidb_api_versions')
    op.drop_index(op.f('ix_tidb_api_versions_correlation_id'), table_name='tidb_api_versions')
    op.drop_table('tidb_api_versions')
    op.drop_index(op.f('ix_tidb_api_specs_target_key'), table_name='tidb_api_specs')
    op.drop_index(op.f('ix_tidb_api_specs_mission_id'), table_name='tidb_api_specs')
    op.drop_index(op.f('ix_tidb_api_specs_host_id'), table_name='tidb_api_specs')
    op.drop_index(op.f('ix_tidb_api_specs_execution_id'), table_name='tidb_api_specs')
    op.drop_index(op.f('ix_tidb_api_specs_correlation_id'), table_name='tidb_api_specs')
    op.drop_table('tidb_api_specs')
    op.drop_index(op.f('ix_tidb_api_schemas_operation_id'), table_name='tidb_api_schemas')
    op.drop_index(op.f('ix_tidb_api_schemas_mission_id'), table_name='tidb_api_schemas')
    op.drop_index(op.f('ix_tidb_api_schemas_digest'), table_name='tidb_api_schemas')
    op.drop_index(op.f('ix_tidb_api_schemas_correlation_id'), table_name='tidb_api_schemas')
    op.drop_index(op.f('ix_tidb_api_schemas_api_id'), table_name='tidb_api_schemas')
    op.drop_table('tidb_api_schemas')
    op.drop_index(op.f('ix_tidb_api_runs_target_key'), table_name='tidb_api_runs')
    op.drop_index(op.f('ix_tidb_api_runs_mission_id'), table_name='tidb_api_runs')
    op.drop_index(op.f('ix_tidb_api_runs_correlation_id'), table_name='tidb_api_runs')
    op.drop_table('tidb_api_runs')
    op.drop_index(op.f('ix_tidb_api_rate_limits_mission_id'), table_name='tidb_api_rate_limits')
    op.drop_index(op.f('ix_tidb_api_rate_limits_host_id'), table_name='tidb_api_rate_limits')
    op.drop_index(op.f('ix_tidb_api_rate_limits_correlation_id'), table_name='tidb_api_rate_limits')
    op.drop_index(op.f('ix_tidb_api_rate_limits_api_id'), table_name='tidb_api_rate_limits')
    op.drop_table('tidb_api_rate_limits')
    op.drop_index(op.f('ix_tidb_api_parameters_operation_id'), table_name='tidb_api_parameters')
    op.drop_index('ix_tidb_api_parameters_op_name', table_name='tidb_api_parameters')
    op.drop_index(op.f('ix_tidb_api_parameters_mission_id'), table_name='tidb_api_parameters')
    op.drop_index(op.f('ix_tidb_api_parameters_correlation_id'), table_name='tidb_api_parameters')
    op.drop_table('tidb_api_parameters')
    op.drop_index(op.f('ix_tidb_api_paginations_operation_id'), table_name='tidb_api_paginations')
    op.drop_index(op.f('ix_tidb_api_paginations_mission_id'), table_name='tidb_api_paginations')
    op.drop_index(op.f('ix_tidb_api_paginations_correlation_id'), table_name='tidb_api_paginations')
    op.drop_index(op.f('ix_tidb_api_paginations_api_id'), table_name='tidb_api_paginations')
    op.drop_table('tidb_api_paginations')
    op.drop_index(op.f('ix_tidb_api_operations_path_hash'), table_name='tidb_api_operations')
    op.drop_index(op.f('ix_tidb_api_operations_mission_id'), table_name='tidb_api_operations')
    op.drop_index(op.f('ix_tidb_api_operations_method'), table_name='tidb_api_operations')
    op.drop_index(op.f('ix_tidb_api_operations_host_id'), table_name='tidb_api_operations')
    op.drop_index('ix_tidb_api_operations_hash_method', table_name='tidb_api_operations')
    op.drop_index(op.f('ix_tidb_api_operations_correlation_id'), table_name='tidb_api_operations')
    op.drop_index(op.f('ix_tidb_api_operations_api_id'), table_name='tidb_api_operations')
    op.drop_table('tidb_api_operations')
    op.drop_index(op.f('ix_tidb_api_hosts_target_key'), table_name='tidb_api_hosts')
    op.drop_index(op.f('ix_tidb_api_hosts_origin_key'), table_name='tidb_api_hosts')
    op.drop_index(op.f('ix_tidb_api_hosts_mission_id'), table_name='tidb_api_hosts')
    op.drop_index(op.f('ix_tidb_api_hosts_host'), table_name='tidb_api_hosts')
    op.drop_index(op.f('ix_tidb_api_hosts_execution_id'), table_name='tidb_api_hosts')
    op.drop_index(op.f('ix_tidb_api_hosts_correlation_id'), table_name='tidb_api_hosts')
    op.drop_table('tidb_api_hosts')
    op.drop_index(op.f('ix_tidb_api_filters_operation_id'), table_name='tidb_api_filters')
    op.drop_index(op.f('ix_tidb_api_filters_mission_id'), table_name='tidb_api_filters')
    op.drop_index(op.f('ix_tidb_api_filters_correlation_id'), table_name='tidb_api_filters')
    op.drop_table('tidb_api_filters')
    op.drop_index(op.f('ix_tidb_api_evidence_subject_id'), table_name='tidb_api_evidence')
    op.drop_index('ix_tidb_api_evidence_subject', table_name='tidb_api_evidence')
    op.drop_index(op.f('ix_tidb_api_evidence_mission_id'), table_name='tidb_api_evidence')
    op.drop_index(op.f('ix_tidb_api_evidence_correlation_id'), table_name='tidb_api_evidence')
    op.drop_table('tidb_api_evidence')
    op.drop_index(op.f('ix_tidb_api_conflicts_subject'), table_name='tidb_api_conflicts')
    op.drop_index(op.f('ix_tidb_api_conflicts_mission_id'), table_name='tidb_api_conflicts')
    op.drop_index(op.f('ix_tidb_api_conflicts_correlation_id'), table_name='tidb_api_conflicts')
    op.drop_table('tidb_api_conflicts')
    op.drop_index('ix_tidb_api_changes_subject_type', table_name='tidb_api_changes')
    op.drop_index(op.f('ix_tidb_api_changes_subject'), table_name='tidb_api_changes')
    op.drop_index(op.f('ix_tidb_api_changes_mission_id'), table_name='tidb_api_changes')
    op.drop_index(op.f('ix_tidb_api_changes_correlation_id'), table_name='tidb_api_changes')
    op.drop_table('tidb_api_changes')
    op.drop_index(op.f('ix_tidb_api_authorizations_mission_id'), table_name='tidb_api_authorizations')
    op.drop_index(op.f('ix_tidb_api_authorizations_correlation_id'), table_name='tidb_api_authorizations')
    op.drop_index(op.f('ix_tidb_api_authorizations_api_id'), table_name='tidb_api_authorizations')
    op.drop_table('tidb_api_authorizations')
    op.drop_index(op.f('ix_tidb_api_authentications_mission_id'), table_name='tidb_api_authentications')
    op.drop_index(op.f('ix_tidb_api_authentications_host_id'), table_name='tidb_api_authentications')
    op.drop_index(op.f('ix_tidb_api_authentications_correlation_id'), table_name='tidb_api_authentications')
    op.drop_index(op.f('ix_tidb_api_authentications_api_id'), table_name='tidb_api_authentications')
    op.drop_table('tidb_api_authentications')
    # ### end Alembic commands ###
