"""live host and dns observation tables

Revision ID: 53b3e0bb8ed2
Revises: 4302b30cb7c7
Create Date: 2026-08-08 05:07:58.144343

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53b3e0bb8ed2'
down_revision: str | Sequence[str] | None = '4302b30cb7c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tidb_discovery_conflicts',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('conflict_type', sa.String(length=16), nullable=False),
    sa.Column('selected_value', sa.Text(), nullable=False),
    sa.Column('selected_source', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_discovery_conflicts_correlation_id'), 'tidb_discovery_conflicts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_discovery_conflicts_key'), 'tidb_discovery_conflicts', ['key'], unique=False)
    op.create_index(op.f('ix_tidb_discovery_conflicts_kind'), 'tidb_discovery_conflicts', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_discovery_conflicts_mission_id'), 'tidb_discovery_conflicts', ['mission_id'], unique=False)
    op.create_table('tidb_dns_changes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_dns_changes_change_type'), 'tidb_dns_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_tidb_dns_changes_correlation_id'), 'tidb_dns_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_changes_mission_id'), 'tidb_dns_changes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_changes_name'), 'tidb_dns_changes', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_dns_changes_record_type'), 'tidb_dns_changes', ['record_type'], unique=False)
    op.create_table('tidb_dns_conflicts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('conflict_type', sa.String(length=16), nullable=False),
    sa.Column('selected_value', sa.Text(), nullable=False),
    sa.Column('selected_source', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_dns_conflicts_correlation_id'), 'tidb_dns_conflicts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_conflicts_mission_id'), 'tidb_dns_conflicts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_conflicts_name'), 'tidb_dns_conflicts', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_dns_conflicts_record_type'), 'tidb_dns_conflicts', ['record_type'], unique=False)
    op.create_table('tidb_dns_observations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('rcode', sa.String(length=16), nullable=False),
    sa.Column('resolver', sa.String(length=255), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_dns_observations_correlation_id'), 'tidb_dns_observations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_observations_execution_id'), 'tidb_dns_observations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_observations_name'), 'tidb_dns_observations', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_dns_observations_record_type'), 'tidb_dns_observations', ['record_type'], unique=False)
    op.create_index(op.f('ix_tidb_dns_observations_resolver'), 'tidb_dns_observations', ['resolver'], unique=False)
    op.create_index(op.f('ix_tidb_dns_observations_tool_id'), 'tidb_dns_observations', ['tool_id'], unique=False)
    op.create_table('tidb_dns_resolutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('record_types', sa.JSON(), nullable=False),
    sa.Column('addresses', sa.JSON(), nullable=False),
    sa.Column('cnames', sa.JSON(), nullable=False),
    sa.Column('rcode', sa.String(length=16), nullable=False),
    sa.Column('resolver', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('wildcard', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_dns_resolutions_correlation_id'), 'tidb_dns_resolutions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_resolutions_execution_id'), 'tidb_dns_resolutions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_resolutions_name'), 'tidb_dns_resolutions', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_dns_resolutions_resolver'), 'tidb_dns_resolutions', ['resolver'], unique=False)
    op.create_index(op.f('ix_tidb_dns_resolutions_status'), 'tidb_dns_resolutions', ['status'], unique=False)
    op.create_table('tidb_host_observations',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('ip_version', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=True),
    sa.Column('methods', sa.JSON(), nullable=False),
    sa.Column('rtt_ms', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_host_observations_address'), 'tidb_host_observations', ['address'], unique=False)
    op.create_index(op.f('ix_tidb_host_observations_correlation_id'), 'tidb_host_observations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_host_observations_execution_id'), 'tidb_host_observations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_host_observations_state'), 'tidb_host_observations', ['state'], unique=False)
    op.create_index(op.f('ix_tidb_host_observations_target_id'), 'tidb_host_observations', ['target_id'], unique=False)
    op.create_index(op.f('ix_tidb_host_observations_tool_id'), 'tidb_host_observations', ['tool_id'], unique=False)
    op.create_table('tidb_live_changes',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_live_changes_change_type'), 'tidb_live_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_tidb_live_changes_correlation_id'), 'tidb_live_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_live_changes_key'), 'tidb_live_changes', ['key'], unique=False)
    op.create_index(op.f('ix_tidb_live_changes_kind'), 'tidb_live_changes', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_live_changes_mission_id'), 'tidb_live_changes', ['mission_id'], unique=False)
    op.create_table('tidb_nameservers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('addresses', sa.JSON(), nullable=False),
    sa.Column('owner_domain', sa.String(length=255), nullable=True),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tidb_nameservers_name')
    )
    op.create_index(op.f('ix_tidb_nameservers_name'), 'tidb_nameservers', ['name'], unique=False)
    op.create_table('tidb_port_observations',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_port_observations_address'), 'tidb_port_observations', ['address'], unique=False)
    op.create_index('ix_tidb_port_observations_address_port', 'tidb_port_observations', ['address', 'port'], unique=False)
    op.create_index(op.f('ix_tidb_port_observations_correlation_id'), 'tidb_port_observations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_port_observations_execution_id'), 'tidb_port_observations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_port_observations_port'), 'tidb_port_observations', ['port'], unique=False)
    op.create_index(op.f('ix_tidb_port_observations_state'), 'tidb_port_observations', ['state'], unique=False)
    op.create_index(op.f('ix_tidb_port_observations_target_id'), 'tidb_port_observations', ['target_id'], unique=False)
    op.create_index(op.f('ix_tidb_port_observations_tool_id'), 'tidb_port_observations', ['tool_id'], unique=False)
    op.create_table('tidb_resolvers',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('rtt_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_resolvers_address'), 'tidb_resolvers', ['address'], unique=True)
    op.create_index(op.f('ix_tidb_resolvers_status'), 'tidb_resolvers', ['status'], unique=False)
    op.create_table('tidb_service_observations',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('software_version', sa.String(length=128), nullable=False),
    sa.Column('extrainfo', sa.Text(), nullable=False),
    sa.Column('banner', sa.Text(), nullable=False),
    sa.Column('fingerprint_method', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_service_observations_address'), 'tidb_service_observations', ['address'], unique=False)
    op.create_index('ix_tidb_service_observations_address_port', 'tidb_service_observations', ['address', 'port'], unique=False)
    op.create_index(op.f('ix_tidb_service_observations_correlation_id'), 'tidb_service_observations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_service_observations_execution_id'), 'tidb_service_observations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_service_observations_port'), 'tidb_service_observations', ['port'], unique=False)
    op.create_index(op.f('ix_tidb_service_observations_service'), 'tidb_service_observations', ['service'], unique=False)
    op.create_index(op.f('ix_tidb_service_observations_target_id'), 'tidb_service_observations', ['target_id'], unique=False)
    op.create_index(op.f('ix_tidb_service_observations_tool_id'), 'tidb_service_observations', ['tool_id'], unique=False)
    op.create_table('tidb_caa_records',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=26), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['tidb_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_caa_records_domain_id'), 'tidb_caa_records', ['domain_id'], unique=False)
    op.create_index(op.f('ix_tidb_caa_records_name'), 'tidb_caa_records', ['name'], unique=False)
    op.create_table('tidb_dns_zones',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=26), nullable=True),
    sa.Column('primary_ns', sa.String(length=255), nullable=True),
    sa.Column('admin_mail', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('refresh', sa.Integer(), nullable=True),
    sa.Column('retry', sa.Integer(), nullable=True),
    sa.Column('expire', sa.Integer(), nullable=True),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['tidb_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tidb_dns_zones_name')
    )
    op.create_index(op.f('ix_tidb_dns_zones_domain_id'), 'tidb_dns_zones', ['domain_id'], unique=False)
    op.create_index(op.f('ix_tidb_dns_zones_name'), 'tidb_dns_zones', ['name'], unique=False)
    op.create_table('tidb_mx_records',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=26), nullable=True),
    sa.Column('preference', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=255), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['tidb_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_mx_records_domain_id'), 'tidb_mx_records', ['domain_id'], unique=False)
    op.create_index(op.f('ix_tidb_mx_records_name'), 'tidb_mx_records', ['name'], unique=False)
    op.create_index('ix_tidb_mx_records_name_exchange', 'tidb_mx_records', ['name', 'exchange'], unique=False)
    op.create_table('tidb_soa_records',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=26), nullable=True),
    sa.Column('primary_ns', sa.String(length=255), nullable=True),
    sa.Column('admin_mail', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('refresh', sa.Integer(), nullable=True),
    sa.Column('retry', sa.Integer(), nullable=True),
    sa.Column('expire', sa.Integer(), nullable=True),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['tidb_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_soa_records_domain_id'), 'tidb_soa_records', ['domain_id'], unique=False)
    op.create_index(op.f('ix_tidb_soa_records_name'), 'tidb_soa_records', ['name'], unique=False)
    op.create_table('tidb_txt_records',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=26), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['tidb_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_txt_records_domain_id'), 'tidb_txt_records', ['domain_id'], unique=False)
    op.create_index(op.f('ix_tidb_txt_records_name'), 'tidb_txt_records', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_txt_records_purpose'), 'tidb_txt_records', ['purpose'], unique=False)
    op.create_table('tidb_dns_delegations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain_id', sa.String(length=26), nullable=True),
    sa.Column('nameservers', sa.JSON(), nullable=False),
    sa.Column('glue_records', sa.JSON(), nullable=False),
    sa.Column('is_delegated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['tidb_subdomains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tidb_dns_delegations_name')
    )
    op.create_index(op.f('ix_tidb_dns_delegations_name'), 'tidb_dns_delegations', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_dns_delegations_subdomain_id'), 'tidb_dns_delegations', ['subdomain_id'], unique=False)
    op.create_table('tidb_dnssec_records',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_id', sa.String(length=26), nullable=True),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=True),
    sa.Column('key_tag', sa.Integer(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['tidb_dns_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_dnssec_records_name'), 'tidb_dnssec_records', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_dnssec_records_record_type'), 'tidb_dnssec_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_tidb_dnssec_records_zone_id'), 'tidb_dnssec_records', ['zone_id'], unique=False)
    op.create_table('tidb_ptr_records',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address_id', sa.String(length=26), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ip_address_id'], ['tidb_ip_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_ptr_records_ip_address_id'), 'tidb_ptr_records', ['ip_address_id'], unique=False)
    op.create_index(op.f('ix_tidb_ptr_records_name'), 'tidb_ptr_records', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tidb_ptr_records_name'), table_name='tidb_ptr_records')
    op.drop_index(op.f('ix_tidb_ptr_records_ip_address_id'), table_name='tidb_ptr_records')
    op.drop_table('tidb_ptr_records')
    op.drop_index(op.f('ix_tidb_dnssec_records_zone_id'), table_name='tidb_dnssec_records')
    op.drop_index(op.f('ix_tidb_dnssec_records_record_type'), table_name='tidb_dnssec_records')
    op.drop_index(op.f('ix_tidb_dnssec_records_name'), table_name='tidb_dnssec_records')
    op.drop_table('tidb_dnssec_records')
    op.drop_index(op.f('ix_tidb_dns_delegations_subdomain_id'), table_name='tidb_dns_delegations')
    op.drop_index(op.f('ix_tidb_dns_delegations_name'), table_name='tidb_dns_delegations')
    op.drop_table('tidb_dns_delegations')
    op.drop_index(op.f('ix_tidb_txt_records_purpose'), table_name='tidb_txt_records')
    op.drop_index(op.f('ix_tidb_txt_records_name'), table_name='tidb_txt_records')
    op.drop_index(op.f('ix_tidb_txt_records_domain_id'), table_name='tidb_txt_records')
    op.drop_table('tidb_txt_records')
    op.drop_index(op.f('ix_tidb_soa_records_name'), table_name='tidb_soa_records')
    op.drop_index(op.f('ix_tidb_soa_records_domain_id'), table_name='tidb_soa_records')
    op.drop_table('tidb_soa_records')
    op.drop_index('ix_tidb_mx_records_name_exchange', table_name='tidb_mx_records')
    op.drop_index(op.f('ix_tidb_mx_records_name'), table_name='tidb_mx_records')
    op.drop_index(op.f('ix_tidb_mx_records_domain_id'), table_name='tidb_mx_records')
    op.drop_table('tidb_mx_records')
    op.drop_index(op.f('ix_tidb_dns_zones_name'), table_name='tidb_dns_zones')
    op.drop_index(op.f('ix_tidb_dns_zones_domain_id'), table_name='tidb_dns_zones')
    op.drop_table('tidb_dns_zones')
    op.drop_index(op.f('ix_tidb_caa_records_name'), table_name='tidb_caa_records')
    op.drop_index(op.f('ix_tidb_caa_records_domain_id'), table_name='tidb_caa_records')
    op.drop_table('tidb_caa_records')
    op.drop_index(op.f('ix_tidb_service_observations_tool_id'), table_name='tidb_service_observations')
    op.drop_index(op.f('ix_tidb_service_observations_target_id'), table_name='tidb_service_observations')
    op.drop_index(op.f('ix_tidb_service_observations_service'), table_name='tidb_service_observations')
    op.drop_index(op.f('ix_tidb_service_observations_port'), table_name='tidb_service_observations')
    op.drop_index(op.f('ix_tidb_service_observations_execution_id'), table_name='tidb_service_observations')
    op.drop_index(op.f('ix_tidb_service_observations_correlation_id'), table_name='tidb_service_observations')
    op.drop_index('ix_tidb_service_observations_address_port', table_name='tidb_service_observations')
    op.drop_index(op.f('ix_tidb_service_observations_address'), table_name='tidb_service_observations')
    op.drop_table('tidb_service_observations')
    op.drop_index(op.f('ix_tidb_resolvers_status'), table_name='tidb_resolvers')
    op.drop_index(op.f('ix_tidb_resolvers_address'), table_name='tidb_resolvers')
    op.drop_table('tidb_resolvers')
    op.drop_index(op.f('ix_tidb_port_observations_tool_id'), table_name='tidb_port_observations')
    op.drop_index(op.f('ix_tidb_port_observations_target_id'), table_name='tidb_port_observations')
    op.drop_index(op.f('ix_tidb_port_observations_state'), table_name='tidb_port_observations')
    op.drop_index(op.f('ix_tidb_port_observations_port'), table_name='tidb_port_observations')
    op.drop_index(op.f('ix_tidb_port_observations_execution_id'), table_name='tidb_port_observations')
    op.drop_index(op.f('ix_tidb_port_observations_correlation_id'), table_name='tidb_port_observations')
    op.drop_index('ix_tidb_port_observations_address_port', table_name='tidb_port_observations')
    op.drop_index(op.f('ix_tidb_port_observations_address'), table_name='tidb_port_observations')
    op.drop_table('tidb_port_observations')
    op.drop_index(op.f('ix_tidb_nameservers_name'), table_name='tidb_nameservers')
    op.drop_table('tidb_nameservers')
    op.drop_index(op.f('ix_tidb_live_changes_mission_id'), table_name='tidb_live_changes')
    op.drop_index(op.f('ix_tidb_live_changes_kind'), table_name='tidb_live_changes')
    op.drop_index(op.f('ix_tidb_live_changes_key'), table_name='tidb_live_changes')
    op.drop_index(op.f('ix_tidb_live_changes_correlation_id'), table_name='tidb_live_changes')
    op.drop_index(op.f('ix_tidb_live_changes_change_type'), table_name='tidb_live_changes')
    op.drop_table('tidb_live_changes')
    op.drop_index(op.f('ix_tidb_host_observations_tool_id'), table_name='tidb_host_observations')
    op.drop_index(op.f('ix_tidb_host_observations_target_id'), table_name='tidb_host_observations')
    op.drop_index(op.f('ix_tidb_host_observations_state'), table_name='tidb_host_observations')
    op.drop_index(op.f('ix_tidb_host_observations_execution_id'), table_name='tidb_host_observations')
    op.drop_index(op.f('ix_tidb_host_observations_correlation_id'), table_name='tidb_host_observations')
    op.drop_index(op.f('ix_tidb_host_observations_address'), table_name='tidb_host_observations')
    op.drop_table('tidb_host_observations')
    op.drop_index(op.f('ix_tidb_dns_resolutions_status'), table_name='tidb_dns_resolutions')
    op.drop_index(op.f('ix_tidb_dns_resolutions_resolver'), table_name='tidb_dns_resolutions')
    op.drop_index(op.f('ix_tidb_dns_resolutions_name'), table_name='tidb_dns_resolutions')
    op.drop_index(op.f('ix_tidb_dns_resolutions_execution_id'), table_name='tidb_dns_resolutions')
    op.drop_index(op.f('ix_tidb_dns_resolutions_correlation_id'), table_name='tidb_dns_resolutions')
    op.drop_table('tidb_dns_resolutions')
    op.drop_index(op.f('ix_tidb_dns_observations_tool_id'), table_name='tidb_dns_observations')
    op.drop_index(op.f('ix_tidb_dns_observations_resolver'), table_name='tidb_dns_observations')
    op.drop_index(op.f('ix_tidb_dns_observations_record_type'), table_name='tidb_dns_observations')
    op.drop_index(op.f('ix_tidb_dns_observations_name'), table_name='tidb_dns_observations')
    op.drop_index(op.f('ix_tidb_dns_observations_execution_id'), table_name='tidb_dns_observations')
    op.drop_index(op.f('ix_tidb_dns_observations_correlation_id'), table_name='tidb_dns_observations')
    op.drop_table('tidb_dns_observations')
    op.drop_index(op.f('ix_tidb_dns_conflicts_record_type'), table_name='tidb_dns_conflicts')
    op.drop_index(op.f('ix_tidb_dns_conflicts_name'), table_name='tidb_dns_conflicts')
    op.drop_index(op.f('ix_tidb_dns_conflicts_mission_id'), table_name='tidb_dns_conflicts')
    op.drop_index(op.f('ix_tidb_dns_conflicts_correlation_id'), table_name='tidb_dns_conflicts')
    op.drop_table('tidb_dns_conflicts')
    op.drop_index(op.f('ix_tidb_dns_changes_record_type'), table_name='tidb_dns_changes')
    op.drop_index(op.f('ix_tidb_dns_changes_name'), table_name='tidb_dns_changes')
    op.drop_index(op.f('ix_tidb_dns_changes_mission_id'), table_name='tidb_dns_changes')
    op.drop_index(op.f('ix_tidb_dns_changes_correlation_id'), table_name='tidb_dns_changes')
    op.drop_index(op.f('ix_tidb_dns_changes_change_type'), table_name='tidb_dns_changes')
    op.drop_table('tidb_dns_changes')
    op.drop_index(op.f('ix_tidb_discovery_conflicts_mission_id'), table_name='tidb_discovery_conflicts')
    op.drop_index(op.f('ix_tidb_discovery_conflicts_kind'), table_name='tidb_discovery_conflicts')
    op.drop_index(op.f('ix_tidb_discovery_conflicts_key'), table_name='tidb_discovery_conflicts')
    op.drop_index(op.f('ix_tidb_discovery_conflicts_correlation_id'), table_name='tidb_discovery_conflicts')
    op.drop_table('tidb_discovery_conflicts')
    # ### end Alembic commands ###
