"""technology intelligence tables

Revision ID: 7ab1a304e8bb
Revises: 7f1c9a2b0e4d
Create Date: 2026-08-08 18:04:14.487703

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ab1a304e8bb'
down_revision: str | Sequence[str] | None = '7f1c9a2b0e4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tidb_technology_categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_categories_name'), 'tidb_technology_categories', ['name'], unique=False)
    op.create_table('tidb_technology_changes',
    sa.Column('asset', sa.String(length=512), nullable=False),
    sa.Column('technology', sa.String(length=255), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_changes_asset'), 'tidb_technology_changes', ['asset'], unique=False)
    op.create_index(op.f('ix_tidb_technology_changes_change_type'), 'tidb_technology_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_tidb_technology_changes_correlation_id'), 'tidb_technology_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_changes_mission_id'), 'tidb_technology_changes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_changes_technology'), 'tidb_technology_changes', ['technology'], unique=False)
    op.create_table('tidb_technology_conflicts',
    sa.Column('asset', sa.String(length=512), nullable=False),
    sa.Column('technology', sa.String(length=255), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('selected_value', sa.Text(), nullable=False),
    sa.Column('selected_source', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_conflicts_asset'), 'tidb_technology_conflicts', ['asset'], unique=False)
    op.create_index('ix_tidb_technology_conflicts_asset_tech', 'tidb_technology_conflicts', ['asset', 'technology'], unique=False)
    op.create_index(op.f('ix_tidb_technology_conflicts_correlation_id'), 'tidb_technology_conflicts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_conflicts_mission_id'), 'tidb_technology_conflicts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_conflicts_technology'), 'tidb_technology_conflicts', ['technology'], unique=False)
    op.create_table('tidb_technology_definitions',
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tidb_technology_definitions_canonical_name', 'tidb_technology_definitions', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_tidb_technology_definitions_category'), 'tidb_technology_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_tidb_technology_definitions_family'), 'tidb_technology_definitions', ['family'], unique=False)
    op.create_table('tidb_technology_evidence',
    sa.Column('observation_id', sa.String(length=26), nullable=False),
    sa.Column('asset', sa.String(length=512), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_evidence_asset'), 'tidb_technology_evidence', ['asset'], unique=False)
    op.create_index(op.f('ix_tidb_technology_evidence_canonical_name'), 'tidb_technology_evidence', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_tidb_technology_evidence_evidence_type'), 'tidb_technology_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_tidb_technology_evidence_observation_id'), 'tidb_technology_evidence', ['observation_id'], unique=False)
    op.create_table('tidb_technology_families',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_families_name'), 'tidb_technology_families', ['name'], unique=False)
    op.create_table('tidb_technology_observations',
    sa.Column('asset', sa.String(length=512), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('software_version', sa.String(length=128), nullable=False),
    sa.Column('version_confidence', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tidb_technology_obs_asset_name', 'tidb_technology_observations', ['asset', 'canonical_name'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_asset'), 'tidb_technology_observations', ['asset'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_canonical_name'), 'tidb_technology_observations', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_category'), 'tidb_technology_observations', ['category'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_correlation_id'), 'tidb_technology_observations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_execution_id'), 'tidb_technology_observations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_family'), 'tidb_technology_observations', ['family'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_mission_id'), 'tidb_technology_observations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_target_id'), 'tidb_technology_observations', ['target_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_observations_tool_id'), 'tidb_technology_observations', ['tool_id'], unique=False)
    op.create_table('tidb_technology_runs',
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('technologies', sa.Integer(), nullable=False),
    sa.Column('versions', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_runs_correlation_id'), 'tidb_technology_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_runs_mission_id'), 'tidb_technology_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_technology_runs_status'), 'tidb_technology_runs', ['status'], unique=False)
    op.create_index(op.f('ix_tidb_technology_runs_target_key'), 'tidb_technology_runs', ['target_key'], unique=False)
    op.create_table('tidb_technology_versions',
    sa.Column('observation_id', sa.String(length=26), nullable=False),
    sa.Column('asset', sa.String(length=512), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('lower', sa.String(length=128), nullable=False),
    sa.Column('upper', sa.String(length=128), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_technology_versions_asset'), 'tidb_technology_versions', ['asset'], unique=False)
    op.create_index(op.f('ix_tidb_technology_versions_canonical_name'), 'tidb_technology_versions', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_tidb_technology_versions_observation_id'), 'tidb_technology_versions', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tidb_technology_versions_observation_id'), table_name='tidb_technology_versions')
    op.drop_index(op.f('ix_tidb_technology_versions_canonical_name'), table_name='tidb_technology_versions')
    op.drop_index(op.f('ix_tidb_technology_versions_asset'), table_name='tidb_technology_versions')
    op.drop_table('tidb_technology_versions')
    op.drop_index(op.f('ix_tidb_technology_runs_target_key'), table_name='tidb_technology_runs')
    op.drop_index(op.f('ix_tidb_technology_runs_status'), table_name='tidb_technology_runs')
    op.drop_index(op.f('ix_tidb_technology_runs_mission_id'), table_name='tidb_technology_runs')
    op.drop_index(op.f('ix_tidb_technology_runs_correlation_id'), table_name='tidb_technology_runs')
    op.drop_table('tidb_technology_runs')
    op.drop_index(op.f('ix_tidb_technology_observations_tool_id'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_target_id'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_mission_id'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_family'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_execution_id'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_correlation_id'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_category'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_canonical_name'), table_name='tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_observations_asset'), table_name='tidb_technology_observations')
    op.drop_index('ix_tidb_technology_obs_asset_name', table_name='tidb_technology_observations')
    op.drop_table('tidb_technology_observations')
    op.drop_index(op.f('ix_tidb_technology_families_name'), table_name='tidb_technology_families')
    op.drop_table('tidb_technology_families')
    op.drop_index(op.f('ix_tidb_technology_evidence_observation_id'), table_name='tidb_technology_evidence')
    op.drop_index(op.f('ix_tidb_technology_evidence_evidence_type'), table_name='tidb_technology_evidence')
    op.drop_index(op.f('ix_tidb_technology_evidence_canonical_name'), table_name='tidb_technology_evidence')
    op.drop_index(op.f('ix_tidb_technology_evidence_asset'), table_name='tidb_technology_evidence')
    op.drop_table('tidb_technology_evidence')
    op.drop_index(op.f('ix_tidb_technology_definitions_family'), table_name='tidb_technology_definitions')
    op.drop_index(op.f('ix_tidb_technology_definitions_category'), table_name='tidb_technology_definitions')
    op.drop_index('ix_tidb_technology_definitions_canonical_name', table_name='tidb_technology_definitions')
    op.drop_table('tidb_technology_definitions')
    op.drop_index(op.f('ix_tidb_technology_conflicts_technology'), table_name='tidb_technology_conflicts')
    op.drop_index(op.f('ix_tidb_technology_conflicts_mission_id'), table_name='tidb_technology_conflicts')
    op.drop_index(op.f('ix_tidb_technology_conflicts_correlation_id'), table_name='tidb_technology_conflicts')
    op.drop_index('ix_tidb_technology_conflicts_asset_tech', table_name='tidb_technology_conflicts')
    op.drop_index(op.f('ix_tidb_technology_conflicts_asset'), table_name='tidb_technology_conflicts')
    op.drop_table('tidb_technology_conflicts')
    op.drop_index(op.f('ix_tidb_technology_changes_technology'), table_name='tidb_technology_changes')
    op.drop_index(op.f('ix_tidb_technology_changes_mission_id'), table_name='tidb_technology_changes')
    op.drop_index(op.f('ix_tidb_technology_changes_correlation_id'), table_name='tidb_technology_changes')
    op.drop_index(op.f('ix_tidb_technology_changes_change_type'), table_name='tidb_technology_changes')
    op.drop_index(op.f('ix_tidb_technology_changes_asset'), table_name='tidb_technology_changes')
    op.drop_table('tidb_technology_changes')
    op.drop_index(op.f('ix_tidb_technology_categories_name'), table_name='tidb_technology_categories')
    op.drop_table('tidb_technology_categories')
    # ### end Alembic commands ###
