"""cloud saas intelligence tables

Revision ID: 7ea0dbfc111d
Revises: b7e2f9a4c1d3
Create Date: 2026-08-09 08:41:37.962095

Extends the TIDB schema with the Wave 11 cloud & SaaS attack-surface
intelligence canonical inventory: cloud providers, accounts/subscriptions/
projects/organizations/tenants, regions, resources, services, endpoints (with
control/data/identity/management plane classification), environments, identity
& IAM indicators, SaaS platforms, SaaS applications, SaaS integrations,
webhooks, third-party dependencies, storage/compute/container/Kubernetes/
database/message/gateway/CDN/load-balancer/CI/CD resource indicators,
secret-management indicators, exposure indicators (intelligence, never
vulnerabilities), generic observations, evidence and historical-change records
plus the run observability record.

Security boundary: every table stores metadata and masked indicators only —
never cloud credentials, access keys, secret values, session tokens, OAuth
secrets or private keys.

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ea0dbfc111d'
down_revision: str | Sequence[str] | None = 'b7e2f9a4c1d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tidb_cloud_accounts',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_accounts_correlation_id'), 'tidb_cloud_accounts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_accounts_kind'), 'tidb_cloud_accounts', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_accounts_mission_id'), 'tidb_cloud_accounts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_accounts_provider'), 'tidb_cloud_accounts', ['provider'], unique=False)
    op.create_index('ix_tidb_cloud_accounts_provider_kind', 'tidb_cloud_accounts', ['provider', 'kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_accounts_target_key'), 'tidb_cloud_accounts', ['target_key'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_accounts_value'), 'tidb_cloud_accounts', ['value'], unique=False)
    op.create_table('tidb_cloud_api_gateways',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('gateway_kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('backend', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_api_gateways_correlation_id'), 'tidb_cloud_api_gateways', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_api_gateways_identifier'), 'tidb_cloud_api_gateways', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_api_gateways_mission_id'), 'tidb_cloud_api_gateways', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_api_gateways_provider'), 'tidb_cloud_api_gateways', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_api_gateways_target_key'), 'tidb_cloud_api_gateways', ['target_key'], unique=False)
    op.create_table('tidb_cloud_cdns',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('origin', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_cdns_correlation_id'), 'tidb_cloud_cdns', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cdns_identifier'), 'tidb_cloud_cdns', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cdns_mission_id'), 'tidb_cloud_cdns', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cdns_provider'), 'tidb_cloud_cdns', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cdns_target_key'), 'tidb_cloud_cdns', ['target_key'], unique=False)
    op.create_table('tidb_cloud_changes',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('previous', sa.Text(), nullable=False),
    sa.Column('current', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_changes_correlation_id'), 'tidb_cloud_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_changes_mission_id'), 'tidb_cloud_changes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_changes_subject'), 'tidb_cloud_changes', ['subject'], unique=False)
    op.create_table('tidb_cloud_cicd_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_cicd_resources_correlation_id'), 'tidb_cloud_cicd_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cicd_resources_mission_id'), 'tidb_cloud_cicd_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cicd_resources_name'), 'tidb_cloud_cicd_resources', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cicd_resources_provider'), 'tidb_cloud_cicd_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_cicd_resources_target_key'), 'tidb_cloud_cicd_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_compute_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('compute_kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_compute_resources_correlation_id'), 'tidb_cloud_compute_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_compute_resources_identifier'), 'tidb_cloud_compute_resources', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_compute_resources_mission_id'), 'tidb_cloud_compute_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_compute_resources_provider'), 'tidb_cloud_compute_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_compute_resources_target_key'), 'tidb_cloud_compute_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_container_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('container_kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('registry', sa.String(length=512), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_container_resources_correlation_id'), 'tidb_cloud_container_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_container_resources_identifier'), 'tidb_cloud_container_resources', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_container_resources_mission_id'), 'tidb_cloud_container_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_container_resources_provider'), 'tidb_cloud_container_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_container_resources_target_key'), 'tidb_cloud_container_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_database_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('database_kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('technology', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('public', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_database_resources_correlation_id'), 'tidb_cloud_database_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_database_resources_identifier'), 'tidb_cloud_database_resources', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_database_resources_mission_id'), 'tidb_cloud_database_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_database_resources_provider'), 'tidb_cloud_database_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_database_resources_target_key'), 'tidb_cloud_database_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_dependencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('application', sa.String(length=255), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_dependencies_correlation_id'), 'tidb_cloud_dependencies', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_dependencies_kind'), 'tidb_cloud_dependencies', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_dependencies_mission_id'), 'tidb_cloud_dependencies', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_dependencies_name'), 'tidb_cloud_dependencies', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_dependencies_provider'), 'tidb_cloud_dependencies', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_dependencies_target_key'), 'tidb_cloud_dependencies', ['target_key'], unique=False)
    op.create_table('tidb_cloud_endpoints',
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('plane', sa.String(length=32), nullable=False),
    sa.Column('exposure', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_endpoints_correlation_id'), 'tidb_cloud_endpoints', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_endpoints_endpoint'), 'tidb_cloud_endpoints', ['endpoint'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_endpoints_exposure'), 'tidb_cloud_endpoints', ['exposure'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_endpoints_mission_id'), 'tidb_cloud_endpoints', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_endpoints_plane'), 'tidb_cloud_endpoints', ['plane'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_endpoints_provider'), 'tidb_cloud_endpoints', ['provider'], unique=False)
    op.create_index('ix_tidb_cloud_endpoints_provider_service', 'tidb_cloud_endpoints', ['provider', 'service'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_endpoints_target_key'), 'tidb_cloud_endpoints', ['target_key'], unique=False)
    op.create_table('tidb_cloud_environments',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_environments_correlation_id'), 'tidb_cloud_environments', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_environments_environment'), 'tidb_cloud_environments', ['environment'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_environments_mission_id'), 'tidb_cloud_environments', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_environments_provider'), 'tidb_cloud_environments', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_environments_target_key'), 'tidb_cloud_environments', ['target_key'], unique=False)
    op.create_table('tidb_cloud_evidence',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=26), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_evidence_correlation_id'), 'tidb_cloud_evidence', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_evidence_mission_id'), 'tidb_cloud_evidence', ['mission_id'], unique=False)
    op.create_index('ix_tidb_cloud_evidence_subject', 'tidb_cloud_evidence', ['subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_evidence_subject_id'), 'tidb_cloud_evidence', ['subject_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_evidence_subject_type'), 'tidb_cloud_evidence', ['subject_type'], unique=False)
    op.create_table('tidb_cloud_exposure_indicators',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_exposure_indicators_correlation_id'), 'tidb_cloud_exposure_indicators', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_exposure_indicators_kind'), 'tidb_cloud_exposure_indicators', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_exposure_indicators_mission_id'), 'tidb_cloud_exposure_indicators', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_exposure_indicators_subject'), 'tidb_cloud_exposure_indicators', ['subject'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_exposure_indicators_target_key'), 'tidb_cloud_exposure_indicators', ['target_key'], unique=False)
    op.create_table('tidb_cloud_identities',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('identity_kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_identities_correlation_id'), 'tidb_cloud_identities', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_identities_identity_kind'), 'tidb_cloud_identities', ['identity_kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_identities_mission_id'), 'tidb_cloud_identities', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_identities_provider'), 'tidb_cloud_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_identities_target_key'), 'tidb_cloud_identities', ['target_key'], unique=False)
    op.create_table('tidb_cloud_integrations',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('integration_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_integrations_correlation_id'), 'tidb_cloud_integrations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_integrations_integration_type'), 'tidb_cloud_integrations', ['integration_type'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_integrations_mission_id'), 'tidb_cloud_integrations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_integrations_provider'), 'tidb_cloud_integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_integrations_target_key'), 'tidb_cloud_integrations', ['target_key'], unique=False)
    op.create_table('tidb_cloud_kubernetes_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('cluster', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_kubernetes_resources_cluster'), 'tidb_cloud_kubernetes_resources', ['cluster'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_kubernetes_resources_correlation_id'), 'tidb_cloud_kubernetes_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_kubernetes_resources_kind'), 'tidb_cloud_kubernetes_resources', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_kubernetes_resources_mission_id'), 'tidb_cloud_kubernetes_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_kubernetes_resources_provider'), 'tidb_cloud_kubernetes_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_kubernetes_resources_target_key'), 'tidb_cloud_kubernetes_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_load_balancers',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('backend', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_load_balancers_correlation_id'), 'tidb_cloud_load_balancers', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_load_balancers_identifier'), 'tidb_cloud_load_balancers', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_load_balancers_mission_id'), 'tidb_cloud_load_balancers', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_load_balancers_provider'), 'tidb_cloud_load_balancers', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_load_balancers_target_key'), 'tidb_cloud_load_balancers', ['target_key'], unique=False)
    op.create_table('tidb_cloud_message_infrastructure',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_message_infrastructure_correlation_id'), 'tidb_cloud_message_infrastructure', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_message_infrastructure_identifier'), 'tidb_cloud_message_infrastructure', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_message_infrastructure_kind'), 'tidb_cloud_message_infrastructure', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_message_infrastructure_mission_id'), 'tidb_cloud_message_infrastructure', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_message_infrastructure_provider'), 'tidb_cloud_message_infrastructure', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_message_infrastructure_target_key'), 'tidb_cloud_message_infrastructure', ['target_key'], unique=False)
    op.create_table('tidb_cloud_observations',
    sa.Column('origin', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_observations_correlation_id'), 'tidb_cloud_observations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_observations_kind'), 'tidb_cloud_observations', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_observations_mission_id'), 'tidb_cloud_observations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_observations_origin'), 'tidb_cloud_observations', ['origin'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_observations_target_key'), 'tidb_cloud_observations', ['target_key'], unique=False)
    op.create_table('tidb_cloud_permissions',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_permissions_action'), 'tidb_cloud_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_permissions_correlation_id'), 'tidb_cloud_permissions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_permissions_mission_id'), 'tidb_cloud_permissions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_permissions_provider'), 'tidb_cloud_permissions', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_permissions_target_key'), 'tidb_cloud_permissions', ['target_key'], unique=False)
    op.create_table('tidb_cloud_providers',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('evidence_indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_providers_correlation_id'), 'tidb_cloud_providers', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_providers_mission_id'), 'tidb_cloud_providers', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_providers_name'), 'tidb_cloud_providers', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_providers_target_key'), 'tidb_cloud_providers', ['target_key'], unique=False)
    op.create_table('tidb_cloud_regions',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_regions_correlation_id'), 'tidb_cloud_regions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_regions_mission_id'), 'tidb_cloud_regions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_regions_provider'), 'tidb_cloud_regions', ['provider'], unique=False)
    op.create_index('ix_tidb_cloud_regions_provider_region', 'tidb_cloud_regions', ['provider', 'region'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_regions_region'), 'tidb_cloud_regions', ['region'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_regions_target_key'), 'tidb_cloud_regions', ['target_key'], unique=False)
    op.create_table('tidb_cloud_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('resource_kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('public', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_resources_correlation_id'), 'tidb_cloud_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_resources_identifier'), 'tidb_cloud_resources', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_resources_mission_id'), 'tidb_cloud_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_resources_provider'), 'tidb_cloud_resources', ['provider'], unique=False)
    op.create_index('ix_tidb_cloud_resources_provider_identifier', 'tidb_cloud_resources', ['provider', 'identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_resources_resource_kind'), 'tidb_cloud_resources', ['resource_kind'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_resources_service'), 'tidb_cloud_resources', ['service'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_resources_target_key'), 'tidb_cloud_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_roles',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('assume_role', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_roles_correlation_id'), 'tidb_cloud_roles', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_roles_mission_id'), 'tidb_cloud_roles', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_roles_name'), 'tidb_cloud_roles', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_roles_provider'), 'tidb_cloud_roles', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_roles_target_key'), 'tidb_cloud_roles', ['target_key'], unique=False)
    op.create_table('tidb_cloud_runs',
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('providers', sa.Integer(), nullable=False),
    sa.Column('accounts', sa.Integer(), nullable=False),
    sa.Column('regions', sa.Integer(), nullable=False),
    sa.Column('resources', sa.Integer(), nullable=False),
    sa.Column('services', sa.Integer(), nullable=False),
    sa.Column('endpoints', sa.Integer(), nullable=False),
    sa.Column('environments', sa.Integer(), nullable=False),
    sa.Column('identities', sa.Integer(), nullable=False),
    sa.Column('saas_providers', sa.Integer(), nullable=False),
    sa.Column('saas_integrations', sa.Integer(), nullable=False),
    sa.Column('webhooks', sa.Integer(), nullable=False),
    sa.Column('storage', sa.Integer(), nullable=False),
    sa.Column('compute', sa.Integer(), nullable=False),
    sa.Column('containers', sa.Integer(), nullable=False),
    sa.Column('kubernetes', sa.Integer(), nullable=False),
    sa.Column('databases', sa.Integer(), nullable=False),
    sa.Column('gateways', sa.Integer(), nullable=False),
    sa.Column('cdns', sa.Integer(), nullable=False),
    sa.Column('load_balancers', sa.Integer(), nullable=False),
    sa.Column('cicd', sa.Integer(), nullable=False),
    sa.Column('secrets', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_runs_correlation_id'), 'tidb_cloud_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_runs_mission_id'), 'tidb_cloud_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_runs_target_key'), 'tidb_cloud_runs', ['target_key'], unique=False)
    op.create_table('tidb_cloud_saas_applications',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('saas_provider', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_saas_applications_correlation_id'), 'tidb_cloud_saas_applications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_applications_mission_id'), 'tidb_cloud_saas_applications', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_applications_name'), 'tidb_cloud_saas_applications', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_applications_saas_provider'), 'tidb_cloud_saas_applications', ['saas_provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_applications_target_key'), 'tidb_cloud_saas_applications', ['target_key'], unique=False)
    op.create_table('tidb_cloud_saas_integrations',
    sa.Column('saas_provider', sa.String(length=64), nullable=False),
    sa.Column('integration_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('auth_mechanism', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_saas_integrations_correlation_id'), 'tidb_cloud_saas_integrations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_integrations_integration_type'), 'tidb_cloud_saas_integrations', ['integration_type'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_integrations_mission_id'), 'tidb_cloud_saas_integrations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_integrations_saas_provider'), 'tidb_cloud_saas_integrations', ['saas_provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_integrations_target_key'), 'tidb_cloud_saas_integrations', ['target_key'], unique=False)
    op.create_table('tidb_cloud_saas_providers',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_saas_providers_correlation_id'), 'tidb_cloud_saas_providers', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_providers_mission_id'), 'tidb_cloud_saas_providers', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_providers_name'), 'tidb_cloud_saas_providers', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_saas_providers_target_key'), 'tidb_cloud_saas_providers', ['target_key'], unique=False)
    op.create_table('tidb_cloud_secret_management',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=512), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_secret_management_correlation_id'), 'tidb_cloud_secret_management', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_secret_management_mission_id'), 'tidb_cloud_secret_management', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_secret_management_provider'), 'tidb_cloud_secret_management', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_secret_management_target_key'), 'tidb_cloud_secret_management', ['target_key'], unique=False)
    op.create_table('tidb_cloud_services',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_services_category'), 'tidb_cloud_services', ['category'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_services_correlation_id'), 'tidb_cloud_services', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_services_mission_id'), 'tidb_cloud_services', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_services_provider'), 'tidb_cloud_services', ['provider'], unique=False)
    op.create_index('ix_tidb_cloud_services_provider_service', 'tidb_cloud_services', ['provider', 'service'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_services_service'), 'tidb_cloud_services', ['service'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_services_target_key'), 'tidb_cloud_services', ['target_key'], unique=False)
    op.create_table('tidb_cloud_storage_resources',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('storage_kind', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('public', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_storage_resources_correlation_id'), 'tidb_cloud_storage_resources', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_storage_resources_identifier'), 'tidb_cloud_storage_resources', ['identifier'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_storage_resources_mission_id'), 'tidb_cloud_storage_resources', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_storage_resources_provider'), 'tidb_cloud_storage_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_storage_resources_target_key'), 'tidb_cloud_storage_resources', ['target_key'], unique=False)
    op.create_table('tidb_cloud_webhooks',
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('signing', sa.String(length=32), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_cloud_webhooks_correlation_id'), 'tidb_cloud_webhooks', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_webhooks_direction'), 'tidb_cloud_webhooks', ['direction'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_webhooks_endpoint'), 'tidb_cloud_webhooks', ['endpoint'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_webhooks_mission_id'), 'tidb_cloud_webhooks', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_webhooks_provider'), 'tidb_cloud_webhooks', ['provider'], unique=False)
    op.create_index(op.f('ix_tidb_cloud_webhooks_target_key'), 'tidb_cloud_webhooks', ['target_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tidb_cloud_webhooks_target_key'), table_name='tidb_cloud_webhooks')
    op.drop_index(op.f('ix_tidb_cloud_webhooks_provider'), table_name='tidb_cloud_webhooks')
    op.drop_index(op.f('ix_tidb_cloud_webhooks_mission_id'), table_name='tidb_cloud_webhooks')
    op.drop_index(op.f('ix_tidb_cloud_webhooks_endpoint'), table_name='tidb_cloud_webhooks')
    op.drop_index(op.f('ix_tidb_cloud_webhooks_direction'), table_name='tidb_cloud_webhooks')
    op.drop_index(op.f('ix_tidb_cloud_webhooks_correlation_id'), table_name='tidb_cloud_webhooks')
    op.drop_table('tidb_cloud_webhooks')
    op.drop_index(op.f('ix_tidb_cloud_storage_resources_target_key'), table_name='tidb_cloud_storage_resources')
    op.drop_index(op.f('ix_tidb_cloud_storage_resources_provider'), table_name='tidb_cloud_storage_resources')
    op.drop_index(op.f('ix_tidb_cloud_storage_resources_mission_id'), table_name='tidb_cloud_storage_resources')
    op.drop_index(op.f('ix_tidb_cloud_storage_resources_identifier'), table_name='tidb_cloud_storage_resources')
    op.drop_index(op.f('ix_tidb_cloud_storage_resources_correlation_id'), table_name='tidb_cloud_storage_resources')
    op.drop_table('tidb_cloud_storage_resources')
    op.drop_index(op.f('ix_tidb_cloud_services_target_key'), table_name='tidb_cloud_services')
    op.drop_index(op.f('ix_tidb_cloud_services_service'), table_name='tidb_cloud_services')
    op.drop_index('ix_tidb_cloud_services_provider_service', table_name='tidb_cloud_services')
    op.drop_index(op.f('ix_tidb_cloud_services_provider'), table_name='tidb_cloud_services')
    op.drop_index(op.f('ix_tidb_cloud_services_mission_id'), table_name='tidb_cloud_services')
    op.drop_index(op.f('ix_tidb_cloud_services_correlation_id'), table_name='tidb_cloud_services')
    op.drop_index(op.f('ix_tidb_cloud_services_category'), table_name='tidb_cloud_services')
    op.drop_table('tidb_cloud_services')
    op.drop_index(op.f('ix_tidb_cloud_secret_management_target_key'), table_name='tidb_cloud_secret_management')
    op.drop_index(op.f('ix_tidb_cloud_secret_management_provider'), table_name='tidb_cloud_secret_management')
    op.drop_index(op.f('ix_tidb_cloud_secret_management_mission_id'), table_name='tidb_cloud_secret_management')
    op.drop_index(op.f('ix_tidb_cloud_secret_management_correlation_id'), table_name='tidb_cloud_secret_management')
    op.drop_table('tidb_cloud_secret_management')
    op.drop_index(op.f('ix_tidb_cloud_saas_providers_target_key'), table_name='tidb_cloud_saas_providers')
    op.drop_index(op.f('ix_tidb_cloud_saas_providers_name'), table_name='tidb_cloud_saas_providers')
    op.drop_index(op.f('ix_tidb_cloud_saas_providers_mission_id'), table_name='tidb_cloud_saas_providers')
    op.drop_index(op.f('ix_tidb_cloud_saas_providers_correlation_id'), table_name='tidb_cloud_saas_providers')
    op.drop_table('tidb_cloud_saas_providers')
    op.drop_index(op.f('ix_tidb_cloud_saas_integrations_target_key'), table_name='tidb_cloud_saas_integrations')
    op.drop_index(op.f('ix_tidb_cloud_saas_integrations_saas_provider'), table_name='tidb_cloud_saas_integrations')
    op.drop_index(op.f('ix_tidb_cloud_saas_integrations_mission_id'), table_name='tidb_cloud_saas_integrations')
    op.drop_index(op.f('ix_tidb_cloud_saas_integrations_integration_type'), table_name='tidb_cloud_saas_integrations')
    op.drop_index(op.f('ix_tidb_cloud_saas_integrations_correlation_id'), table_name='tidb_cloud_saas_integrations')
    op.drop_table('tidb_cloud_saas_integrations')
    op.drop_index(op.f('ix_tidb_cloud_saas_applications_target_key'), table_name='tidb_cloud_saas_applications')
    op.drop_index(op.f('ix_tidb_cloud_saas_applications_saas_provider'), table_name='tidb_cloud_saas_applications')
    op.drop_index(op.f('ix_tidb_cloud_saas_applications_name'), table_name='tidb_cloud_saas_applications')
    op.drop_index(op.f('ix_tidb_cloud_saas_applications_mission_id'), table_name='tidb_cloud_saas_applications')
    op.drop_index(op.f('ix_tidb_cloud_saas_applications_correlation_id'), table_name='tidb_cloud_saas_applications')
    op.drop_table('tidb_cloud_saas_applications')
    op.drop_index(op.f('ix_tidb_cloud_runs_target_key'), table_name='tidb_cloud_runs')
    op.drop_index(op.f('ix_tidb_cloud_runs_mission_id'), table_name='tidb_cloud_runs')
    op.drop_index(op.f('ix_tidb_cloud_runs_correlation_id'), table_name='tidb_cloud_runs')
    op.drop_table('tidb_cloud_runs')
    op.drop_index(op.f('ix_tidb_cloud_roles_target_key'), table_name='tidb_cloud_roles')
    op.drop_index(op.f('ix_tidb_cloud_roles_provider'), table_name='tidb_cloud_roles')
    op.drop_index(op.f('ix_tidb_cloud_roles_name'), table_name='tidb_cloud_roles')
    op.drop_index(op.f('ix_tidb_cloud_roles_mission_id'), table_name='tidb_cloud_roles')
    op.drop_index(op.f('ix_tidb_cloud_roles_correlation_id'), table_name='tidb_cloud_roles')
    op.drop_table('tidb_cloud_roles')
    op.drop_index(op.f('ix_tidb_cloud_resources_target_key'), table_name='tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_resources_service'), table_name='tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_resources_resource_kind'), table_name='tidb_cloud_resources')
    op.drop_index('ix_tidb_cloud_resources_provider_identifier', table_name='tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_resources_provider'), table_name='tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_resources_mission_id'), table_name='tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_resources_identifier'), table_name='tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_resources_correlation_id'), table_name='tidb_cloud_resources')
    op.drop_table('tidb_cloud_resources')
    op.drop_index(op.f('ix_tidb_cloud_regions_target_key'), table_name='tidb_cloud_regions')
    op.drop_index(op.f('ix_tidb_cloud_regions_region'), table_name='tidb_cloud_regions')
    op.drop_index('ix_tidb_cloud_regions_provider_region', table_name='tidb_cloud_regions')
    op.drop_index(op.f('ix_tidb_cloud_regions_provider'), table_name='tidb_cloud_regions')
    op.drop_index(op.f('ix_tidb_cloud_regions_mission_id'), table_name='tidb_cloud_regions')
    op.drop_index(op.f('ix_tidb_cloud_regions_correlation_id'), table_name='tidb_cloud_regions')
    op.drop_table('tidb_cloud_regions')
    op.drop_index(op.f('ix_tidb_cloud_providers_target_key'), table_name='tidb_cloud_providers')
    op.drop_index(op.f('ix_tidb_cloud_providers_name'), table_name='tidb_cloud_providers')
    op.drop_index(op.f('ix_tidb_cloud_providers_mission_id'), table_name='tidb_cloud_providers')
    op.drop_index(op.f('ix_tidb_cloud_providers_correlation_id'), table_name='tidb_cloud_providers')
    op.drop_table('tidb_cloud_providers')
    op.drop_index(op.f('ix_tidb_cloud_permissions_target_key'), table_name='tidb_cloud_permissions')
    op.drop_index(op.f('ix_tidb_cloud_permissions_provider'), table_name='tidb_cloud_permissions')
    op.drop_index(op.f('ix_tidb_cloud_permissions_mission_id'), table_name='tidb_cloud_permissions')
    op.drop_index(op.f('ix_tidb_cloud_permissions_correlation_id'), table_name='tidb_cloud_permissions')
    op.drop_index(op.f('ix_tidb_cloud_permissions_action'), table_name='tidb_cloud_permissions')
    op.drop_table('tidb_cloud_permissions')
    op.drop_index(op.f('ix_tidb_cloud_observations_target_key'), table_name='tidb_cloud_observations')
    op.drop_index(op.f('ix_tidb_cloud_observations_origin'), table_name='tidb_cloud_observations')
    op.drop_index(op.f('ix_tidb_cloud_observations_mission_id'), table_name='tidb_cloud_observations')
    op.drop_index(op.f('ix_tidb_cloud_observations_kind'), table_name='tidb_cloud_observations')
    op.drop_index(op.f('ix_tidb_cloud_observations_correlation_id'), table_name='tidb_cloud_observations')
    op.drop_table('tidb_cloud_observations')
    op.drop_index(op.f('ix_tidb_cloud_message_infrastructure_target_key'), table_name='tidb_cloud_message_infrastructure')
    op.drop_index(op.f('ix_tidb_cloud_message_infrastructure_provider'), table_name='tidb_cloud_message_infrastructure')
    op.drop_index(op.f('ix_tidb_cloud_message_infrastructure_mission_id'), table_name='tidb_cloud_message_infrastructure')
    op.drop_index(op.f('ix_tidb_cloud_message_infrastructure_kind'), table_name='tidb_cloud_message_infrastructure')
    op.drop_index(op.f('ix_tidb_cloud_message_infrastructure_identifier'), table_name='tidb_cloud_message_infrastructure')
    op.drop_index(op.f('ix_tidb_cloud_message_infrastructure_correlation_id'), table_name='tidb_cloud_message_infrastructure')
    op.drop_table('tidb_cloud_message_infrastructure')
    op.drop_index(op.f('ix_tidb_cloud_load_balancers_target_key'), table_name='tidb_cloud_load_balancers')
    op.drop_index(op.f('ix_tidb_cloud_load_balancers_provider'), table_name='tidb_cloud_load_balancers')
    op.drop_index(op.f('ix_tidb_cloud_load_balancers_mission_id'), table_name='tidb_cloud_load_balancers')
    op.drop_index(op.f('ix_tidb_cloud_load_balancers_identifier'), table_name='tidb_cloud_load_balancers')
    op.drop_index(op.f('ix_tidb_cloud_load_balancers_correlation_id'), table_name='tidb_cloud_load_balancers')
    op.drop_table('tidb_cloud_load_balancers')
    op.drop_index(op.f('ix_tidb_cloud_kubernetes_resources_target_key'), table_name='tidb_cloud_kubernetes_resources')
    op.drop_index(op.f('ix_tidb_cloud_kubernetes_resources_provider'), table_name='tidb_cloud_kubernetes_resources')
    op.drop_index(op.f('ix_tidb_cloud_kubernetes_resources_mission_id'), table_name='tidb_cloud_kubernetes_resources')
    op.drop_index(op.f('ix_tidb_cloud_kubernetes_resources_kind'), table_name='tidb_cloud_kubernetes_resources')
    op.drop_index(op.f('ix_tidb_cloud_kubernetes_resources_correlation_id'), table_name='tidb_cloud_kubernetes_resources')
    op.drop_index(op.f('ix_tidb_cloud_kubernetes_resources_cluster'), table_name='tidb_cloud_kubernetes_resources')
    op.drop_table('tidb_cloud_kubernetes_resources')
    op.drop_index(op.f('ix_tidb_cloud_integrations_target_key'), table_name='tidb_cloud_integrations')
    op.drop_index(op.f('ix_tidb_cloud_integrations_provider'), table_name='tidb_cloud_integrations')
    op.drop_index(op.f('ix_tidb_cloud_integrations_mission_id'), table_name='tidb_cloud_integrations')
    op.drop_index(op.f('ix_tidb_cloud_integrations_integration_type'), table_name='tidb_cloud_integrations')
    op.drop_index(op.f('ix_tidb_cloud_integrations_correlation_id'), table_name='tidb_cloud_integrations')
    op.drop_table('tidb_cloud_integrations')
    op.drop_index(op.f('ix_tidb_cloud_identities_target_key'), table_name='tidb_cloud_identities')
    op.drop_index(op.f('ix_tidb_cloud_identities_provider'), table_name='tidb_cloud_identities')
    op.drop_index(op.f('ix_tidb_cloud_identities_mission_id'), table_name='tidb_cloud_identities')
    op.drop_index(op.f('ix_tidb_cloud_identities_identity_kind'), table_name='tidb_cloud_identities')
    op.drop_index(op.f('ix_tidb_cloud_identities_correlation_id'), table_name='tidb_cloud_identities')
    op.drop_table('tidb_cloud_identities')
    op.drop_index(op.f('ix_tidb_cloud_exposure_indicators_target_key'), table_name='tidb_cloud_exposure_indicators')
    op.drop_index(op.f('ix_tidb_cloud_exposure_indicators_subject'), table_name='tidb_cloud_exposure_indicators')
    op.drop_index(op.f('ix_tidb_cloud_exposure_indicators_mission_id'), table_name='tidb_cloud_exposure_indicators')
    op.drop_index(op.f('ix_tidb_cloud_exposure_indicators_kind'), table_name='tidb_cloud_exposure_indicators')
    op.drop_index(op.f('ix_tidb_cloud_exposure_indicators_correlation_id'), table_name='tidb_cloud_exposure_indicators')
    op.drop_table('tidb_cloud_exposure_indicators')
    op.drop_index(op.f('ix_tidb_cloud_evidence_subject_type'), table_name='tidb_cloud_evidence')
    op.drop_index(op.f('ix_tidb_cloud_evidence_subject_id'), table_name='tidb_cloud_evidence')
    op.drop_index('ix_tidb_cloud_evidence_subject', table_name='tidb_cloud_evidence')
    op.drop_index(op.f('ix_tidb_cloud_evidence_mission_id'), table_name='tidb_cloud_evidence')
    op.drop_index(op.f('ix_tidb_cloud_evidence_correlation_id'), table_name='tidb_cloud_evidence')
    op.drop_table('tidb_cloud_evidence')
    op.drop_index(op.f('ix_tidb_cloud_environments_target_key'), table_name='tidb_cloud_environments')
    op.drop_index(op.f('ix_tidb_cloud_environments_provider'), table_name='tidb_cloud_environments')
    op.drop_index(op.f('ix_tidb_cloud_environments_mission_id'), table_name='tidb_cloud_environments')
    op.drop_index(op.f('ix_tidb_cloud_environments_environment'), table_name='tidb_cloud_environments')
    op.drop_index(op.f('ix_tidb_cloud_environments_correlation_id'), table_name='tidb_cloud_environments')
    op.drop_table('tidb_cloud_environments')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_target_key'), table_name='tidb_cloud_endpoints')
    op.drop_index('ix_tidb_cloud_endpoints_provider_service', table_name='tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_provider'), table_name='tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_plane'), table_name='tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_mission_id'), table_name='tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_exposure'), table_name='tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_endpoint'), table_name='tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_endpoints_correlation_id'), table_name='tidb_cloud_endpoints')
    op.drop_table('tidb_cloud_endpoints')
    op.drop_index(op.f('ix_tidb_cloud_dependencies_target_key'), table_name='tidb_cloud_dependencies')
    op.drop_index(op.f('ix_tidb_cloud_dependencies_provider'), table_name='tidb_cloud_dependencies')
    op.drop_index(op.f('ix_tidb_cloud_dependencies_name'), table_name='tidb_cloud_dependencies')
    op.drop_index(op.f('ix_tidb_cloud_dependencies_mission_id'), table_name='tidb_cloud_dependencies')
    op.drop_index(op.f('ix_tidb_cloud_dependencies_kind'), table_name='tidb_cloud_dependencies')
    op.drop_index(op.f('ix_tidb_cloud_dependencies_correlation_id'), table_name='tidb_cloud_dependencies')
    op.drop_table('tidb_cloud_dependencies')
    op.drop_index(op.f('ix_tidb_cloud_database_resources_target_key'), table_name='tidb_cloud_database_resources')
    op.drop_index(op.f('ix_tidb_cloud_database_resources_provider'), table_name='tidb_cloud_database_resources')
    op.drop_index(op.f('ix_tidb_cloud_database_resources_mission_id'), table_name='tidb_cloud_database_resources')
    op.drop_index(op.f('ix_tidb_cloud_database_resources_identifier'), table_name='tidb_cloud_database_resources')
    op.drop_index(op.f('ix_tidb_cloud_database_resources_correlation_id'), table_name='tidb_cloud_database_resources')
    op.drop_table('tidb_cloud_database_resources')
    op.drop_index(op.f('ix_tidb_cloud_container_resources_target_key'), table_name='tidb_cloud_container_resources')
    op.drop_index(op.f('ix_tidb_cloud_container_resources_provider'), table_name='tidb_cloud_container_resources')
    op.drop_index(op.f('ix_tidb_cloud_container_resources_mission_id'), table_name='tidb_cloud_container_resources')
    op.drop_index(op.f('ix_tidb_cloud_container_resources_identifier'), table_name='tidb_cloud_container_resources')
    op.drop_index(op.f('ix_tidb_cloud_container_resources_correlation_id'), table_name='tidb_cloud_container_resources')
    op.drop_table('tidb_cloud_container_resources')
    op.drop_index(op.f('ix_tidb_cloud_compute_resources_target_key'), table_name='tidb_cloud_compute_resources')
    op.drop_index(op.f('ix_tidb_cloud_compute_resources_provider'), table_name='tidb_cloud_compute_resources')
    op.drop_index(op.f('ix_tidb_cloud_compute_resources_mission_id'), table_name='tidb_cloud_compute_resources')
    op.drop_index(op.f('ix_tidb_cloud_compute_resources_identifier'), table_name='tidb_cloud_compute_resources')
    op.drop_index(op.f('ix_tidb_cloud_compute_resources_correlation_id'), table_name='tidb_cloud_compute_resources')
    op.drop_table('tidb_cloud_compute_resources')
    op.drop_index(op.f('ix_tidb_cloud_cicd_resources_target_key'), table_name='tidb_cloud_cicd_resources')
    op.drop_index(op.f('ix_tidb_cloud_cicd_resources_provider'), table_name='tidb_cloud_cicd_resources')
    op.drop_index(op.f('ix_tidb_cloud_cicd_resources_name'), table_name='tidb_cloud_cicd_resources')
    op.drop_index(op.f('ix_tidb_cloud_cicd_resources_mission_id'), table_name='tidb_cloud_cicd_resources')
    op.drop_index(op.f('ix_tidb_cloud_cicd_resources_correlation_id'), table_name='tidb_cloud_cicd_resources')
    op.drop_table('tidb_cloud_cicd_resources')
    op.drop_index(op.f('ix_tidb_cloud_changes_subject'), table_name='tidb_cloud_changes')
    op.drop_index(op.f('ix_tidb_cloud_changes_mission_id'), table_name='tidb_cloud_changes')
    op.drop_index(op.f('ix_tidb_cloud_changes_correlation_id'), table_name='tidb_cloud_changes')
    op.drop_table('tidb_cloud_changes')
    op.drop_index(op.f('ix_tidb_cloud_cdns_target_key'), table_name='tidb_cloud_cdns')
    op.drop_index(op.f('ix_tidb_cloud_cdns_provider'), table_name='tidb_cloud_cdns')
    op.drop_index(op.f('ix_tidb_cloud_cdns_mission_id'), table_name='tidb_cloud_cdns')
    op.drop_index(op.f('ix_tidb_cloud_cdns_identifier'), table_name='tidb_cloud_cdns')
    op.drop_index(op.f('ix_tidb_cloud_cdns_correlation_id'), table_name='tidb_cloud_cdns')
    op.drop_table('tidb_cloud_cdns')
    op.drop_index(op.f('ix_tidb_cloud_api_gateways_target_key'), table_name='tidb_cloud_api_gateways')
    op.drop_index(op.f('ix_tidb_cloud_api_gateways_provider'), table_name='tidb_cloud_api_gateways')
    op.drop_index(op.f('ix_tidb_cloud_api_gateways_mission_id'), table_name='tidb_cloud_api_gateways')
    op.drop_index(op.f('ix_tidb_cloud_api_gateways_identifier'), table_name='tidb_cloud_api_gateways')
    op.drop_index(op.f('ix_tidb_cloud_api_gateways_correlation_id'), table_name='tidb_cloud_api_gateways')
    op.drop_table('tidb_cloud_api_gateways')
    op.drop_index(op.f('ix_tidb_cloud_accounts_value'), table_name='tidb_cloud_accounts')
    op.drop_index(op.f('ix_tidb_cloud_accounts_target_key'), table_name='tidb_cloud_accounts')
    op.drop_index('ix_tidb_cloud_accounts_provider_kind', table_name='tidb_cloud_accounts')
    op.drop_index(op.f('ix_tidb_cloud_accounts_provider'), table_name='tidb_cloud_accounts')
    op.drop_index(op.f('ix_tidb_cloud_accounts_mission_id'), table_name='tidb_cloud_accounts')
    op.drop_index(op.f('ix_tidb_cloud_accounts_kind'), table_name='tidb_cloud_accounts')
    op.drop_index(op.f('ix_tidb_cloud_accounts_correlation_id'), table_name='tidb_cloud_accounts')
    op.drop_table('tidb_cloud_accounts')
    # ### end Alembic commands ###
