"""topology relationship, conflict, change, cluster and build tables

Revision ID: 7f1c9a2b0e4d
Revises: 53b3e0bb8ed2
Create Date: 2026-08-08 06:30:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f1c9a2b0e4d'
down_revision: str | Sequence[str] | None = '53b3e0bb8ed2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tidb_topology_builds',
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entities_processed', sa.Integer(), nullable=False),
    sa.Column('relationships_processed', sa.Integer(), nullable=False),
    sa.Column('new_relationships', sa.Integer(), nullable=False),
    sa.Column('updated_relationships', sa.Integer(), nullable=False),
    sa.Column('removed_relationships', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_topology_builds_correlation_id'), 'tidb_topology_builds', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_builds_mission_id'), 'tidb_topology_builds', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_builds_status'), 'tidb_topology_builds', ['status'], unique=False)
    op.create_index(op.f('ix_tidb_topology_builds_target_key'), 'tidb_topology_builds', ['target_key'], unique=False)
    op.create_table('tidb_topology_changes',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_topology_changes_change_type'), 'tidb_topology_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_tidb_topology_changes_correlation_id'), 'tidb_topology_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_changes_key'), 'tidb_topology_changes', ['key'], unique=False)
    op.create_index(op.f('ix_tidb_topology_changes_kind'), 'tidb_topology_changes', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_topology_changes_mission_id'), 'tidb_topology_changes', ['mission_id'], unique=False)
    op.create_table('tidb_topology_clusters',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cluster_type', sa.String(length=32), nullable=False),
    sa.Column('entity_keys', sa.JSON(), nullable=False),
    sa.Column('metric', sa.JSON(), nullable=False),
    sa.Column('detected_by', sa.String(length=255), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_topology_clusters_cluster_type'), 'tidb_topology_clusters', ['cluster_type'], unique=False)
    op.create_index(op.f('ix_tidb_topology_clusters_correlation_id'), 'tidb_topology_clusters', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_clusters_mission_id'), 'tidb_topology_clusters', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_clusters_name'), 'tidb_topology_clusters', ['name'], unique=False)
    op.create_table('tidb_topology_conflicts',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('selected_value', sa.Text(), nullable=False),
    sa.Column('selected_source', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_topology_conflicts_correlation_id'), 'tidb_topology_conflicts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_conflicts_key'), 'tidb_topology_conflicts', ['key'], unique=False)
    op.create_index(op.f('ix_tidb_topology_conflicts_kind'), 'tidb_topology_conflicts', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_topology_conflicts_mission_id'), 'tidb_topology_conflicts', ['mission_id'], unique=False)
    op.create_table('tidb_topology_relationships',
    sa.Column('rel_type', sa.String(length=64), nullable=False),
    sa.Column('source_entity', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.String(length=512), nullable=False),
    sa.Column('target_entity', sa.String(length=32), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_id', sa.String(length=26), nullable=True),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('relationship_key', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_topology_relationships_correlation_id'), 'tidb_topology_relationships', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_execution_id'), 'tidb_topology_relationships', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_in_scope'), 'tidb_topology_relationships', ['in_scope'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_mission_id'), 'tidb_topology_relationships', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_rel_type'), 'tidb_topology_relationships', ['rel_type'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_relationship_key'), 'tidb_topology_relationships', ['relationship_key'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_source_entity'), 'tidb_topology_relationships', ['source_entity'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_source_id'), 'tidb_topology_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_source_key'), 'tidb_topology_relationships', ['source_key'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_target_entity'), 'tidb_topology_relationships', ['target_entity'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_target_id'), 'tidb_topology_relationships', ['target_id'], unique=False)
    op.create_index(op.f('ix_tidb_topology_relationships_target_key'), 'tidb_topology_relationships', ['target_key'], unique=False)
    op.create_index('ix_tidb_topology_rel_key_type', 'tidb_topology_relationships', ['relationship_key', 'rel_type'], unique=False)
    op.create_index('ix_tidb_topology_rel_source', 'tidb_topology_relationships', ['source_entity', 'source_key'], unique=False)
    op.create_index('ix_tidb_topology_rel_target', 'tidb_topology_relationships', ['target_entity', 'target_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tidb_topology_rel_target', table_name='tidb_topology_relationships')
    op.drop_index('ix_tidb_topology_rel_source', table_name='tidb_topology_relationships')
    op.drop_index('ix_tidb_topology_rel_key_type', table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_target_key'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_target_id'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_target_entity'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_source_key'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_source_id'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_source_entity'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_relationship_key'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_rel_type'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_mission_id'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_in_scope'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_execution_id'), table_name='tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_relationships_correlation_id'), table_name='tidb_topology_relationships')
    op.drop_table('tidb_topology_relationships')
    op.drop_index(op.f('ix_tidb_topology_conflicts_mission_id'), table_name='tidb_topology_conflicts')
    op.drop_index(op.f('ix_tidb_topology_conflicts_kind'), table_name='tidb_topology_conflicts')
    op.drop_index(op.f('ix_tidb_topology_conflicts_key'), table_name='tidb_topology_conflicts')
    op.drop_index(op.f('ix_tidb_topology_conflicts_correlation_id'), table_name='tidb_topology_conflicts')
    op.drop_table('tidb_topology_conflicts')
    op.drop_index(op.f('ix_tidb_topology_clusters_name'), table_name='tidb_topology_clusters')
    op.drop_index(op.f('ix_tidb_topology_clusters_mission_id'), table_name='tidb_topology_clusters')
    op.drop_index(op.f('ix_tidb_topology_clusters_correlation_id'), table_name='tidb_topology_clusters')
    op.drop_index(op.f('ix_tidb_topology_clusters_cluster_type'), table_name='tidb_topology_clusters')
    op.drop_table('tidb_topology_clusters')
    op.drop_index(op.f('ix_tidb_topology_changes_mission_id'), table_name='tidb_topology_changes')
    op.drop_index(op.f('ix_tidb_topology_changes_kind'), table_name='tidb_topology_changes')
    op.drop_index(op.f('ix_tidb_topology_changes_key'), table_name='tidb_topology_changes')
    op.drop_index(op.f('ix_tidb_topology_changes_correlation_id'), table_name='tidb_topology_changes')
    op.drop_index(op.f('ix_tidb_topology_changes_change_type'), table_name='tidb_topology_changes')
    op.drop_table('tidb_topology_changes')
    op.drop_index(op.f('ix_tidb_topology_builds_target_key'), table_name='tidb_topology_builds')
    op.drop_index(op.f('ix_tidb_topology_builds_status'), table_name='tidb_topology_builds')
    op.drop_index(op.f('ix_tidb_topology_builds_mission_id'), table_name='tidb_topology_builds')
    op.drop_index(op.f('ix_tidb_topology_builds_correlation_id'), table_name='tidb_topology_builds')
    op.drop_table('tidb_topology_builds')
    # ### end Alembic commands ###
