"""javascript intelligence tables

Revision ID: c51bafedb05e
Revises: 9c2a1b7d3f5e
Create Date: 2026-08-09 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c51bafedb05e'
down_revision: str | Sequence[str] | None = '9c2a1b7d3f5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tidb_js_intelligence_assets',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=512), nullable=False),
    sa.Column('parent_url', sa.Text(), nullable=False),
    sa.Column('asset_kind', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer()),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.Text(), nullable=False),
    sa.Column('last_modified', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_assets_hash_url'), 'tidb_js_intelligence_assets', ['content_hash', 'url'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_asset_kind'), 'tidb_js_intelligence_assets', ['asset_kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_content_hash'), 'tidb_js_intelligence_assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_correlation_id'), 'tidb_js_intelligence_assets', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_execution_id'), 'tidb_js_intelligence_assets', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_mission_id'), 'tidb_js_intelligence_assets', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_target_key'), 'tidb_js_intelligence_assets', ['target_key'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_assets_tool_id'), 'tidb_js_intelligence_assets', ['tool_id'], unique=False)

    op.create_table('tidb_js_intelligence_auth',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_auth_correlation_id'), 'tidb_js_intelligence_auth', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_auth_execution_id'), 'tidb_js_intelligence_auth', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_auth_kind'), 'tidb_js_intelligence_auth', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_auth_mission_id'), 'tidb_js_intelligence_auth', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_auth_target_key'), 'tidb_js_intelligence_auth', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_changes',
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('previous', sa.Text(), nullable=False),
    sa.Column('current', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_changes_artifact_type'), 'tidb_js_intelligence_changes', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_changes_change_type'), 'tidb_js_intelligence_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_changes_correlation_id'), 'tidb_js_intelligence_changes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_changes_mission_id'), 'tidb_js_intelligence_changes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_changes_subject'), 'tidb_js_intelligence_changes', ['subject'], unique=False)

    op.create_table('tidb_js_intelligence_configuration',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_configuration_correlation_id'), 'tidb_js_intelligence_configuration', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_configuration_execution_id'), 'tidb_js_intelligence_configuration', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_configuration_kind'), 'tidb_js_intelligence_configuration', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_configuration_mission_id'), 'tidb_js_intelligence_configuration', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_configuration_target_key'), 'tidb_js_intelligence_configuration', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_conflicts',
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('selected', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_conflicts_subject_type'), 'tidb_js_intelligence_conflicts', ['subject', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_conflicts_artifact_type'), 'tidb_js_intelligence_conflicts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_conflicts_correlation_id'), 'tidb_js_intelligence_conflicts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_conflicts_mission_id'), 'tidb_js_intelligence_conflicts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_conflicts_subject'), 'tidb_js_intelligence_conflicts', ['subject'], unique=False)

    op.create_table('tidb_js_intelligence_dependencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_dependencies_correlation_id'), 'tidb_js_intelligence_dependencies', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_dependencies_execution_id'), 'tidb_js_intelligence_dependencies', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_dependencies_mission_id'), 'tidb_js_intelligence_dependencies', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_dependencies_name'), 'tidb_js_intelligence_dependencies', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_dependencies_target_key'), 'tidb_js_intelligence_dependencies', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_domains',
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('hostname', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_domains_correlation_id'), 'tidb_js_intelligence_domains', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_domains_domain'), 'tidb_js_intelligence_domains', ['domain'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_domains_execution_id'), 'tidb_js_intelligence_domains', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_domains_mission_id'), 'tidb_js_intelligence_domains', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_domains_relation'), 'tidb_js_intelligence_domains', ['relation'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_domains_target_key'), 'tidb_js_intelligence_domains', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_endpoints',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('api_type', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_endpoints_url_method'), 'tidb_js_intelligence_endpoints', ['url', 'method'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_api_type'), 'tidb_js_intelligence_endpoints', ['api_type'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_correlation_id'), 'tidb_js_intelligence_endpoints', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_execution_id'), 'tidb_js_intelligence_endpoints', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_kind'), 'tidb_js_intelligence_endpoints', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_method'), 'tidb_js_intelligence_endpoints', ['method'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_mission_id'), 'tidb_js_intelligence_endpoints', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_endpoints_target_key'), 'tidb_js_intelligence_endpoints', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_imports',
    sa.Column('specifier', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('chunk', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_imports_correlation_id'), 'tidb_js_intelligence_imports', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_imports_execution_id'), 'tidb_js_intelligence_imports', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_imports_mission_id'), 'tidb_js_intelligence_imports', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_imports_target_key'), 'tidb_js_intelligence_imports', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_routes',
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_routes_correlation_id'), 'tidb_js_intelligence_routes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_routes_execution_id'), 'tidb_js_intelligence_routes', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_routes_framework'), 'tidb_js_intelligence_routes', ['framework'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_routes_mission_id'), 'tidb_js_intelligence_routes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_routes_target_key'), 'tidb_js_intelligence_routes', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_runs',
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assets', sa.Integer(), nullable=False),
    sa.Column('endpoints', sa.Integer(), nullable=False),
    sa.Column('routes', sa.Integer(), nullable=False),
    sa.Column('secrets', sa.Integer(), nullable=False),
    sa.Column('services', sa.Integer(), nullable=False),
    sa.Column('dependencies', sa.Integer(), nullable=False),
    sa.Column('technologies', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32)),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_runs_correlation_id'), 'tidb_js_intelligence_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_runs_mission_id'), 'tidb_js_intelligence_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_runs_status'), 'tidb_js_intelligence_runs', ['status'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_runs_target_key'), 'tidb_js_intelligence_runs', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_secrets',
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('masked_value', sa.Text(), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer()),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('detection_rule', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_classification'), 'tidb_js_intelligence_secrets', ['classification'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_correlation_id'), 'tidb_js_intelligence_secrets', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_execution_id'), 'tidb_js_intelligence_secrets', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_mission_id'), 'tidb_js_intelligence_secrets', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_target_key'), 'tidb_js_intelligence_secrets', ['target_key'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_tier'), 'tidb_js_intelligence_secrets', ['tier'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_secrets_value_hash'), 'tidb_js_intelligence_secrets', ['value_hash'], unique=False)
    op.create_index(op.f('ix_tidb_js_secrets_hash_class'), 'tidb_js_intelligence_secrets', ['value_hash', 'classification'], unique=False)

    op.create_table('tidb_js_intelligence_security',
    sa.Column('api', sa.String(length=32), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_security_api'), 'tidb_js_intelligence_security', ['api'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_security_correlation_id'), 'tidb_js_intelligence_security', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_security_execution_id'), 'tidb_js_intelligence_security', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_security_mission_id'), 'tidb_js_intelligence_security', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_security_target_key'), 'tidb_js_intelligence_security', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_services',
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_services_category'), 'tidb_js_intelligence_services', ['category'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_services_correlation_id'), 'tidb_js_intelligence_services', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_services_execution_id'), 'tidb_js_intelligence_services', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_services_mission_id'), 'tidb_js_intelligence_services', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_services_target_key'), 'tidb_js_intelligence_services', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_storage',
    sa.Column('storage_type', sa.String(length=32), nullable=False),
    sa.Column('key_pattern', sa.Text(), nullable=False),
    sa.Column('usage_context', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_storage_correlation_id'), 'tidb_js_intelligence_storage', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_storage_execution_id'), 'tidb_js_intelligence_storage', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_storage_mission_id'), 'tidb_js_intelligence_storage', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_storage_storage_type'), 'tidb_js_intelligence_storage', ['storage_type'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_storage_target_key'), 'tidb_js_intelligence_storage', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_technology',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('version_confidence', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_technology_correlation_id'), 'tidb_js_intelligence_technology', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_technology_execution_id'), 'tidb_js_intelligence_technology', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_technology_kind'), 'tidb_js_intelligence_technology', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_technology_mission_id'), 'tidb_js_intelligence_technology', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_technology_name'), 'tidb_js_intelligence_technology', ['name'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_technology_target_key'), 'tidb_js_intelligence_technology', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_wasm',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_wasm_correlation_id'), 'tidb_js_intelligence_wasm', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_wasm_execution_id'), 'tidb_js_intelligence_wasm', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_wasm_kind'), 'tidb_js_intelligence_wasm', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_wasm_mission_id'), 'tidb_js_intelligence_wasm', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_wasm_target_key'), 'tidb_js_intelligence_wasm', ['target_key'], unique=False)

    op.create_table('tidb_js_intelligence_workers',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('registration_context', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=False),
    sa.Column('mission_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32)),
    sa.Column('first_seen', sa.String(length=32)),
    sa.Column('last_seen', sa.String(length=32)),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(length=32)),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tidb_js_intelligence_workers_correlation_id'), 'tidb_js_intelligence_workers', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_workers_execution_id'), 'tidb_js_intelligence_workers', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_workers_kind'), 'tidb_js_intelligence_workers', ['kind'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_workers_mission_id'), 'tidb_js_intelligence_workers', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tidb_js_intelligence_workers_target_key'), 'tidb_js_intelligence_workers', ['target_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tidb_js_intelligence_workers_correlation_id'), table_name='tidb_js_intelligence_workers')
    op.drop_index(op.f('ix_tidb_js_intelligence_workers_execution_id'), table_name='tidb_js_intelligence_workers')
    op.drop_index(op.f('ix_tidb_js_intelligence_workers_kind'), table_name='tidb_js_intelligence_workers')
    op.drop_index(op.f('ix_tidb_js_intelligence_workers_mission_id'), table_name='tidb_js_intelligence_workers')
    op.drop_index(op.f('ix_tidb_js_intelligence_workers_target_key'), table_name='tidb_js_intelligence_workers')
    op.drop_table('tidb_js_intelligence_workers')
    op.drop_index(op.f('ix_tidb_js_intelligence_wasm_correlation_id'), table_name='tidb_js_intelligence_wasm')
    op.drop_index(op.f('ix_tidb_js_intelligence_wasm_execution_id'), table_name='tidb_js_intelligence_wasm')
    op.drop_index(op.f('ix_tidb_js_intelligence_wasm_kind'), table_name='tidb_js_intelligence_wasm')
    op.drop_index(op.f('ix_tidb_js_intelligence_wasm_mission_id'), table_name='tidb_js_intelligence_wasm')
    op.drop_index(op.f('ix_tidb_js_intelligence_wasm_target_key'), table_name='tidb_js_intelligence_wasm')
    op.drop_table('tidb_js_intelligence_wasm')
    op.drop_index(op.f('ix_tidb_js_intelligence_technology_correlation_id'), table_name='tidb_js_intelligence_technology')
    op.drop_index(op.f('ix_tidb_js_intelligence_technology_execution_id'), table_name='tidb_js_intelligence_technology')
    op.drop_index(op.f('ix_tidb_js_intelligence_technology_kind'), table_name='tidb_js_intelligence_technology')
    op.drop_index(op.f('ix_tidb_js_intelligence_technology_mission_id'), table_name='tidb_js_intelligence_technology')
    op.drop_index(op.f('ix_tidb_js_intelligence_technology_name'), table_name='tidb_js_intelligence_technology')
    op.drop_index(op.f('ix_tidb_js_intelligence_technology_target_key'), table_name='tidb_js_intelligence_technology')
    op.drop_table('tidb_js_intelligence_technology')
    op.drop_index(op.f('ix_tidb_js_intelligence_storage_correlation_id'), table_name='tidb_js_intelligence_storage')
    op.drop_index(op.f('ix_tidb_js_intelligence_storage_execution_id'), table_name='tidb_js_intelligence_storage')
    op.drop_index(op.f('ix_tidb_js_intelligence_storage_mission_id'), table_name='tidb_js_intelligence_storage')
    op.drop_index(op.f('ix_tidb_js_intelligence_storage_storage_type'), table_name='tidb_js_intelligence_storage')
    op.drop_index(op.f('ix_tidb_js_intelligence_storage_target_key'), table_name='tidb_js_intelligence_storage')
    op.drop_table('tidb_js_intelligence_storage')
    op.drop_index(op.f('ix_tidb_js_intelligence_services_category'), table_name='tidb_js_intelligence_services')
    op.drop_index(op.f('ix_tidb_js_intelligence_services_correlation_id'), table_name='tidb_js_intelligence_services')
    op.drop_index(op.f('ix_tidb_js_intelligence_services_execution_id'), table_name='tidb_js_intelligence_services')
    op.drop_index(op.f('ix_tidb_js_intelligence_services_mission_id'), table_name='tidb_js_intelligence_services')
    op.drop_index(op.f('ix_tidb_js_intelligence_services_target_key'), table_name='tidb_js_intelligence_services')
    op.drop_table('tidb_js_intelligence_services')
    op.drop_index(op.f('ix_tidb_js_intelligence_security_api'), table_name='tidb_js_intelligence_security')
    op.drop_index(op.f('ix_tidb_js_intelligence_security_correlation_id'), table_name='tidb_js_intelligence_security')
    op.drop_index(op.f('ix_tidb_js_intelligence_security_execution_id'), table_name='tidb_js_intelligence_security')
    op.drop_index(op.f('ix_tidb_js_intelligence_security_mission_id'), table_name='tidb_js_intelligence_security')
    op.drop_index(op.f('ix_tidb_js_intelligence_security_target_key'), table_name='tidb_js_intelligence_security')
    op.drop_table('tidb_js_intelligence_security')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_classification'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_correlation_id'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_execution_id'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_mission_id'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_target_key'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_tier'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_secrets_value_hash'), table_name='tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_secrets_hash_class'), table_name='tidb_js_intelligence_secrets')
    op.drop_table('tidb_js_intelligence_secrets')
    op.drop_index(op.f('ix_tidb_js_intelligence_runs_correlation_id'), table_name='tidb_js_intelligence_runs')
    op.drop_index(op.f('ix_tidb_js_intelligence_runs_mission_id'), table_name='tidb_js_intelligence_runs')
    op.drop_index(op.f('ix_tidb_js_intelligence_runs_status'), table_name='tidb_js_intelligence_runs')
    op.drop_index(op.f('ix_tidb_js_intelligence_runs_target_key'), table_name='tidb_js_intelligence_runs')
    op.drop_table('tidb_js_intelligence_runs')
    op.drop_index(op.f('ix_tidb_js_intelligence_routes_correlation_id'), table_name='tidb_js_intelligence_routes')
    op.drop_index(op.f('ix_tidb_js_intelligence_routes_execution_id'), table_name='tidb_js_intelligence_routes')
    op.drop_index(op.f('ix_tidb_js_intelligence_routes_framework'), table_name='tidb_js_intelligence_routes')
    op.drop_index(op.f('ix_tidb_js_intelligence_routes_mission_id'), table_name='tidb_js_intelligence_routes')
    op.drop_index(op.f('ix_tidb_js_intelligence_routes_target_key'), table_name='tidb_js_intelligence_routes')
    op.drop_table('tidb_js_intelligence_routes')
    op.drop_index(op.f('ix_tidb_js_intelligence_imports_correlation_id'), table_name='tidb_js_intelligence_imports')
    op.drop_index(op.f('ix_tidb_js_intelligence_imports_execution_id'), table_name='tidb_js_intelligence_imports')
    op.drop_index(op.f('ix_tidb_js_intelligence_imports_mission_id'), table_name='tidb_js_intelligence_imports')
    op.drop_index(op.f('ix_tidb_js_intelligence_imports_target_key'), table_name='tidb_js_intelligence_imports')
    op.drop_table('tidb_js_intelligence_imports')
    op.drop_index(op.f('ix_tidb_js_endpoints_url_method'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_api_type'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_correlation_id'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_execution_id'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_kind'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_method'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_mission_id'), table_name='tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_endpoints_target_key'), table_name='tidb_js_intelligence_endpoints')
    op.drop_table('tidb_js_intelligence_endpoints')
    op.drop_index(op.f('ix_tidb_js_intelligence_domains_correlation_id'), table_name='tidb_js_intelligence_domains')
    op.drop_index(op.f('ix_tidb_js_intelligence_domains_domain'), table_name='tidb_js_intelligence_domains')
    op.drop_index(op.f('ix_tidb_js_intelligence_domains_execution_id'), table_name='tidb_js_intelligence_domains')
    op.drop_index(op.f('ix_tidb_js_intelligence_domains_mission_id'), table_name='tidb_js_intelligence_domains')
    op.drop_index(op.f('ix_tidb_js_intelligence_domains_relation'), table_name='tidb_js_intelligence_domains')
    op.drop_index(op.f('ix_tidb_js_intelligence_domains_target_key'), table_name='tidb_js_intelligence_domains')
    op.drop_table('tidb_js_intelligence_domains')
    op.drop_index(op.f('ix_tidb_js_intelligence_dependencies_correlation_id'), table_name='tidb_js_intelligence_dependencies')
    op.drop_index(op.f('ix_tidb_js_intelligence_dependencies_execution_id'), table_name='tidb_js_intelligence_dependencies')
    op.drop_index(op.f('ix_tidb_js_intelligence_dependencies_mission_id'), table_name='tidb_js_intelligence_dependencies')
    op.drop_index(op.f('ix_tidb_js_intelligence_dependencies_name'), table_name='tidb_js_intelligence_dependencies')
    op.drop_index(op.f('ix_tidb_js_intelligence_dependencies_target_key'), table_name='tidb_js_intelligence_dependencies')
    op.drop_table('tidb_js_intelligence_dependencies')
    op.drop_index(op.f('ix_tidb_js_conflicts_subject_type'), table_name='tidb_js_intelligence_conflicts')
    op.drop_index(op.f('ix_tidb_js_intelligence_conflicts_artifact_type'), table_name='tidb_js_intelligence_conflicts')
    op.drop_index(op.f('ix_tidb_js_intelligence_conflicts_correlation_id'), table_name='tidb_js_intelligence_conflicts')
    op.drop_index(op.f('ix_tidb_js_intelligence_conflicts_mission_id'), table_name='tidb_js_intelligence_conflicts')
    op.drop_index(op.f('ix_tidb_js_intelligence_conflicts_subject'), table_name='tidb_js_intelligence_conflicts')
    op.drop_table('tidb_js_intelligence_conflicts')
    op.drop_index(op.f('ix_tidb_js_intelligence_configuration_correlation_id'), table_name='tidb_js_intelligence_configuration')
    op.drop_index(op.f('ix_tidb_js_intelligence_configuration_execution_id'), table_name='tidb_js_intelligence_configuration')
    op.drop_index(op.f('ix_tidb_js_intelligence_configuration_kind'), table_name='tidb_js_intelligence_configuration')
    op.drop_index(op.f('ix_tidb_js_intelligence_configuration_mission_id'), table_name='tidb_js_intelligence_configuration')
    op.drop_index(op.f('ix_tidb_js_intelligence_configuration_target_key'), table_name='tidb_js_intelligence_configuration')
    op.drop_table('tidb_js_intelligence_configuration')
    op.drop_index(op.f('ix_tidb_js_intelligence_changes_artifact_type'), table_name='tidb_js_intelligence_changes')
    op.drop_index(op.f('ix_tidb_js_intelligence_changes_change_type'), table_name='tidb_js_intelligence_changes')
    op.drop_index(op.f('ix_tidb_js_intelligence_changes_correlation_id'), table_name='tidb_js_intelligence_changes')
    op.drop_index(op.f('ix_tidb_js_intelligence_changes_mission_id'), table_name='tidb_js_intelligence_changes')
    op.drop_index(op.f('ix_tidb_js_intelligence_changes_subject'), table_name='tidb_js_intelligence_changes')
    op.drop_table('tidb_js_intelligence_changes')
    op.drop_index(op.f('ix_tidb_js_intelligence_auth_correlation_id'), table_name='tidb_js_intelligence_auth')
    op.drop_index(op.f('ix_tidb_js_intelligence_auth_execution_id'), table_name='tidb_js_intelligence_auth')
    op.drop_index(op.f('ix_tidb_js_intelligence_auth_kind'), table_name='tidb_js_intelligence_auth')
    op.drop_index(op.f('ix_tidb_js_intelligence_auth_mission_id'), table_name='tidb_js_intelligence_auth')
    op.drop_index(op.f('ix_tidb_js_intelligence_auth_target_key'), table_name='tidb_js_intelligence_auth')
    op.drop_table('tidb_js_intelligence_auth')
    op.drop_index(op.f('ix_tidb_js_assets_hash_url'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_asset_kind'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_content_hash'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_correlation_id'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_execution_id'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_mission_id'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_target_key'), table_name='tidb_js_intelligence_assets')
    op.drop_index(op.f('ix_tidb_js_intelligence_assets_tool_id'), table_name='tidb_js_intelligence_assets')
    op.drop_table('tidb_js_intelligence_assets')    # ### end Alembic commands ###
