# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0
#
# HunterX — AI-Assisted Vulnerability Hunter
# This module provides centralized legal attribution and metadata injection
# for all generated outputs, reports, and exports.

from datetime import datetime
from typing import Dict, Any, Optional

__all__ = [
    "AUTHOR",
    "COPYRIGHT",
    "COPYRIGHT_SHORT",
    "LICENSE_NAME",
    "REPOSITORY_URL",
    "get_copyright_text",
    "get_disclaimer",
    "get_markdown_header",
    "get_markdown_footer",
    "get_json_metadata",
    "get_html_footer",
    "get_text_footer",
    "get_xml_footer",
    "get_csv_header",
    "get_banner",
    "inject_json",
    "inject_markdown",
    "inject_html",
    "License",
]

AUTHOR = "Ahmed Awad (NullC0d3)"
COPYRIGHT = f"Copyright (c) 2026 {AUTHOR}"
COPYRIGHT_SHORT = f"(c) 2026 {AUTHOR}"
LICENSE_NAME = "Apache License 2.0"
LICENSE_IDENTIFIER = "Apache-2.0"
LICENSE_URL = "https://www.apache.org/licenses/LICENSE-2.0"
REPOSITORY_URL = "https://github.com/nullc0d30/HunterX"

_DISCLAIMER_TEXT = (
    "DISCLAIMER: This framework is provided under the Apache License 2.0. It is "
    "intended exclusively for authorized security assessments, defensive security "
    "research, professional penetration testing, red team exercises, and educational "
    "use. The developer (Ahmed Awad / NullC0d3) is NOT responsible for any illegal "
    "use, unauthorized attacks, misuse, abuse, damage caused by third parties, or "
    "violation of local laws. Users are solely responsible for ensuring compliance "
    "with all applicable local, national, and international laws. Unauthorized use "
    "against systems without explicit permission is illegal and unethical."
)


class License:
    NAME = LICENSE_NAME
    IDENTIFIER = LICENSE_IDENTIFIER
    URL = LICENSE_URL
    YEAR = 2026
    AUTHOR = AUTHOR
    NOTICE = f"{COPYRIGHT}. Licensed under {LICENSE_NAME}."


def get_copyright_text() -> str:
    """Returns the full copyright line."""
    return f"{COPYRIGHT}. Licensed under {LICENSE_NAME}. See {LICENSE_URL}."


def get_disclaimer() -> str:
    """Returns the legal disclaimer."""
    return _DISCLAIMER_TEXT


def get_markdown_header(extra: Optional[str] = None) -> str:
    """Returns a markdown legal header block."""
    parts = [
        "---",
        f"Copyright (c) 2026 {AUTHOR}",
        f"SPDX-License-Identifier: {LICENSE_IDENTIFIER}",
    ]
    if extra:
        parts.append("")
        parts.append(extra)
    parts.append("---")
    parts.append("")
    return "\n".join(parts)


def get_markdown_footer() -> str:
    """Returns a markdown legal footer block."""
    lines = [
        "",
        "---",
        f"*{COPYRIGHT}*",
        f"*Licensed under {LICENSE_NAME}*",
        "",
        _DISCLAIMER_TEXT,
        "",
        f"*Report generated by [HunterX]({REPOSITORY_URL})*",
        "",
    ]
    return "\n".join(lines)


def get_json_metadata() -> Dict[str, Any]:
    """Returns a dict with legal metadata for JSON injection."""
    return {
        "_metadata": {
            "tool": "HunterX",
            "author": AUTHOR,
            "copyright": COPYRIGHT,
            "license": LICENSE_NAME,
            "repository": REPOSITORY_URL,
            "disclaimer": _DISCLAIMER_TEXT,
            "generated_at": datetime.utcnow().isoformat() + "Z",
        }
    }


def get_html_footer() -> str:
    """Returns an HTML legal footer block."""
    return f"""
    <hr>
    <footer style="text-align:center; color:#666; font-size:0.8em; margin-top:20px;">
        <p>{COPYRIGHT}. Licensed under <a href="{LICENSE_URL}" style="color:#4a9eff;">{LICENSE_NAME}</a>.</p>
        <p>{_DISCLAIMER_TEXT}</p>
        <p>Generated by <a href="{REPOSITORY_URL}" style="color:#4a9eff;">HunterX</a></p>
    </footer>
"""


def get_text_footer() -> str:
    """Returns a plain-text legal footer."""
    sep = "=" * 72
    return f"""
{sep}
{COPYRIGHT} | Licensed under {LICENSE_NAME}
{sep}
{_DISCLAIMER_TEXT}
{sep}
"""


def get_xml_footer() -> str:
    """Returns an XML comment footer with legal info."""
    return f"<!-- {COPYRIGHT}. Licensed under {LICENSE_NAME}. -->"


def get_csv_header() -> str:
    """Returns CSV comment lines with legal info (prepended to CSV output)."""
    return f"# {COPYRIGHT}. Licensed under {LICENSE_NAME}.\n#\n# {_DISCLAIMER_TEXT}\n#\n#"


def get_banner() -> str:
    """Returns the CLI banner string with copyright."""
    return (
        "HunterX v4.0.1 — AI-Assisted Vulnerability Hunter\n"
        f"{COPYRIGHT}. Licensed under {LICENSE_NAME}.\n"
        "Authorized security assessments only. Use responsibly."
    )


def inject_json(data: Dict) -> Dict:
    """Injects legal metadata into a JSON-serializable dict."""
    result = dict(data)
    meta = get_json_metadata()
    meta["_metadata"]["generated_at"] = datetime.utcnow().isoformat() + "Z"
    result["_metadata"] = meta["_metadata"]
    return result


def inject_markdown(content: str, header: bool = True, footer: bool = True) -> str:
    """Wraps markdown content with legal header/footer."""
    result = content
    if header:
        result = get_markdown_header() + "\n" + result
    if footer:
        result = result.rstrip("\n") + "\n" + get_markdown_footer()
    return result


def inject_html(html_content: str) -> str:
    """Injects legal footer before closing body tag in HTML."""
    footer = get_html_footer()
    if "</body>" in html_content:
        return html_content.replace("</body>", footer + "\n</body>")
    return html_content + footer
