# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Domain exception hierarchy.

All errors raised by HunterX derive from :class:`HunterXError`. Subclasses are
grouped by concern so application and infrastructure layers can catch and map
them to API/CLI error responses consistently.
"""

from __future__ import annotations

from hunterx.domain.exceptions.adaptive_mission_planning import (
    ActionNotFoundError,
    AdaptiveMissionNotFoundError,
    AdaptiveMissionPlanningError,
    AdaptiveMissionStateError,
    AdaptivePlanNotFoundError,
    PolicyBlockedActionError,
)
from hunterx.domain.exceptions.base import HunterXError, HunterXErrorCode
from hunterx.domain.exceptions.config import (
    ConfigurationError,
    ProfileNotFoundError,
    ValidationConfigError,
)
from hunterx.domain.exceptions.domain import (
    DomainError,
    InvalidFindingError,
    InvalidMissionError,
    InvalidTargetError,
)
from hunterx.domain.exceptions.domain import (
    ValidationError as DomainValidationError,
)
from hunterx.domain.exceptions.factory import (
    CompatibilityError,
    DuplicatePackError,
    GeneratorNotFoundError,
    InvalidToolPackSpecError,
    PackagingError,
    PackGenerationError,
    PackValidationError,
    TemplateNotFoundError,
    TemplateRenderError,
    ToolFactoryError,
    ToolPackNotFoundError,
)
from hunterx.domain.exceptions.infrastructure import (
    CacheError,
    DuplicateRegistrationError,
    InfrastructureError,
    NotFoundError,
    PersistenceError,
    QueueError,
    RegistrationNotFoundError,
    SandboxError,
    SecretResolutionError,
)
from hunterx.domain.exceptions.infrastructure import (
    ConnectionError as InfrastructureConnectionError,
)
from hunterx.domain.exceptions.operation import (
    AuthenticationError,
    AuthorizationError,
    ExecutionError,
    MissionAlreadyRunningError,
    MissionNotFoundError,
    OperationError,
    PluginExecutionError,
    PluginLoadError,
    PluginNotFoundError,
    ReportRenderError,
    ScheduleConflictError,
    ToolCancellationError,
    ToolDependencyError,
    ToolExecutionError,
    ToolHealthError,
    ToolInstallationError,
    ToolLockError,
    ToolNotFoundError,
    ToolQueueError,
    ToolRegistrationError,
    ToolRetryableError,
    ToolSelectionError,
    ToolStateTransitionError,
    ToolTimeoutError,
)
from hunterx.domain.exceptions.orchestration import (
    ExecutionPlanNotFoundError,
    InvalidMissionStateError,
    MissionCancelledError,
    OffensiveMissionNotFoundError,
    OffensiveOrchestrationError,
    RateLimitExceededError,
    SafetyViolationError,
    ScopeViolationError,
    ToolSelectionUnavailableError,
)
from hunterx.domain.exceptions.planning import (
    CheckpointNotFoundError,
    InvalidMissionPlanError,
    InvalidMissionRequestError,
    InvalidStateTransitionError,
    MissionPlanningError,
    MissionPlanNotFoundError,
    MissionPlanValidationError,
    MissionProfileNotFoundError,
    MissionTemplateNotFoundError,
)

__all__ = [
    "HunterXError",
    "HunterXErrorCode",
    "ConfigurationError",
    "ProfileNotFoundError",
    "ValidationConfigError",
    "InfrastructureError",
    "PersistenceError",
    "NotFoundError",
    "DuplicateRegistrationError",
    "RegistrationNotFoundError",
    "CacheError",
    "QueueError",
    "InfrastructureConnectionError",
    "SecretResolutionError",
    "SandboxError",
    "DomainError",
    "InvalidTargetError",
    "InvalidFindingError",
    "InvalidMissionError",
    "DomainValidationError",
    "MissionPlanningError",
    "MissionProfileNotFoundError",
    "MissionTemplateNotFoundError",
    "InvalidMissionRequestError",
    "MissionPlanNotFoundError",
    "InvalidMissionPlanError",
    "MissionPlanValidationError",
    "CheckpointNotFoundError",
    "InvalidStateTransitionError",
    "ToolFactoryError",
    "InvalidToolPackSpecError",
    "PackGenerationError",
    "ToolPackNotFoundError",
    "DuplicatePackError",
    "PackValidationError",
    "GeneratorNotFoundError",
    "TemplateNotFoundError",
    "TemplateRenderError",
    "PackagingError",
    "CompatibilityError",
    "OperationError",
    "ExecutionError",
    "MissionNotFoundError",
    "MissionAlreadyRunningError",
    "PluginLoadError",
    "PluginExecutionError",
    "PluginNotFoundError",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ToolRegistrationError",
    "ToolStateTransitionError",
    "ToolSelectionError",
    "ToolTimeoutError",
    "ToolCancellationError",
    "ToolRetryableError",
    "ToolInstallationError",
    "ToolDependencyError",
    "ToolHealthError",
    "ToolLockError",
    "ToolQueueError",
    "ScheduleConflictError",
    "ReportRenderError",
    "AuthorizationError",
    "AuthenticationError",
    "OffensiveOrchestrationError",
    "OffensiveMissionNotFoundError",
    "ExecutionPlanNotFoundError",
    "InvalidMissionStateError",
    "ScopeViolationError",
    "SafetyViolationError",
    "ToolSelectionUnavailableError",
    "RateLimitExceededError",
    "MissionCancelledError",
    "ActionNotFoundError",
    "AdaptiveMissionNotFoundError",
    "AdaptiveMissionPlanningError",
    "AdaptiveMissionStateError",
    "AdaptivePlanNotFoundError",
    "PolicyBlockedActionError",
]
