# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Integration templates for the Tool Integration Factory.

The factory renders every generated pack from an integration template. A
built-in "standard" template ships with the factory; operators may register
overrides by ``template_id`` so packs stay identical in layout while allowing
org-specific boilerplate.
"""

from __future__ import annotations

from hunterx.domain.exceptions import TemplateNotFoundError
from hunterx.domain.ports.tool_factory import PackTemplateRepository
from hunterx.domain.tool_factory import IntegrationTemplate
from hunterx.tools.factory.layout import PACK_STRUCTURE_VERSION

# -- built-in template file contents -----------------------------------------

_ADAPTER_INIT = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Adapter package for the ${display_name} integration pack."""

from ${vendor}.${pack_id}.adapters.adapter import ${adapter_class_name}, DESCRIPTOR

__all__ = ["${adapter_class_name}", "DESCRIPTOR"]
'''

_ADAPTER = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Tool adapter for ${display_name}.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

from hunterx.domain.execution import ExecutionContext
from hunterx.domain.tools import ToolDescriptor
from hunterx.tools.sdk import OutputCollector, ToolAdapter

DESCRIPTOR = ToolDescriptor(
    name="${pack_id}",
    version="${version}",
    description="${description}",
    entrypoint="${entrypoint}",
    targets=(${targets_list}),
    capabilities=(${capabilities_list}),
    parameters={},
    permissions=(${permissions_list}),
)


class ${adapter_class_name}(ToolAdapter):
    """Executes ${tool_name} through the HunterX Tool Integration SDK."""

    descriptor = DESCRIPTOR

    def run(self, context: ExecutionContext, collector: OutputCollector) -> None:
        """Invoke ${tool_name} for ``context.target`` and collect output.

        Invoke the ${tool_name} CLI, attach raw output through ``collector``
        and set a JSON payload shaped like
        ``{"findings": [{"title", "severity", "target", "description",
        "risk_score", "metadata"}]}``.
        """
        # TODO: implement ${tool_name} invocation and output collection.
        collector.set_exit_code(0)
'''

_PARSING_INIT = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Parsing package for the ${display_name} integration pack."""

from ${vendor}.${pack_id}.parsing.normalizer import ${normalizer_class_name}
from ${vendor}.${pack_id}.parsing.parser import ${parser_class_name}

__all__ = ["${parser_class_name}", "${normalizer_class_name}"]
'''

_PARSER = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Parser for ${display_name} ${parser_strategy} output.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

import json
from typing import Any


class ${parser_class_name}:
    """Parses raw ${tool_name} output into structured finding records."""

    strategy = "${parser_strategy}"

    def parse(self, raw: str) -> list[dict[str, Any]]:
        """Parse ``raw`` output into a list of finding records."""
        if self.strategy == "json":
            return self._parse_json(raw)
        if self.strategy == "xml":
            return self._parse_xml(raw)
        if self.strategy == "csv":
            return self._parse_csv(raw)
        return self._parse_text(raw)

    def _parse_json(self, raw: str) -> list[dict[str, Any]]:
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            return []
        findings = payload.get("findings", []) if isinstance(payload, dict) else payload
        return [record for record in findings if isinstance(record, dict)]

    def _parse_xml(self, raw: str) -> list[dict[str, Any]]:
        # TODO: implement XML parsing for ${tool_name}.
        return []

    def _parse_csv(self, raw: str) -> list[dict[str, Any]]:
        # TODO: implement CSV parsing for ${tool_name}.
        return []

    def _parse_text(self, raw: str) -> list[dict[str, Any]]:
        # TODO: implement ${parser_strategy} parsing for ${tool_name}.
        return []
'''

_NORMALIZER = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Normalizer for ${display_name} findings.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

from typing import Any

from hunterx.plugins.sdk.results import FindingResult


class ${normalizer_class_name}:
    """Normalizes ${tool_name} records into :class:`FindingResult`."""

    def normalize(self, records: list[dict[str, Any]], *, target: str) -> list[FindingResult]:
        """Convert parsed records into normalized findings."""
        return [self._normalize(record, target=target) for record in records]

    def _normalize(self, record: dict[str, Any], *, target: str) -> FindingResult:
        return FindingResult(
            title=str(record.get("title", "Finding")),
            severity=str(record.get("severity", "info")).lower(),
            target=str(record.get("target", target)),
            description=str(record.get("description", "")),
            risk_score=self._risk_score(record),
            metadata=dict(record.get("metadata", {})),
        )

    @staticmethod
    def _risk_score(record: dict[str, Any]) -> float | None:
        score = record.get("risk_score")
        if score is None:
            return None
        try:
            return float(score)
        except (TypeError, ValueError):
            return None
'''

_RUNTIME_INIT = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Runtime package for the ${display_name} integration pack."""
'''

_ERRORS = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Typed errors for the ${display_name} integration pack.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations


class ${adapter_class_name}Error(Exception):
    """Base error for the ${display_name} integration pack."""


class ${adapter_class_name}ExecutionError(${adapter_class_name}Error):
    """Raised when ${tool_name} fails to execute."""


class ${adapter_class_name}ParseError(${adapter_class_name}Error):
    """Raised when ${tool_name} output cannot be parsed."""


class ${adapter_class_name}NormalizationError(${adapter_class_name}Error):
    """Raised when ${tool_name} output cannot be normalized."""
'''

_LOGGING = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Logging for the ${display_name} integration pack.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

import logging

logger = logging.getLogger("hunterx.packs.${vendor}.${pack_id}")


def get_logger() -> logging.Logger:
    """Return the pack's module logger."""
    return logger
'''

_TELEMETRY = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Telemetry for the ${display_name} integration pack.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

import time


class Telemetry:
    """Measures execution duration for pack runs."""

    def __init__(self) -> None:
        self._started: float | None = None

    def start(self) -> Telemetry:
        """Start the timer and return self."""
        self._started = time.monotonic()
        return self

    def elapsed_ms(self) -> int:
        """Return elapsed milliseconds since :meth:`start`."""
        if self._started is None:
            return 0
        return int((time.monotonic() - self._started) * 1000)
'''

_TESTS_INIT = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Tests package for the ${display_name} integration pack."""
'''

_TEST_UNIT = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Unit tests for the ${display_name} integration pack.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

import pytest

from ${vendor}.${pack_id}.adapters.adapter import DESCRIPTOR, ${adapter_class_name}
from ${vendor}.${pack_id}.parsing.normalizer import ${normalizer_class_name}
from ${vendor}.${pack_id}.parsing.parser import ${parser_class_name}


def test_descriptor_is_defined() -> None:
    assert DESCRIPTOR.name == "${pack_id}"


def test_adapter_version_matches_pack() -> None:
    assert ${adapter_class_name}().descriptor.version == "${version}"


def test_parser_handles_empty_output() -> None:
    assert ${parser_class_name}().parse("") == []


def test_normalizer_produces_findings() -> None:
    records = [{"title": "Sample", "severity": "high", "target": "t.example", "risk_score": 8.0}]
    findings = ${normalizer_class_name}().normalize(records, target="t.example")
    assert findings[0].title == "Sample"
    assert findings[0].risk_score == pytest.approx(8.0)
'''

_TEST_INTEGRATION = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Integration tests for the ${display_name} integration pack.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

from ${vendor}.${pack_id}.adapters.adapter import ${adapter_class_name}


def test_descriptor_contract_matches_manifest() -> None:
    descriptor = ${adapter_class_name}().descriptor
    assert descriptor.entrypoint.endswith(":${adapter_class_name}")


def test_descriptor_declares_capabilities() -> None:
    descriptor = ${adapter_class_name}().descriptor
    assert isinstance(descriptor.capabilities, tuple)
'''

_TEST_PERFORMANCE = '''# ${copyright}
# SPDX-License-Identifier: Apache-2.0

"""Performance smoke tests for the ${display_name} integration pack.

Generated by the HunterX Tool Integration Factory v${generator_version}.
"""

from __future__ import annotations

import time

from ${vendor}.${pack_id}.parsing.parser import ${parser_class_name}


def test_parser_smoke_under_time_budget() -> None:
    parser = ${parser_class_name}()
    started = time.monotonic()
    parser.parse("")
    assert time.monotonic() - started < 1.0
'''

_PYPROJECT = '''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "hunterx-tool-pack-${vendor}-${pack_id}"
version = "${version}"
description = "${description}"
readme = "README.md"
license = {text = "${license}"}
authors = [{name = "${author}"}]
requires-python = ">=3.11"
dependencies = ["hunterx>=${hunterx_version}"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-m 'not tools'"
'''

_MANIFEST = '''include pack.yaml
include pyproject.toml
recursive-include metadata *.yaml
recursive-include knowledge *.yaml
recursive-include install *.yaml
recursive-include rules *.yaml
recursive-include schemas *.json
recursive-include adapters *.py
recursive-include parsing *.py
recursive-include mapping *.yaml
recursive-include runtime *.py
recursive-include validation *.yaml
recursive-include tests *.py
recursive-include docs *.md
'''

_README = '''# ${display_name}

${description}

| Field | Value |
| --- | --- |
| Pack | `${pack_id}` |
| Vendor | `${vendor}` |
| Version | `${version}` |
| License | `${license}` |
| Entry point | `` `${entrypoint}` `` |
| Capabilities | `${capabilities_joined}` |

See `docs/developer.md` for the developer guide and `docs/integration.md`
for wiring the pack into HunterX.
'''

#: Built-in template files: relative path -> template content.
_BUILTIN_FILES: dict[str, str] = {
    "adapters/__init__.py": _ADAPTER_INIT,
    "adapters/adapter.py": _ADAPTER,
    "parsing/__init__.py": _PARSING_INIT,
    "parsing/parser.py": _PARSER,
    "parsing/normalizer.py": _NORMALIZER,
    "runtime/__init__.py": _RUNTIME_INIT,
    "runtime/errors.py": _ERRORS,
    "runtime/logging.py": _LOGGING,
    "runtime/telemetry.py": _TELEMETRY,
    "tests/__init__.py": _TESTS_INIT,
    "tests/test_unit.py": _TEST_UNIT,
    "tests/test_integration.py": _TEST_INTEGRATION,
    "tests/test_performance.py": _TEST_PERFORMANCE,
    "pyproject.toml": _PYPROJECT,
    "README.md": _README,
    "MANIFEST.in": _MANIFEST,
}

#: Public view of the built-in template file set (path -> template content).
BUILTIN_FILES: dict[str, str] = dict(_BUILTIN_FILES)

#: The standard template shipped with the factory.
BUILTIN_TEMPLATE = IntegrationTemplate(
    template_id="standard",
    name="Standard Integration Template",
    description="Default HunterX Tool Integration Pack layout and boilerplate.",
    version="1.0.0",
    structure_version=PACK_STRUCTURE_VERSION,
    author="HunterX Team",
    files=dict(_BUILTIN_FILES),
    builtin=True,
)


class PackTemplateStore:
    """Holds integration templates and resolves the effective file set.

    A :class:`PackTemplateRepository` may back the store; registered overrides
    take precedence over the built-in standard template.
    """

    def __init__(self, repository: PackTemplateRepository | None = None) -> None:
        self._repository = repository
        self._overrides: dict[str, IntegrationTemplate] = {}

    def register(self, template: IntegrationTemplate) -> IntegrationTemplate:
        """Register a template override (persisting it when backed)."""
        self._overrides[template.template_id] = template
        if self._repository is not None:
            self._repository.save(template)
        return template

    def get(self, template_id: str) -> IntegrationTemplate:
        """Return a template, raising :class:`TemplateNotFoundError`."""
        if template_id in self._overrides:
            return self._overrides[template_id]
        if template_id == "standard" or template_id is None:
            return BUILTIN_TEMPLATE
        if self._repository is not None:
            template = self._repository.get(template_id)
            if template is not None:
                self._overrides[template_id] = template
                return template
        raise TemplateNotFoundError(template_id)

    def resolve(self, template_id: str | None = None) -> dict[str, str]:
        """Return the effective ``path -> template content`` file set.

        The built-in standard template is the base; a chosen template's files
        override it per path.
        """
        files: dict[str, str] = dict(BUILTIN_TEMPLATE.files)
        if template_id is not None and template_id != "standard":
            template = self.get(template_id)
            files.update(template.files)
        return files

    def list(self) -> list[IntegrationTemplate]:
        """Return every known template (built-in plus registered overrides)."""
        templates = [BUILTIN_TEMPLATE]
        if self._repository is not None:
            templates.extend(self._repository.list(limit=10_000))
        templates.extend(self._overrides.values())
        seen: dict[str, IntegrationTemplate] = {}
        for template in templates:
            seen[template.template_id] = template
        return list(seen.values())
