# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Web / crawling / content / parameter / API / JS arsenal tool specs."""

from __future__ import annotations

from hunterx.domain.tool_mastery import ToolSupportLevel
from hunterx.tools.mastery.specs import ToolSpec

#: HTTP probing, technology detection, WAF detection, TLS analysis.
WEB_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="httpx",
        display_name="HTTPx",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/httpx",
        license="MIT",
        category="web",
        subcategory="probe",
        description="Fast and multi-purpose HTTP toolkit for probing live hosts and metadata.",
        capabilities=("http-probing", "technology-detection", "http-configuration-analysis"),
        version="1.6.5",
        language="go",
        tags=("probe", "http", "tech"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("url", "host", "ip"),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="httpx-jsonl",
        normalizer_id="tech-normalizer",
        adapter_id="hunterx.tools.tech.httpx:HttpxAdapter",
        alternatives=("whatweb", "curl"),
        successors=("katana", "nuclei"),
        safety_class="read-only",
        operational_knowledge=("Probing is low-impact; follow redirects carefully.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="whatweb",
        display_name="WhatWeb",
        vendor="urbanadventurer",
        project_url="https://github.com/urbanadventurer/WhatWeb",
        license="GPL-2.0",
        category="web",
        subcategory="tech",
        description="Next-generation web scanner that identifies website technologies.",
        capabilities=("technology-detection", "web-server-analysis"),
        version="0.5.5",
        language="ruby",
        tags=("fingerprint", "tech", "web"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="whatweb-json",
        normalizer_id="tech-normalizer",
        adapter_id="hunterx.tools.tech.whatweb:WhatWebAdapter",
        alternatives=("httpx", "wappalyzer"),
        successors=("nuclei", "katana"),
        safety_class="read-only",
        operational_knowledge=("Aggressive plugins send more requests; use passive plugins for low impact.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="wafw00f",
        display_name="Wafw00f",
        vendor="EnableSecurity",
        project_url="https://github.com/EnableSecurity/wafw00f",
        license="BSD-3-Clause",
        category="web",
        subcategory="waf",
        description="Identifies and fingerprints Web Application Firewall products.",
        capabilities=("waf-detection",),
        version="2.2.0",
        language="python",
        tags=("waf", "fingerprint"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("nuclei-waf-templates",),
        successors=("nuclei",),
        safety_class="read-only",
        operational_knowledge=("Run before active testing to tune payloads and rate limits.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="nikto",
        display_name="Nikto",
        vendor="sullo",
        project_url="https://github.com/sullo/nikto",
        license="GPL-2.0",
        category="web",
        subcategory="scan",
        description="Web server scanner that checks for dangerous files, misconfigurations and outdated software.",
        capabilities=("web-server-analysis", "http-configuration-analysis"),
        version="2.5.0",
        language="perl",
        tags=("scanner", "web", "misconfig"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "xml", "text"),
        structured_formats=("json", "xml"),
        alternatives=("nuclei", "zap"),
        successors=("nuclei",),
        safety_class="active",
        operational_knowledge=("Noisy; many checks are heuristic. Validate everything.",),
        false_positives=("Heuristic findings frequently require manual verification.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="testssl.sh",
        display_name="testssl.sh",
        vendor="drwetter",
        project_url="https://github.com/drwetter/testssl.sh",
        license="GPL-2.0",
        category="web",
        subcategory="tls",
        description="TLS/SSL configuration analysis: protocols, ciphers, vulnerabilities, certificates.",
        capabilities=("tls-analysis", "http-configuration-analysis"),
        version="3.2.0",
        language="shell",
        tags=("tls", "ssl", "analysis"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "url"),
        protocols=("tls",),
        output_formats=("json", "csv", "html"),
        structured_formats=("json",),
        safety_class="read-only",
        operational_knowledge=("Deep TLS analysis; long-running scans on large cipher suites.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="sslscan",
        display_name="SSLScan",
        vendor="rbsec",
        project_url="https://github.com/rbsec/sslscan",
        license="GPL-3.0",
        category="web",
        subcategory="tls",
        description="Fast TLS/SSL scanner for cipher suite and certificate enumeration.",
        capabilities=("tls-analysis",),
        version="2.1.3",
        language="c",
        tags=("tls", "ssl", "ciphers"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip"),
        protocols=("tls",),
        output_formats=("text", "xml"),
        structured_formats=("xml",),
        alternatives=("testssl.sh",),
        successors=("testssl.sh",),
        safety_class="read-only",
        operational_knowledge=("Complementary to testssl.sh for rapid cipher enumeration.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: Crawling / URL discovery tools.
CRAWL_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="katana",
        display_name="Katana",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/katana",
        license="MIT",
        category="crawl",
        subcategory="crawler",
        description="Next-generation crawling and spidering for endpoint and URL discovery.",
        capabilities=("crawling", "url-discovery", "endpoint-discovery"),
        version="1.1.2",
        language="go",
        tags=("crawler", "url", "endpoint"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="katana-jsonl",
        normalizer_id="url-normalizer",
        adapter_id="hunterx.tools.web.katana:KatanaAdapter",
        alternatives=("gospider", "hakrawler"),
        successors=("arjun", "linkfinder", "nuclei"),
        safety_class="active",
        operational_knowledge=("Live discovery is an active evidence class distinct from historical.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="gospider",
        display_name="Gospider",
        vendor="jaeles-project",
        project_url="https://github.com/jaeles-project/gospider",
        license="MIT",
        category="crawl",
        subcategory="crawler",
        description="Fast web spider that finds URLs, links, forms and JS files.",
        capabilities=("crawling", "url-discovery", "javascript-discovery"),
        version="1.1.6",
        language="go",
        tags=("crawler", "spider"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("katana", "hakrawler"),
        successors=("linkfinder", "arjun"),
        safety_class="active",
        operational_knowledge=("Follows sitemap and robots; noisy on large sites.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="hakrawler",
        display_name="Hakrawler",
        vendor="hakluke",
        project_url="https://github.com/hakluke/hakrawler",
        license="GPL-3.0",
        category="crawl",
        subcategory="crawler",
        description="Web crawler designed for fast, easy URL discovery.",
        capabilities=("crawling", "url-discovery"),
        version="2.1.0",
        language="go",
        tags=("crawler", "url"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("text",),
        alternatives=("katana", "gospider"),
        successors=("linkfinder",),
        safety_class="active",
        operational_knowledge=("Simple crawler; pairs well with link extraction tools.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="gau",
        display_name="GAU",
        vendor="lc",
        project_url="https://github.com/lc/gau",
        license="MIT",
        category="crawl",
        subcategory="historical",
        description="GetAllURLs: fetch known URLs from AlienVault OTX, Wayback and Common Crawl.",
        capabilities=("historical-url-discovery", "url-discovery"),
        version="2.0.9",
        language="go",
        tags=("historical", "url", "osint"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain",),
        protocols=("https",),
        output_formats=("text",),
        alternatives=("waybackurls", "gauplus"),
        successors=("httpx", "katana"),
        safety_class="passive",
        operational_knowledge=("Historical discovery is a distinct evidence class from live crawling.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="waybackurls",
        display_name="Waybackurls",
        vendor="tomnomnom",
        project_url="https://github.com/tomnomnom/waybackurls",
        license="MIT",
        category="crawl",
        subcategory="historical",
        description="Fetch all URLs the Wayback Machine knows about for a domain.",
        capabilities=("historical-url-discovery",),
        version="0.1.0",
        language="go",
        tags=("historical", "wayback", "url"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain",),
        protocols=("https",),
        output_formats=("text",),
        alternatives=("gau", "gauplus"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("Wayback data can be years old; deduplicate and re-probe.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="urlfinder",
        display_name="URLFinder",
        vendor="codingo",
        project_url="https://github.com/codingo/URLFinder",
        license="MIT",
        category="crawl",
        subcategory="historical",
        description="Extract URLs from a site and its Wayback/CDX data.",
        capabilities=("historical-url-discovery", "url-discovery"),
        version="1.0.2",
        language="go",
        tags=("url", "wayback"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain", "url"),
        protocols=("https",),
        output_formats=("text", "json"),
        structured_formats=("json",),
        alternatives=("gau", "waybackurls"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("Combines live extraction with CDX historical lookups.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="crobat",
        display_name="Crobat",
        vendor="Cgboal",
        project_url="https://github.com/Cgboal/SonarSearch",
        license="GPL-3.0",
        category="recon",
        subcategory="osint",
        description="Query Rapid7 Project Sonar DNS dataset for subdomains.",
        capabilities=("subdomain-enumeration", "historical-url-discovery"),
        version="1.1.0",
        language="rust",
        tags=("osint", "subdomain", "sonar"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain",),
        output_formats=("text",),
        alternatives=("subfinder", "amass"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("Sonar dataset snapshot may lag live state.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="gauplus",
        display_name="gauplus",
        vendor="bp0lr",
        project_url="https://github.com/bp0lr/gauplus",
        license="MIT",
        category="crawl",
        subcategory="historical",
        description="Community-maintained fork of GAU with additional sources and options.",
        capabilities=("historical-url-discovery", "url-discovery"),
        version="1.0.3",
        language="go",
        tags=("historical", "url", "osint"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain",),
        protocols=("https",),
        output_formats=("text", "json"),
        structured_formats=("json",),
        alternatives=("gau", "waybackurls"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("Maintained fork of GAU; prefer when GAU is stale.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: Content discovery / fuzzing tools.
CONTENT_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="ffuf",
        display_name="FFUF",
        vendor="ffuf",
        project_url="https://github.com/ffuf/ffuf",
        license="MIT",
        category="content",
        subcategory="fuzz",
        description="Fast web fuzzer for directory, file, vhost and parameter fuzzing.",
        capabilities=("content-discovery", "directory-enumeration", "file-enumeration", "vhost-enumeration"),
        version="2.1.0",
        language="go",
        tags=("fuzz", "directory", "vhost"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="ffuf-json",
        normalizer_id="url-normalizer",
        adapter_id="hunterx.tools.content.ffuf:FfufAdapter",
        alternatives=("gobuster", "feroxbuster", "dirsearch"),
        successors=("nuclei",),
        safety_class="active",
        rate_limits="respect rate limits; use matchers and filters",
        resource_requirements="concurrency and wordlists drive resource use",
        operational_knowledge=("Wildcard responses and baseline responses must be filtered to avoid false positives.",),
        false_positives=("Wildcard web servers generate false positives unless filtered.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="feroxbuster",
        display_name="Feroxbuster",
        vendor="epi052",
        project_url="https://github.com/epi052/feroxbuster",
        license="MIT",
        category="content",
        subcategory="fuzz",
        description="Fast, recursive content discovery tool with Rust.",
        capabilities=("content-discovery", "directory-enumeration", "file-enumeration"),
        version="2.11.0",
        language="rust",
        tags=("fuzz", "directory", "recursive"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("ffuf", "gobuster", "dirsearch"),
        successors=("nuclei",),
        safety_class="active",
        operational_knowledge=("Recursive crawling increases request volume; scope carefully.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="gobuster",
        display_name="Gobuster",
        vendor="OJ",
        project_url="https://github.com/OJ/gobuster",
        license="Apache-2.0",
        category="content",
        subcategory="fuzz",
        description="Directory/file/vhost/DNS busting with Go.",
        capabilities=("directory-enumeration", "file-enumeration", "vhost-enumeration"),
        version="3.6.0",
        language="go",
        tags=("fuzz", "directory", "vhost"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url", "domain"),
        protocols=("http", "https", "dns"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("ffuf", "feroxbuster", "dirsearch"),
        successors=("nuclei",),
        safety_class="active",
        operational_knowledge=("Multipurpose: dir, dns, vhost and s3 modes.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="dirsearch",
        display_name="Dirsearch",
        vendor="maurosoria",
        project_url="https://github.com/maurosoria/dirsearch",
        license="GPL-2.0",
        category="content",
        subcategory="fuzz",
        description="Advanced web path discovery tool written in Python.",
        capabilities=("directory-enumeration", "file-enumeration"),
        version="0.4.3",
        language="python",
        tags=("fuzz", "directory"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("ffuf", "gobuster", "feroxbuster"),
        successors=("nuclei",),
        safety_class="active",
        operational_knowledge=("Mature Python codebase; easy to customize with extensions.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
)


#: Parameter discovery tools.
PARAMETER_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="arjun",
        display_name="Arjun",
        vendor="s0md3v",
        project_url="https://github.com/s0md3v/Arjun",
        license="GPL-3.0",
        category="parameter",
        subcategory="discovery",
        description="HTTP parameter discovery suite that finds hidden HTTP parameters.",
        capabilities=("parameter-discovery", "get-parameter-discovery", "post-parameter-discovery"),
        version="2.2.6",
        language="python",
        tags=("parameter", "hidden"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("paramspider",),
        successors=("sqlmap", "dalfox", "nuclei"),
        safety_class="active",
        operational_knowledge=("Hidden parameters expand attack surface for injection testing.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="paramspider",
        display_name="ParamSpider",
        vendor="devanshbatham",
        project_url="https://github.com/devanshbatham/ParamSpider",
        license="MIT",
        category="parameter",
        subcategory="discovery",
        description="Finds parameters from web archives for a given domain.",
        capabilities=("parameter-discovery", "historical-parameter-discovery"),
        version="1.0.0",
        language="python",
        tags=("parameter", "archive"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain",),
        protocols=("https",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("arjun",),
        successors=("sqlmap", "dalfox"),
        safety_class="passive",
        operational_knowledge=("Archive-derived parameters are historical evidence.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
)


#: API discovery / testing tools.
API_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="kiterunner",
        display_name="Kiterunner",
        vendor="assetnote",
        project_url="https://github.com/assetnote/kiterunner",
        license="Apache-2.0",
        category="api",
        subcategory="discovery",
        description="Content discovery and route enumeration for API and web endpoints.",
        capabilities=("api-discovery", "content-discovery"),
        version="1.0.0",
        language="go",
        tags=("api", "route", "discovery"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        successors=("graphqlmap", "inql"),
        safety_class="active",
        operational_knowledge=("Routes are candidate endpoints; validate each one.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="graphqlmap",
        display_name="GraphQLmap",
        vendor="swisskyrepo",
        project_url="https://github.com/swisskyrepo/GraphQLmap",
        license="MIT",
        category="api",
        subcategory="graphql",
        description="GraphQL exploitation framework for querying and fuzzing.",
        capabilities=("graphql-analysis", "graphql-introspection", "query-analysis"),
        version="1.1.0",
        language="python",
        tags=("graphql", "api"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("inql",),
        successors=("jwt-tool",),
        safety_class="active",
        operational_knowledge=("Introspection must be explicitly permitted by scope.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="inql",
        display_name="InQL",
        vendor="doyensec",
        project_url="https://github.com/doyensec/inql",
        license="GPL-3.0",
        category="api",
        subcategory="graphql",
        description="GraphQL security testing: schema introspection and query analysis.",
        capabilities=("graphql-analysis", "graphql-introspection", "query-analysis"),
        version="6.0.0",
        language="python",
        tags=("graphql", "api"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("graphqlmap",),
        successors=("jwt-tool",),
        safety_class="active",
        operational_knowledge=("Burp integration available; scope introspection carefully.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="jwt-tool",
        display_name="jwt_tool",
        vendor="ticarpi",
        project_url="https://github.com/ticarpi/jwt_tool",
        license="GPL-3.0",
        category="api",
        subcategory="auth",
        description="JWT manipulation, forgery and vulnerability testing toolkit.",
        capabilities=("jwt-analysis", "authentication-analysis"),
        version="2.2.6",
        language="python",
        tags=("jwt", "auth", "token"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("token", "url"),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        successors=("interactsh",),
        safety_class="active",
        operational_knowledge=("Algorithm confusion and weak-signature tests are active.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="openapi-parser",
        display_name="OpenAPI / Swagger parser",
        vendor="HunterX",
        project_url="",
        license="Apache-2.0",
        category="api",
        subcategory="schema",
        description="In-process OpenAPI/Swagger document parser for schema and endpoint intelligence.",
        capabilities=("openapi-analysis", "api-discovery", "api-parameter-analysis"),
        version="1.0.0",
        language="python",
        tags=("openapi", "swagger", "schema"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json",),
        structured_formats=("json",),
        parser_id="openapi-parser",
        normalizer_id="url-normalizer",
        safety_class="passive",
        operational_knowledge=("Parses schemas only; never executes discovered operations.",),
        execution_type="pip",
        container_available=False,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="postman-parser",
        display_name="Postman collection parser",
        vendor="HunterX",
        project_url="",
        license="Apache-2.0",
        category="api",
        subcategory="schema",
        description="In-process Postman collection parser for endpoint and parameter intelligence.",
        capabilities=("api-discovery", "api-parameter-analysis"),
        version="1.0.0",
        language="python",
        tags=("postman", "collection", "schema"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json",),
        structured_formats=("json",),
        parser_id="postman-parser",
        normalizer_id="url-normalizer",
        safety_class="passive",
        operational_knowledge=("Parses collections only; never executes requests.",),
        execution_type="pip",
        container_available=False,
        binary_available=False,
    ),
)


#: JavaScript intelligence tools.
JAVASCRIPT_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="linkfinder",
        display_name="LinkFinder",
        vendor="GerbenJavado",
        project_url="https://github.com/GerbenJavado/LinkFinder",
        license="GPL-3.0",
        category="javascript",
        subcategory="endpoints",
        description="Discovers endpoints and URLs in JavaScript files.",
        capabilities=("javascript-analysis", "endpoint-extraction"),
        version="1.0.0",
        language="python",
        tags=("js", "endpoint", "url"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("xnlinkfinder", "jsluice"),
        successors=("secretfinder", "arjun"),
        safety_class="passive",
        operational_knowledge=("Minified JS yields noisy candidates; deduplicate.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="secretfinder",
        display_name="SecretFinder",
        vendor="m4ll0k",
        project_url="https://github.com/m4ll0k/SecretFinder",
        license="MIT",
        category="javascript",
        subcategory="secrets",
        description="Finds sensitive data (API keys, tokens) inside JavaScript files.",
        capabilities=("javascript-analysis", "secret-indicator-discovery"),
        version="1.0.0",
        language="python",
        tags=("js", "secrets", "tokens"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("jsluice",),
        successors=("trufflehog", "detect-secrets"),
        safety_class="passive",
        operational_knowledge=("Raw credentials must never be stored unredacted.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="xnlinkfinder",
        display_name="xnLinkFinder",
        vendor="xnl-h4ck3r",
        project_url="https://github.com/xnl-h4ck3r/xnLinkFinder",
        license="GPL-3.0",
        category="javascript",
        subcategory="endpoints",
        description="Discover endpoints and files in JavaScript files, wordlists and web pages.",
        capabilities=("javascript-analysis", "endpoint-extraction", "parameter-discovery"),
        version="1.0.0",
        language="python",
        tags=("js", "endpoint", "url"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("linkfinder", "jsluice"),
        successors=("secretfinder",),
        safety_class="passive",
        operational_knowledge=("Handles minified, obfuscated and wordlist inputs.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="jsluice",
        display_name="JSluice",
        vendor="bishopfox",
        project_url="https://github.com/BishopFox/jsluice",
        license="MIT",
        category="javascript",
        subcategory="analysis",
        description="A Golang tool for analyzing JavaScript and extracting URLs, secrets and parameters.",
        capabilities=("javascript-analysis", "endpoint-extraction", "secret-indicator-discovery", "source-map-discovery"),
        version="0.1.0",
        language="go",
        tags=("js", "analysis", "secrets"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("linkfinder", "xnlinkfinder"),
        successors=("secretfinder",),
        safety_class="passive",
        operational_knowledge=("Understands minified JS, bundles, chunks and source maps.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)
