# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Enterprise / AD, SNMP, cloud, container and composition arsenal tool specs."""

from __future__ import annotations

from hunterx.domain.tool_mastery import ToolSupportLevel
from hunterx.tools.mastery.specs import ToolSpec

#: Enterprise network / Active Directory tools (internal network capability).
ENTERPRISE_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="netexec",
        display_name="NetExec",
        vendor="Pennyw0rth",
        project_url="https://github.com/Pennyw0rth/NetExec",
        license="BSD-2-Clause",
        category="enterprise",
        subcategory="ad",
        description="Network service exploitation and enumeration for SMB, LDAP, WinRM and more.",
        capabilities=("smb-enumeration", "windows-enumeration", "ldap-enumeration", "domain-enumeration"),
        version="1.1.0",
        language="python",
        tags=("smb", "ldap", "ad", "winrm"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "network"),
        protocols=("smb", "ldap", "winrm", "mssql", "rdp"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("impacket", "enum4linux-ng"),
        successors=("ldapsearch",),
        safety_class="active",
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Successor to CrackMapExec; requires an internal-network scope.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="impacket",
        display_name="Impacket",
        vendor="fortra",
        project_url="https://github.com/fortra/impacket",
        license="Apache-2.0",
        category="enterprise",
        subcategory="ad",
        description="Collection of Python classes for working with network protocols and SMB/Kerberos.",
        capabilities=("smb-enumeration", "kerberos-enumeration", "domain-enumeration"),
        version="0.12.0",
        language="python",
        tags=("smb", "kerberos", "ad"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "domain"),
        protocols=("smb", "ldap", "kerberos", "winrm", "mssql"),
        output_formats=("text",),
        alternatives=("netexec",),
        successors=("ldapsearch",),
        safety_class="active",
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Provides protocol clients used by NetExec and enumeration tooling.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="enum4linux-ng",
        display_name="enum4linux-ng",
        vendor="cdsheets",
        project_url="https://github.com/cddmp/enum4linux-ng",
        license="GPL-2.0",
        category="enterprise",
        subcategory="ad",
        description="Windows / Samba enumeration tool for SMB, RPC and NetBIOS.",
        capabilities=("smb-enumeration", "windows-enumeration", "domain-enumeration"),
        version="1.3.0",
        language="python",
        tags=("smb", "windows", "enumeration"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip"),
        protocols=("smb", "netbios", "rpc"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("netexec", "impacket"),
        successors=("ldapsearch",),
        safety_class="active",
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Modern rewrite of enum4linux with YAML output.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="ldapsearch",
        display_name="ldapsearch",
        vendor="OpenLDAP",
        project_url="https://www.openldap.org/software/man.cgi?query=ldapsearch",
        license="OpenLDAP Public License",
        category="enterprise",
        subcategory="ldap",
        description="LDAP query utility for directory enumeration and attribute discovery.",
        capabilities=("ldap-enumeration", "active-directory-intelligence"),
        version="2.6.0",
        language="c",
        tags=("ldap", "directory"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "domain"),
        protocols=("ldap", "ldaps"),
        output_formats=("text",),
        successors=("analysis",),
        safety_class="active",
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Used to extract AD attributes after authenticated access.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="rpcclient",
        display_name="rpcclient",
        vendor="Samba",
        project_url="https://www.samba.org/samba/docs/current/man-html/rpcclient.1.html",
        license="GPL-3.0",
        category="enterprise",
        subcategory="rpc",
        description="SMB/RPC client for Windows domain enumeration and query.",
        capabilities=("smb-enumeration", "windows-enumeration"),
        version="4.20.0",
        language="c",
        tags=("smb", "rpc", "windows"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip"),
        protocols=("smb", "msrpc"),
        output_formats=("text",),
        successors=("analysis",),
        safety_class="active",
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Pairs with enum4linux-ng for deep share and user enumeration.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: SNMP network service tools.
SNMP_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="snmpwalk",
        display_name="snmpwalk",
        vendor="NET-SNMP",
        project_url="https://github.com/net-snmp/net-snmp",
        license="BSD-3-Clause",
        category="snmp",
        subcategory="enumeration",
        description="SNMP MIB walker for enumerating network device information.",
        capabilities=("snmp-enumeration", "network-device-enumeration"),
        version="5.9.4",
        language="c",
        tags=("snmp", "mib", "network"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "network"),
        protocols=("udp", "snmp"),
        output_formats=("text",),
        successors=("analysis",),
        safety_class="passive",
        operational_knowledge=("Requires a community string; scoped to permitted networks only.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: Cloud security tools (Sprint 017 integration).
CLOUD_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="prowler",
        display_name="Prowler",
        vendor="Prowler",
        project_url="https://github.com/prowler-cloud/prowler",
        license="Apache-2.0",
        category="cloud",
        subcategory="audit",
        description="AWS, Azure, GCP and Kubernetes security assessments and audits.",
        capabilities=("aws-security", "azure-security", "gcp-security", "cloud-asset-discovery", "cloud-misconfiguration"),
        version="4.5.0",
        language="python",
        tags=("cloud", "aws", "azure", "gcp", "audit"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("cloud",),
        protocols=("https",),
        output_formats=("json", "csv", "html", "text"),
        structured_formats=("json",),
        alternatives=("scoutsuite",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Feeds Sprint 017 Cloud Intelligence as an evidence provider.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="scoutsuite",
        display_name="ScoutSuite",
        vendor="nccgroup",
        project_url="https://github.com/nccgroup/ScoutSuite",
        license="GPL-2.0",
        category="cloud",
        subcategory="audit",
        description="Multi-cloud security auditing for AWS, Azure and GCP.",
        capabilities=("aws-security", "azure-security", "gcp-security", "cloud-misconfiguration"),
        version="5.14.0",
        language="python",
        tags=("cloud", "audit"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("cloud",),
        protocols=("https",),
        output_formats=("json", "html"),
        structured_formats=("json",),
        alternatives=("prowler",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Feeds Sprint 017 Cloud Intelligence topology and correlation.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
)


#: Container / Kubernetes security tools.
CONTAINER_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="trivy",
        display_name="Trivy",
        vendor="Aqua Security",
        project_url="https://github.com/aquasecurity/trivy",
        license="Apache-2.0",
        category="container",
        subcategory="image",
        description="Comprehensive scanner for container images, filesystems, repos and more.",
        capabilities=("container-analysis", "image-analysis", "sbom", "dependency-analysis"),
        version="0.54.0",
        language="go",
        tags=("container", "cve", "sbom", "image"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("image", "directory", "filesystem"),
        protocols=("oci", "container"),
        output_formats=("json", "table", "sarif", "text"),
        structured_formats=("json", "sarif"),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Used for supply-chain analysis of container artifacts.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="syft",
        display_name="Syft",
        vendor="Anchore",
        project_url="https://github.com/anchore/syft",
        license="Apache-2.0",
        category="container",
        subcategory="sbom",
        description="Generate SBOMs from container images and filesystems.",
        capabilities=("sbom-generation", "container-analysis", "dependency-analysis"),
        version="1.9.0",
        language="go",
        tags=("sbom", "container"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("image", "directory", "filesystem"),
        output_formats=("json", "cyclonedx", "spdx", "text"),
        structured_formats=("json", "cyclonedx", "spdx"),
        successors=("trivy", "grype"),
        safety_class="passive",
        operational_knowledge=("Feeds SBOM-based vulnerability mapping into Trivy/Grype.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="grype",
        display_name="Grype",
        vendor="Anchore",
        project_url="https://github.com/anchore/grype",
        license="Apache-2.0",
        category="container",
        subcategory="cve",
        description="Container image and filesystem vulnerability scanner.",
        capabilities=("container-analysis", "cve-analysis", "dependency-analysis"),
        version="0.80.0",
        language="go",
        tags=("container", "cve", "image"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("image", "directory", "filesystem"),
        output_formats=("json", "table", "sarif", "text"),
        structured_formats=("json", "sarif"),
        predecessors=("syft",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Consumes Syft SBOMs; report-only, no destructive actions.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="kube-bench",
        display_name="kube-bench",
        vendor="Aqua Security",
        project_url="https://github.com/aquasecurity/kube-bench",
        license="Apache-2.0",
        category="container",
        subcategory="kubernetes",
        description="CIS Benchmark compliance checks for Kubernetes clusters.",
        capabilities=("kubernetes-security", "k8s-configuration-analysis"),
        version="0.9.3",
        language="go",
        tags=("kubernetes", "cis", "compliance"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("kubernetes",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Requires cluster access within an authorized scope.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: Software composition / dependency analysis tools.
COMPOSITION_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="osv-scanner",
        display_name="OSV-Scanner",
        vendor="google",
        project_url="https://github.com/google/osv-scanner",
        license="Apache-2.0",
        category="composition",
        subcategory="dependency",
        description="Vulnerability scanner for dependencies using the OSV database.",
        capabilities=("dependency-analysis", "vulnerability-mapping"),
        version="1.8.4",
        language="go",
        tags=("dependency", "osv", "cve"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("lockfile", "directory", "filesystem"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Maps dependency versions to OSV advisories.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)
