# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Recon / DNS / network arsenal tool specs."""

from __future__ import annotations

from hunterx.domain.tool_mastery import ToolSupportLevel
from hunterx.tools.mastery.specs import ToolSpec

#: Passive/active recon, subdomain enumeration and DNS intelligence.
RECON_DNS_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="amass",
        display_name="Amass",
        vendor="OWASP",
        project_url="https://github.com/owasp-amass/amass",
        license="Apache-2.0",
        category="recon",
        subcategory="dns",
        description="In-depth attack surface mapping and external asset discovery.",
        capabilities=("subdomain-enumeration", "asn-enumeration", "org-enumeration", "asset-discovery"),
        version="4.2.0",
        language="go",
        tags=("attack-surface", "enumeration", "asn"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        protocols=("dns", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="recon-json",
        normalizer_id="recon-normalizer",
        adapter_id="hunterx.tools.recon.amass:AmassAdapter",
        version_constraints=(">=4.0.0",),
        alternatives=("subfinder", "findomain", "assetfinder"),
        complementary=("nuclei", "httpx"),
        successors=("httpx", "nuclei"),
        safety_class="passive",
        operational_knowledge=("Active enumeration can be slow and network intensive.",),
        false_negatives=("Passive-only runs can miss assets reachable only via active sources.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="subfinder",
        display_name="Subfinder",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/subfinder",
        license="MIT",
        category="recon",
        subcategory="dns",
        description="Fast passive subdomain enumeration from curated online sources.",
        capabilities=("subdomain-enumeration", "asset-discovery"),
        version="2.14.0",
        language="go",
        tags=("osint", "passive", "subdomain"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        protocols=("https", "dns"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="recon-json",
        normalizer_id="recon-normalizer",
        adapter_id="hunterx.tools.recon.subfinder:SubfinderAdapter",
        version_constraints=(">=2.0.0",),
        alternatives=("amass", "findomain", "assetfinder"),
        successors=("httpx", "nuclei"),
        safety_class="passive",
        operational_knowledge=("Passive sources can lag behind live infrastructure.",),
        false_negatives=("May miss subdomains not indexed in public sources.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="assetfinder",
        display_name="Assetfinder",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/assetfinder",
        license="MIT",
        category="recon",
        subcategory="dns",
        description="Lightweight tool for finding domains and subdomains related to a target.",
        capabilities=("subdomain-enumeration",),
        version="0.4.0",
        language="go",
        tags=("osint", "subdomain"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        output_formats=("text",),
        parser_id="recon-text",
        normalizer_id="recon-normalizer",
        adapter_id="hunterx.tools.recon.assetfinder:AssetfinderAdapter",
        alternatives=("subfinder", "findomain"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("No active resolution; results may contain stale entries.",),
        false_negatives=("Stale or incomplete for long-lived infrastructures.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="findomain",
        display_name="Findomain",
        vendor="Findomain",
        project_url="https://github.com/Findomain/Findomain",
        license="GPL-3.0",
        category="recon",
        subcategory="dns",
        description="Subdomain enumeration with certificate transparency, PTR and zone walking.",
        capabilities=("subdomain-enumeration", "certificate-enumeration", "dns-intelligence"),
        version="9.0.1",
        language="rust",
        tags=("osint", "subdomain", "certificate"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="recon-json",
        normalizer_id="recon-normalizer",
        adapter_id="hunterx.tools.recon.findomain:FindomainAdapter",
        alternatives=("subfinder", "amass"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("Active modes require working resolvers.",),
        execution_type="binary",
        package_manager="cargo",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="theharvester",
        display_name="theHarvester",
        vendor="Sekaia",
        project_url="https://github.com/laramies/theHarvester",
        license="GPL-2.0",
        category="recon",
        subcategory="osint",
        description="E-mail, subdomain and hostname recon from public sources.",
        capabilities=("subdomain-enumeration", "osint", "org-enumeration", "asset-discovery"),
        version="4.3.0",
        language="python",
        tags=("osint", "email", "subdomain"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="recon-json",
        normalizer_id="recon-normalizer",
        adapter_id="hunterx.tools.recon.theharvester:TheHarvesterAdapter",
        alternatives=("subfinder", "findomain"),
        successors=("httpx",),
        safety_class="passive",
        operational_knowledge=("Source rate limits can throttle large runs.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="bbot",
        display_name="BBOT",
        vendor="Black Lantern Security",
        project_url="https://github.com/blacklanternsecurity/bbot",
        license="GPL-3.0",
        category="recon",
        subcategory="attack-surface",
        description="Modular, recursive attack surface discovery with passive and active modules.",
        capabilities=("subdomain-enumeration", "asset-discovery", "osint"),
        version="2.3.0",
        language="python",
        tags=("attack-surface", "osint", "modular"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="recon-json",
        normalizer_id="recon-normalizer",
        adapter_id="hunterx.tools.recon.bbot:BBOTAdapter",
        alternatives=("amass", "subfinder"),
        successors=("httpx", "nuclei"),
        safety_class="passive",
        operational_knowledge=("Heavier than single-purpose tools; requires Python environment.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="spiderfoot",
        display_name="SpiderFoot",
        vendor="SpiderFoot",
        project_url="https://github.com/smicallef/spiderfoot",
        license="MIT",
        category="recon",
        subcategory="osint",
        description="Automated OSINT and attack surface discovery across 200+ modules.",
        capabilities=("osint", "asset-discovery", "org-enumeration", "asn-enumeration"),
        version="4.0.0",
        language="python",
        tags=("osint", "automation", "attack-surface"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain", "ip", "org"),
        output_formats=("json", "csv"),
        structured_formats=("json",),
        safety_class="passive",
        operational_knowledge=("Heavyweight; prefers a running server or long CLI runs.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="dnsrecon",
        display_name="DNSrecon",
        vendor="darkoperator",
        project_url="https://github.com/darkoperator/dnsrecon",
        license="GPL-2.0",
        category="dns",
        subcategory="recon",
        description="DNS enumeration, zone transfer attempts, brute forcing and SRV records.",
        capabilities=("dns-enumeration", "brute-force-dns", "record-enumeration"),
        version="1.0.0",
        language="python",
        tags=("dns", "enumeration", "zone-transfer"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("domain",),
        protocols=("dns",),
        output_formats=("json", "xml"),
        structured_formats=("json", "xml"),
        safety_class="read-only",
        operational_knowledge=("Zone transfer attempts are active; scope carefully.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="crt-sh",
        display_name="crt.sh Certificate Transparency",
        vendor="crt.sh",
        project_url="https://crt.sh",
        license="CC0-1.0",
        category="recon",
        subcategory="certificate",
        description="Certificate Transparency log search for subdomains and certificates.",
        capabilities=("certificate-enumeration", "subdomain-enumeration"),
        version="1.0.0",
        language="",
        tags=("certificate", "ct", "subdomain"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("domain",),
        protocols=("https",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        safety_class="passive",
        operational_knowledge=("Rate limits apply; certificate history can be stale.",),
        execution_type="remote",
        container_available=False,
        binary_available=False,
    ),
)


#: DNS resolution / enumeration tools.
DNS_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="dnsx",
        display_name="DNSx",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/dnsx",
        license="MIT",
        category="dns",
        subcategory="resolution",
        description="Fast multi-purpose DNS toolkit for resolution, wildcard detection and record enum.",
        capabilities=("dns-resolution", "record-enumeration", "wildcard-detection"),
        version="1.2.1",
        language="go",
        tags=("dns", "resolver", "wildcard"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        protocols=("dns",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="dnsx-jsonl",
        normalizer_id="dns-normalizer",
        adapter_id="hunterx.tools.dns.dnsx:DnsxAdapter",
        alternatives=("dig", "dnsrecon"),
        successors=("httpx",),
        safety_class="read-only",
        operational_knowledge=("Wildcard detection is important to avoid false hosts.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="massdns",
        display_name="MassDNS",
        vendor="blechschmidt",
        project_url="https://github.com/blechschmidt/massdns",
        license="MIT",
        category="dns",
        subcategory="resolution",
        description="High-performance DNS stub resolver for bulk lookups.",
        capabilities=("dns-resolution",),
        version="1.0.0",
        language="c",
        tags=("dns", "bulk", "resolver"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("domain",),
        protocols=("dns",),
        output_formats=("text", "json"),
        structured_formats=("json",),
        safety_class="read-only",
        operational_knowledge=("High volume; needs resolver lists and careful rate control.",),
        execution_type="binary",
        container_available=False,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="shuffledns",
        display_name="Shuffledns",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/shuffledns",
        license="MIT",
        category="dns",
        subcategory="resolution",
        description="Massdns wrapper with recursive subdomain brute forcing.",
        capabilities=("dns-resolution", "brute-force-dns"),
        version="1.0.9",
        language="go",
        tags=("dns", "bruteforce", "wrapper"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("domain",),
        protocols=("dns",),
        output_formats=("text",),
        safety_class="read-only",
        operational_knowledge=("Requires massdns underneath; use with in-scope wordlists.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="dnspython",
        display_name="dnspython",
        vendor="dnspython",
        project_url="https://github.com/rthalley/dnspython",
        license="ISC",
        category="dns",
        subcategory="library",
        description="In-process DNS library used for resolution, record enumeration and analysis.",
        capabilities=("dns-resolution", "record-enumeration"),
        version="2.6.0",
        language="python",
        tags=("dns", "library"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("domain",),
        protocols=("dns",),
        output_formats=("json",),
        structured_formats=("json",),
        parser_id="json",
        normalizer_id="dns-normalizer",
        adapter_id="hunterx.tools.dns.dnspython:DnspythonAdapter",
        alternatives=("dig",),
        successors=("httpx",),
        safety_class="read-only",
        operational_knowledge=("In-process; no external binary required.",),
        execution_type="pip",
        package_manager="pip",
        container_available=False,
        binary_available=False,
    ),
)


#: Network discovery / port scanning tools.
NETWORK_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="naabu",
        display_name="Naabu",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/naabu",
        license="MIT",
        category="network",
        subcategory="port",
        description="Fast port scanner focused on reliability and simplicity.",
        capabilities=("port-discovery", "host-discovery"),
        version="2.3.1",
        language="go",
        tags=("port-scan", "network"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("host", "ip", "cidr"),
        protocols=("tcp", "udp"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="naabu-jsonl",
        normalizer_id="port-normalizer",
        adapter_id="hunterx.tools.livehost.naabu:NaabuAdapter",
        alternatives=("nmap", "masscan", "rustscan"),
        successors=("nmap",),
        safety_class="active",
        operational_knowledge=("Fast SYN scans are active; scope must be explicit.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="nmap",
        display_name="Nmap",
        vendor="Nmap Project",
        project_url="https://github.com/nmap/nmap",
        license="Nmap Public Source License",
        category="network",
        subcategory="scan",
        description="Network discovery and security auditing: port scan, service/version detection, OS detection.",
        capabilities=("port-discovery", "service-discovery", "version-detection", "os-detection", "network-discovery"),
        version="7.94",
        language="c",
        tags=("port-scan", "service", "os", "network"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("host", "ip", "cidr", "network"),
        protocols=("tcp", "udp", "icmp", "sctp"),
        output_formats=("xml", "json", "text"),
        structured_formats=("xml",),
        parser_id="nmap-xml",
        normalizer_id="port-normalizer",
        adapter_id="hunterx.tools.livehost.nmap:NmapAdapter",
        version_constraints=(">=7.0",),
        alternatives=("masscan", "naabu", "rustscan"),
        successors=("vulners", "nuclei"),
        safety_class="active",
        resource_requirements="NSE scripts can be resource heavy",
        operational_knowledge=("Use XML output (not human text) when structured output is needed.",),
        false_positives=("OS detection is probabilistic.",),
        execution_type="binary",
        package_manager="apt",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="masscan",
        display_name="Masscan",
        vendor="robertdavidgraham",
        project_url="https://github.com/robertdavidgraham/masscan",
        license="Apache-2.0",
        category="network",
        subcategory="port",
        description="Very fast TCP port scanner for large address spaces.",
        capabilities=("port-discovery",),
        version="1.3.2",
        language="c",
        tags=("port-scan", "large-scale"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("ip", "cidr", "network"),
        protocols=("tcp", "udp"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="masscan-json",
        normalizer_id="port-normalizer",
        adapter_id="hunterx.tools.livehost.masscan:MasscanAdapter",
        alternatives=("nmap", "naabu"),
        successors=("nmap",),
        safety_class="active",
        rate_limits="needs explicit rate limit",
        operational_knowledge=("Requires root; extremely fast; very easy to overshoot scope.",),
        execution_type="binary",
        container_available=False,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="rustscan",
        display_name="RustScan",
        vendor="RustScan",
        project_url="https://github.com/RustScan/RustScan",
        license="MIT",
        category="network",
        subcategory="port",
        description="High-speed port scanner that feeds results into Nmap.",
        capabilities=("port-discovery",),
        version="2.1.1",
        language="rust",
        tags=("port-scan", "fast"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("host", "ip", "cidr"),
        protocols=("tcp",),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("nmap", "naabu"),
        successors=("nmap",),
        safety_class="active",
        operational_knowledge=("Designed to pipe results into Nmap for service detection.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="unicornscan",
        display_name="Unicornscan",
        vendor="Unicornscan",
        project_url="https://github.com/curetheplague/Unicornscan",
        license="GPL-2.0",
        category="network",
        subcategory="port",
        description="Distributed, asynchronous port scanner with accurate UDP/TCP probing.",
        capabilities=("port-discovery",),
        version="0.4.7",
        language="c",
        tags=("port-scan", "udp"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "cidr"),
        protocols=("tcp", "udp"),
        output_formats=("text",),
        safety_class="active",
        operational_knowledge=("Legacy tool; strong UDP scanning capability.",),
        execution_type="binary",
        container_available=False,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="arp-scan",
        display_name="arp-scan",
        vendor="royhills",
        project_url="https://github.com/royhills/arp-scan",
        license="GPL-3.0",
        category="network",
        subcategory="discovery",
        description="ARP-based host discovery on local networks.",
        capabilities=("host-discovery", "network-discovery"),
        version="1.10.0",
        language="c",
        tags=("arp", "lan", "discovery"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("network",),
        protocols=("arp",),
        output_formats=("text",),
        safety_class="active",
        operational_knowledge=("Local network only; requires interface access.",),
        execution_type="binary",
        container_available=False,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="fping",
        display_name="fping",
        vendor="fping",
        project_url="https://github.com/schweikert/fping",
        license="Apache-2.0",
        category="network",
        subcategory="discovery",
        description="Fast ICMP host liveness checking over large ranges.",
        capabilities=("host-discovery",),
        version="5.1.0",
        language="c",
        tags=("icmp", "liveness", "discovery"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "cidr"),
        protocols=("icmp",),
        output_formats=("text",),
        safety_class="active",
        operational_knowledge=("ICMP may be filtered; complements TCP-based discovery.",),
        execution_type="binary",
        container_available=False,
        binary_available=True,
    ),
)
