# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Vulnerability / injection / OOB / secrets / SAST / proxy arsenal tool specs."""

from __future__ import annotations

from hunterx.domain.tool_mastery import ToolSupportLevel
from hunterx.tools.mastery.specs import ToolSpec

#: Vulnerability discovery tools.
VULN_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="nuclei",
        display_name="Nuclei",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/nuclei",
        license="MIT",
        category="vulnerability",
        subcategory="scanner",
        description="Template-based vulnerability scanner for web, DNS, network and infrastructure.",
        capabilities=("cve-detection", "misconfiguration-detection", "web-vulnerability-detection", "exposure-detection"),
        version="3.2.0",
        language="go",
        tags=("scanner", "templates", "cve"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("url", "host", "domain", "ip"),
        protocols=("http", "https", "dns", "tcp"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="nuclei-jsonl",
        normalizer_id="vulnerability-candidate-normalizer",
        adapter_id="hunterx.tools.vuln.nuclei:NucleiAdapter",
        version_constraints=(">=3.0.0",),
        alternatives=("nikto", "zap", "openvas"),
        successors=("interactsh", "sqlmap", "dalfox"),
        safety_class="low-impact-active",
        resource_requirements="templates and concurrency drive resource use",
        rate_limits="rate limit to avoid load",
        operational_knowledge=("Nuclei output is a candidate observation; every match requires validation.",),
        false_positives=("Template matches require manual validation; not all are exploitable.",),
        false_negatives=("Templates outside the active set; OAST detection disabled by default.",),
        execution_type="binary",
        package_manager="go",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="openvas",
        display_name="OpenVAS / Greenbone",
        vendor="Greenbone",
        project_url="https://github.com/greenbone/openvas-scanner",
        license="AGPL-3.0",
        category="vulnerability",
        subcategory="scanner",
        description="Open-source vulnerability scanner with a comprehensive NASL plugin feed.",
        capabilities=("cve-detection", "misconfiguration-detection", "network-vulnerability-detection"),
        version="23.0.0",
        language="c",
        tags=("scanner", "network", "cve"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("host", "ip", "network"),
        protocols=("tcp", "udp"),
        output_formats=("xml", "json"),
        structured_formats=("xml",),
        alternatives=("nuclei",),
        successors=("validation",),
        safety_class="active",
        operational_knowledge=("Heavyweight; requires Greenbone suite. Scan results are candidates.",),
        execution_type="binary",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="wapiti",
        display_name="Wapiti",
        vendor="IFSIC",
        project_url="https://github.com/wapiti-scanner/wapiti",
        license="Apache-2.0",
        category="vulnerability",
        subcategory="scanner",
        description="Web application vulnerability scanner with black-box detection modules.",
        capabilities=("web-vulnerability-detection",),
        version="3.1.7",
        language="python",
        tags=("scanner", "web", "xss", "sqli"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "html", "text"),
        structured_formats=("json",),
        alternatives=("nuclei",),
        successors=("validation",),
        safety_class="active",
        operational_knowledge=("Modular; can combine with free proxies for session support.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
)


#: Injection discovery / validation tools.
INJECTION_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="dalfox",
        display_name="Dalfox",
        vendor="hahwul",
        project_url="https://github.com/hahwul/dalfox",
        license="MIT",
        category="injection",
        subcategory="xss",
        description="Powerful open-source XSS scanner and parameter analysis tool.",
        capabilities=("xss-discovery", "reflection-analysis", "parameter-analysis", "xss-validation"),
        version="2.9.3",
        language="go",
        tags=("xss", "scanner", "validation"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("xssstrike",),
        successors=("proof-replay",),
        safety_class="active",
        operational_knowledge=("Reflection + context + execution evidence are distinct stages.",),
        false_positives=("A reflected parameter is NOT automatically confirmed XSS.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="xssstrike",
        display_name="XSStrike",
        vendor="s0md3v",
        project_url="https://github.com/s0md3v/XSStrike",
        license="GPL-3.0",
        category="injection",
        subcategory="xss",
        description="Advanced XSS detection suite with fuzzing and payload generation.",
        capabilities=("xss-discovery", "dom-analysis", "reflection-analysis"),
        version="3.1.5",
        language="python",
        tags=("xss", "fuzz", "dom"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("text",),
        alternatives=("dalfox",),
        successors=("proof-replay",),
        safety_class="active",
        operational_knowledge=("DOM analysis requires a browser-capable context.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="sqlmap",
        display_name="SQLmap",
        vendor="sqlmapproject",
        project_url="https://github.com/sqlmapproject/sqlmap",
        license="GPL-2.0",
        category="injection",
        subcategory="sqli",
        description="Automatic SQL injection and database takeover tool.",
        capabilities=("sql-injection-detection", "sql-injection-validation", "database-fingerprinting"),
        version="1.8.6",
        language="python",
        tags=("sqli", "database", "validation"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("ghauri",),
        successors=("proof-replay",),
        safety_class="high-impact",
        destructive=True,
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Never automatically execute high-impact database actions.",),
        false_positives=("Injection point confidence requires manual review.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="ghauri",
        display_name="Ghauri",
        vendor="rwxdot",
        project_url="https://github.com/rwxdot/ghauri",
        license="MIT",
        category="injection",
        subcategory="sqli",
        description="Cross-platform advanced SQL injection detection and exploitation tool.",
        capabilities=("sql-injection-detection", "sql-injection-validation", "database-fingerprinting"),
        version="2.0.4",
        language="python",
        tags=("sqli", "database"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("sqlmap",),
        successors=("proof-replay",),
        safety_class="high-impact",
        destructive=True,
        scope_requirements="requires explicit authorization",
        operational_knowledge=("High-impact validation must follow the Proof/Safety policy.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="commix",
        display_name="Commix",
        vendor="commixproject",
        project_url="https://github.com/commixproject/commix",
        license="GPL-3.0",
        category="injection",
        subcategory="command",
        description="Automated OS command injection detection and exploitation.",
        capabilities=("command-injection-detection", "command-injection-validation"),
        version="3.9.0",
        language="python",
        tags=("rce", "command-injection"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("text",),
        successors=("interactsh", "proof-replay"),
        safety_class="high-impact",
        destructive=True,
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Execution proof must use the safest available verification mechanism.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="tplmap",
        display_name="Tplmap",
        vendor="epinna",
        project_url="https://github.com/epinna/tplmap",
        license="GPL-3.0",
        category="injection",
        subcategory="ssti",
        description="Server-Side Template Injection detection and exploitation tool.",
        capabilities=("ssti-detection", "template-engine-identification"),
        version="1.0.0",
        language="python",
        tags=("ssti", "template"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("text",),
        alternatives=("sstimap",),
        successors=("interactsh", "proof-replay"),
        safety_class="high-impact",
        destructive=True,
        scope_requirements="requires explicit authorization",
        operational_knowledge=("SSTI detection requires engine identification to prove impact.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="sstimap",
        display_name="SSTImap",
        vendor="vladris",
        project_url="https://github.com/vladris/sstimap",
        license="MIT",
        category="injection",
        subcategory="ssti",
        description="Automatic SSTI detection and exploitation with multiple template engines.",
        capabilities=("ssti-detection", "ssti-validation", "template-engine-identification"),
        version="1.2.0",
        language="python",
        tags=("ssti", "template"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("text",),
        alternatives=("tplmap",),
        successors=("interactsh", "proof-replay"),
        safety_class="high-impact",
        destructive=True,
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Maintained fork of Tplmap; broader engine support.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
    ToolSpec(
        tool_id="xxeinjector",
        display_name="XXEinjector",
        vendor="enjoiz",
        project_url="https://github.com/enjoiz/XXEinjector",
        license="MIT",
        category="injection",
        subcategory="xxe",
        description="Tool for automatic XXE injection detection and exploitation.",
        capabilities=("xxe-detection", "xxe-validation", "oob-xml-interaction"),
        version="1.0.0",
        language="ruby",
        tags=("xxe", "xml"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("text",),
        successors=("interactsh", "proof-replay"),
        safety_class="high-impact",
        destructive=True,
        scope_requirements="requires explicit authorization",
        operational_knowledge=("Integrates with Interactsh for OOB XML interactions.",),
        execution_type="binary",
        container_available=False,
        binary_available=True,
    ),
)


#: Out-of-band / callback tools.
OOB_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="interactsh",
        display_name="Interactsh",
        vendor="ProjectDiscovery",
        project_url="https://github.com/projectdiscovery/interactsh",
        license="MIT",
        category="oob",
        subcategory="callback",
        description="OOB interaction server for detecting SSRF, blind injection, XXE and more.",
        capabilities=("oob-callback", "dns-callback", "http-callback", "smtp-callback", "interaction-correlation"),
        version="1.2.1",
        language="go",
        tags=("oast", "ssrf", "blind"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("callback",),
        protocols=("dns", "http", "https", "smtp"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        successors=("proof-replay",),
        safety_class="active",
        operational_knowledge=(
            "Every interaction must be correlated with mission, target, request, proof attempt, timestamp and token.",
        ),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: Secrets discovery tools.
SECRETS_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="gitleaks",
        display_name="Gitleaks",
        vendor="gitleaks",
        project_url="https://github.com/gitleaks/gitleaks",
        license="MIT",
        category="secrets",
        subcategory="scanner",
        description="Secret scanner for git repositories, files and directories.",
        capabilities=("secret-discovery", "credential-discovery", "token-discovery", "key-discovery"),
        version="8.18.4",
        language="go",
        tags=("secrets", "git", "scanner"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("repository", "directory", "file"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        parser_id="gitleaks-json",
        normalizer_id="secret-normalizer",
        adapter_id="hunterx.tools.secrets.gitleaks:GitleaksAdapter",
        version_constraints=(">=8.0.0",),
        alternatives=("trufflehog", "detect-secrets"),
        successors=("redaction",),
        safety_class="passive",
        operational_knowledge=("Raw credentials must NEVER be stored unredacted.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="trufflehog",
        display_name="TruffleHog",
        vendor="Truffle Security",
        project_url="https://github.com/trufflesecurity/trufflehog",
        license="AGPL-3.0",
        category="secrets",
        subcategory="scanner",
        description="Find, verify and analyze leaked credentials in repos, files and more.",
        capabilities=("secret-discovery", "credential-discovery", "token-discovery"),
        version="3.80.0",
        language="go",
        tags=("secrets", "scanning"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("repository", "directory", "url"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("gitleaks", "detect-secrets"),
        successors=("redaction",),
        safety_class="passive",
        operational_knowledge=("Raw credentials must NEVER be stored unredacted.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="detect-secrets",
        display_name="detect-secrets",
        vendor="Yelp",
        project_url="https://github.com/Yelp/detect-secrets",
        license="Apache-2.0",
        category="secrets",
        subcategory="scanner",
        description="Enterprise-friendly secret detection with baseline support.",
        capabilities=("secret-discovery", "credential-discovery", "token-discovery"),
        version="1.5.0",
        language="python",
        tags=("secrets", "baseline"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("repository", "directory", "file"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("gitleaks", "trufflehog"),
        successors=("redaction",),
        safety_class="passive",
        operational_knowledge=("Baselines allow explicit allow-listing of known-safe matches.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=False,
    ),
)


#: SAST / code intelligence tools.
SAST_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="semgrep",
        display_name="Semgrep",
        vendor="Semgrep",
        project_url="https://github.com/semgrep/semgrep",
        license="LGPL-2.1",
        category="sast",
        subcategory="static",
        description="Fast, open-source static analysis for many languages with custom rules.",
        capabilities=("sast", "code-pattern-analysis", "vulnerability-pattern-detection"),
        version="1.82.0",
        language="ocaml",
        tags=("sast", "static", "rules"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("directory", "repository", "file"),
        output_formats=("json", "sarif", "text"),
        structured_formats=("json", "sarif"),
        alternatives=("codeql",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Rules are user-supplied knowledge; findings are code-pattern candidates.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="codeql",
        display_name="CodeQL CLI",
        vendor="GitHub",
        project_url="https://github.com/github/codeql-cli-binaries",
        license="Commercial / available where licensing permits",
        category="sast",
        subcategory="static",
        description="Semantic code analysis engine for vulnerabilities, errors and variant analysis.",
        capabilities=("sast", "code-flow-analysis", "taint-analysis", "vulnerability-pattern-detection"),
        version="2.17.0",
        language="go",
        tags=("sast", "codeql", "semantic"),
        support_level=ToolSupportLevel.KNOWLEDGE_ONLY,
        targets=("directory", "repository"),
        output_formats=("sarif", "text"),
        structured_formats=("sarif",),
        alternatives=("semgrep",),
        successors=("validation",),
        safety_class="passive",
        operational_knowledge=("Use where licensing and deployment conditions permit.",),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
)


#: Web proxy / interception tools.
PROXY_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="zap",
        display_name="OWASP ZAP",
        vendor="OWASP",
        project_url="https://github.com/zaproxy/zaproxy",
        license="Apache-2.0",
        category="proxy",
        subcategory="interception",
        description="Web application security scanner and interception proxy.",
        capabilities=("http-interception", "request-replay", "response-analysis", "active-testing"),
        version="2.15.0",
        language="java",
        tags=("proxy", "scanner", "interception"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("url",),
        protocols=("http", "https"),
        output_formats=("json", "xml", "text"),
        structured_formats=("json", "xml"),
        alternatives=("mitmproxy",),
        successors=("validation",),
        safety_class="active",
        operational_knowledge=(
            "Use as an observation source, replay engine and validation engine, not merely a scanner.",
        ),
        execution_type="binary",
        container_available=True,
        binary_available=True,
    ),
    ToolSpec(
        tool_id="mitmproxy",
        display_name="mitmproxy",
        vendor="mitmproxy",
        project_url="https://github.com/mitmproxy/mitmproxy",
        license="MIT",
        category="proxy",
        subcategory="interception",
        description="Interactive HTTPS proxy for traffic capture, replay and analysis.",
        capabilities=("http-interception", "request-replay", "response-analysis", "traffic-capture"),
        version="10.4.0",
        language="python",
        tags=("proxy", "capture", "replay"),
        support_level=ToolSupportLevel.PARTIAL_SUPPORT,
        targets=("traffic",),
        protocols=("http", "https"),
        output_formats=("json", "text"),
        structured_formats=("json",),
        alternatives=("zap",),
        successors=("analysis",),
        safety_class="active",
        operational_knowledge=("Python scripting enables programmatic traffic analysis.",),
        execution_type="pip",
        package_manager="pip",
        container_available=True,
        binary_available=True,
    ),
)


#: Deterministic in-process proof replay tools.
PROOF_REPLAY_TOOLS: tuple[ToolSpec, ...] = (
    ToolSpec(
        tool_id="proof-replay",
        display_name="Proof Replay",
        vendor="HunterX",
        project_url="",
        license="Apache-2.0",
        category="proof",
        subcategory="replay",
        description="Deterministic in-process safe proof replay probe for demonstrating proof candidates.",
        capabilities=("safe-validation", "proof-replay", "impact-statement"),
        version="1.0.0",
        language="python",
        tags=("proof", "replay", "validation"),
        support_level=ToolSupportLevel.FULLY_SUPPORTED,
        targets=("url", "host", "domain", "ip", "service"),
        protocols=("http", "https"),
        output_formats=("json",),
        structured_formats=("json",),
        parser_id="json",
        normalizer_id="proof-replay-normalizer",
        adapter_id="hunterx.tools.proof_replay.adapters:ProofReplayAdapter",
        version_constraints=(">=1.0.0",),
        predecessors=("interactsh", "sqlmap", "dalfox", "sstimap", "xxeinjector"),
        safety_class="passive",
        operational_knowledge=(
            "Replay is a proof demonstration, never a weaponization step.",
            "Every replay request has already passed scope, safety and proof policy gates.",
        ),
        execution_type="pip",
        container_available=False,
        binary_available=False,
    ),
)
