# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""Canonical data-driven playbooks for the Sprint 025 arsenal.

Every playbook declares an objective, the capabilities required to achieve it,
preferred/fallback tools, preconditions, stop conditions and evidence/proof
requirements. They never hardcode unrestricted attack commands — concrete tool
selection is delegated to the mission-aware selector at runtime.
"""

from __future__ import annotations

from hunterx.domain.tool_mastery import (
    ToolPlaybook,
    ToolPlaybookCategory,
)
from hunterx.tools.mastery.playbooks import (
    build_playbook,
    build_step,
)

#: The canonical set of playbooks defined by the Sprint 025 contract.
PLAYBOOKS: tuple[ToolPlaybook, ...] = (
    build_playbook(
        playbook_id="web-initial-recon",
        name="Web initial recon",
        category=ToolPlaybookCategory.RECON,
        objective="Identify live web assets, technologies, WAFs and initial entry points.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment", "vulnerability-research"),
        steps=[
            build_step(
                step_id="web-recon-1",
                objective="Enumerate subdomains and assets.",
                required_capabilities=("subdomain-enumeration",),
                preferred_tools=("subfinder", "amass"),
                fallback_tools=("assetfinder", "findomain", "bbot"),
                evidence_requirements=("resolved-host", "asset-type", "discovery-source"),
            ),
            build_step(
                step_id="web-recon-2",
                objective="Probe live hosts and detect technology stacks.",
                required_capabilities=("http-probing", "technology-detection"),
                preferred_tools=("httpx",),
                fallback_tools=("whatweb",),
                evidence_requirements=("status-code", "technology-signature", "tls-fingerprint"),
            ),
            build_step(
                step_id="web-recon-3",
                objective="Detect WAF and rate-limit behavior before active testing.",
                required_capabilities=("waf-detection",),
                preferred_tools=("wafw00f",),
                evidence_requirements=("waf-signature", "blocking-behavior"),
                safety_class="read-only",
            ),
        ],
        stop_conditions=("targets exhausted", "authorization ceiling reached"),
        description="Standard entry playbook for external web assessment.",
    ),
    build_playbook(
        playbook_id="api-discovery",
        name="API endpoint discovery",
        category=ToolPlaybookCategory.DISCOVERY,
        objective="Discover API routes, schemas and parameters for later assessment.",
        mission_types=("bug-bounty", "pentest", "api-assessment", "web-assessment"),
        steps=[
            build_step(
                step_id="api-discovery-1",
                objective="Crawl and extract endpoints from live traffic.",
                required_capabilities=("crawling", "endpoint-discovery"),
                preferred_tools=("katana",),
                fallback_tools=("gospider", "hakrawler"),
                evidence_requirements=("url", "method", "source"),
            ),
            build_step(
                step_id="api-discovery-2",
                objective="Extract endpoints and parameters from JavaScript.",
                required_capabilities=("javascript-analysis", "endpoint-extraction"),
                preferred_tools=("jsluice",),
                fallback_tools=("linkfinder", "xnlinkfinder"),
                evidence_requirements=("js-endpoint", "parameter-name"),
                safety_class="read-only",
            ),
            build_step(
                step_id="api-discovery-3",
                objective="Discover hidden API parameters.",
                required_capabilities=("parameter-discovery",),
                preferred_tools=("arjun",),
                fallback_tools=("paramspider",),
                evidence_requirements=("parameter-name", "parameter-method"),
            ),
            build_step(
                step_id="api-discovery-4",
                objective="Parse OpenAPI/Postman schemas when available.",
                required_capabilities=("openapi-analysis",),
                preferred_tools=("openapi-parser",),
                fallback_tools=("postman-parser",),
                evidence_requirements=("endpoint", "operation", "schema"),
                safety_class="read-only",
            ),
        ],
        stop_conditions=("no new endpoints", "schema fully parsed"),
        description="Discover API surface before focused assessment.",
    ),
    build_playbook(
        playbook_id="subdomain-enumeration",
        name="Subdomain enumeration",
        category=ToolPlaybookCategory.RECON,
        objective="Enumerate all in-scope subdomains through passive and active sources.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "vulnerability-research"),
        steps=[
            build_step(
                step_id="sub-enum-1",
                objective="Passive subdomain enumeration from public sources.",
                required_capabilities=("subdomain-enumeration", "asset-discovery"),
                preferred_tools=("subfinder",),
                fallback_tools=("assetfinder", "theharvester", "crobat"),
                evidence_requirements=("subdomain", "source"),
                safety_class="passive",
            ),
            build_step(
                step_id="sub-enum-2",
                objective="Certificate transparency log lookups.",
                required_capabilities=("certificate-enumeration",),
                preferred_tools=("crt-sh",),
                fallback_tools=("findomain",),
                evidence_requirements=("cert-subdomain", "cert-serial"),
                safety_class="passive",
            ),
            build_step(
                step_id="sub-enum-3",
                objective="Resolve and deduplicate enumerated hostnames.",
                required_capabilities=("dns-resolution", "record-enumeration"),
                preferred_tools=("dnsx",),
                fallback_tools=("dnspython",),
                evidence_requirements=("resolved-ip", "record-type", "wildcard-status"),
                safety_class="read-only",
            ),
        ],
        stop_conditions=("resolution returns no new hosts", "source exhaustion"),
        description="Build the live subdomain set before probing.",
    ),
    build_playbook(
        playbook_id="network-recon",
        name="Network recon and service discovery",
        category=ToolPlaybookCategory.RECON,
        objective="Discover reachable hosts, open ports and running services on in-scope networks.",
        mission_types=("pentest", "network-assessment", "internal-assessment", "red-team"),
        steps=[
            build_step(
                step_id="net-recon-1",
                objective="Discover live hosts on the target range.",
                required_capabilities=("host-discovery",),
                preferred_tools=("fping",),
                fallback_tools=("arp-scan",),
                evidence_requirements=("live-host", "discovery-method"),
                safety_class="active",
            ),
            build_step(
                step_id="net-recon-2",
                objective="Scan for open ports.",
                required_capabilities=("port-discovery",),
                preferred_tools=("nmap",),
                fallback_tools=("naabu", "masscan", "rustscan"),
                evidence_requirements=("open-port", "protocol"),
                safety_class="active",
            ),
            build_step(
                step_id="net-recon-3",
                objective="Identify services and versions on open ports.",
                required_capabilities=("service-discovery", "version-detection"),
                preferred_tools=("nmap",),
                evidence_requirements=("service-name", "service-version"),
                safety_class="active",
            ),
        ],
        stop_conditions=("all in-scope hosts scanned", "scope limit reached"),
        description="Standard entry playbook for internal/network assessment.",
    ),
    build_playbook(
        playbook_id="web-content-discovery",
        name="Web content and directory discovery",
        category=ToolPlaybookCategory.DISCOVERY,
        objective="Discover directories, files and virtual hosts on target web applications.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="content-discovery-1",
                objective="Fuzz directories and files with tuned wordlists.",
                required_capabilities=("content-discovery", "directory-enumeration", "file-enumeration"),
                preferred_tools=("ffuf",),
                fallback_tools=("feroxbuster", "gobuster", "dirsearch"),
                evidence_requirements=("path", "status-code", "size"),
                safety_class="active",
            ),
            build_step(
                step_id="content-discovery-2",
                objective="Discover virtual hosts.",
                required_capabilities=("vhost-enumeration",),
                preferred_tools=("ffuf",),
                fallback_tools=("gobuster",),
                evidence_requirements=("vhost", "host-header", "status-code"),
                safety_class="active",
            ),
            build_step(
                step_id="content-discovery-3",
                objective="Generate target-specific wordlists.",
                required_capabilities=("wordlist-generation", "custom-wordlists"),
                preferred_tools=("cewl",),
                evidence_requirements=("wordlist", "source-url"),
                safety_class="passive",
            ),
        ],
        stop_conditions=("no new content", "rate limit enforced"),
        description="Locate hidden content that expands attack surface.",
    ),
    build_playbook(
        playbook_id="javascript-analysis",
        name="JavaScript analysis",
        category=ToolPlaybookCategory.ANALYSIS,
        objective="Mine JavaScript assets for endpoints, secrets and hidden parameters.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="js-analysis-1",
                objective="Extract endpoints and URLs from JavaScript.",
                required_capabilities=("javascript-analysis", "endpoint-extraction"),
                preferred_tools=("jsluice",),
                fallback_tools=("linkfinder", "xnlinkfinder"),
                evidence_requirements=("js-endpoint", "js-source", "source-map"),
                safety_class="read-only",
            ),
            build_step(
                step_id="js-analysis-2",
                objective="Discover secret indicators inside JavaScript.",
                required_capabilities=("secret-indicator-discovery",),
                preferred_tools=("secretfinder",),
                fallback_tools=("jsluice",),
                evidence_requirements=("secret-indicator", "js-source"),
                safety_class="read-only",
            ),
        ],
        stop_conditions=("no new endpoints or indicators",),
        description="Leverage client-side code for attack surface expansion.",
    ),
    build_playbook(
        playbook_id="secret-discovery",
        name="Secret discovery",
        category=ToolPlaybookCategory.DISCOVERY,
        objective="Locate credentials, tokens and keys exposed in scope.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "vulnerability-research"),
        steps=[
            build_step(
                step_id="secret-discovery-1",
                objective="Scan git repositories and files for secrets.",
                required_capabilities=("secret-discovery", "credential-discovery", "token-discovery"),
                preferred_tools=("gitleaks",),
                fallback_tools=("trufflehog", "detect-secrets"),
                evidence_requirements=("secret-type", "secret-location", "redacted-value"),
                safety_class="passive",
            ),
            build_step(
                step_id="secret-discovery-2",
                objective="Discover secret indicators inside JavaScript.",
                required_capabilities=("secret-indicator-discovery",),
                preferred_tools=("secretfinder",),
                fallback_tools=("jsluice",),
                evidence_requirements=("secret-indicator", "js-source"),
                safety_class="read-only",
            ),
        ],
        stop_conditions=("all in-scope repos scanned",),
        description="Find exposed secrets; never store raw credentials unredacted.",
    ),
    build_playbook(
        playbook_id="vulnerability-triage",
        name="Vulnerability triage",
        category=ToolPlaybookCategory.ASSESSMENT,
        objective="Prioritize candidate findings and decide what to validate and prove.",
        mission_types=(
            "bug-bounty",
            "pentest",
            "web-assessment",
            "api-assessment",
            "vulnerability-research",
        ),
        steps=[
            build_step(
                step_id="triage-1",
                objective="Scan for candidate vulnerabilities from discovered surface.",
                required_capabilities=("web-vulnerability-detection", "cve-detection", "misconfiguration-detection"),
                preferred_tools=("nuclei",),
                fallback_tools=("wapiti", "openvas"),
                evidence_requirements=("candidate-finding", "template-id", "severity"),
                safety_class="low-impact-active",
            ),
            build_step(
                step_id="triage-2",
                objective="Correlate findings with topology and technology context.",
                required_capabilities=("vulnerability-mapping", "cve-research"),
                preferred_tools=("searchsploit",),
                fallback_tools=("exploitdb",),
                evidence_requirements=("cve", "affected-version", "exploit-path"),
                safety_class="passive",
            ),
        ],
        stop_conditions=("all candidates correlated",),
        description="Candidates are not proof; this playbook feeds validation.",
    ),
    build_playbook(
        playbook_id="xss-validation",
        name="XSS validation",
        category=ToolPlaybookCategory.VALIDATION,
        objective="Validate reflected, stored and DOM-based XSS candidates with execution evidence.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="xss-validation-1",
                objective="Confirm reflection and context of candidate parameters.",
                required_capabilities=("reflection-analysis", "parameter-analysis"),
                preferred_tools=("dalfox",),
                fallback_tools=("xssstrike",),
                evidence_requirements=("reflection-point", "output-context"),
                safety_class="active",
            ),
            build_step(
                step_id="xss-validation-2",
                objective="Confirm execution with a safe proof payload.",
                required_capabilities=("xss-validation",),
                preferred_tools=("dalfox",),
                evidence_requirements=("execution-evidence", "payload", "context"),
                proof_requirements=("execution-evidence", "impact-statement"),
                safety_class="active",
            ),
        ],
        stop_conditions=("execution confirmed", "candidate disproved"),
        description="A reflected parameter is NOT confirmed XSS without execution evidence.",
    ),
    build_playbook(
        playbook_id="sqli-validation",
        name="SQL injection validation",
        category=ToolPlaybookCategory.VALIDATION,
        objective="Validate SQL injection candidates with differential behavior and safe DBMS identification.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="sqli-validation-1",
                objective="Confirm injection point and DBMS family.",
                required_capabilities=("sql-injection-detection", "database-fingerprinting"),
                preferred_tools=("sqlmap",),
                fallback_tools=("ghauri",),
                evidence_requirements=("injection-point", "dbms-family", "payload"),
                safety_class="high-impact",
            ),
            build_step(
                step_id="sqli-validation-2",
                objective="Prove impact through safe verification only.",
                required_capabilities=("sql-injection-validation",),
                preferred_tools=("sqlmap",),
                fallback_tools=("ghauri",),
                evidence_requirements=("differential-evidence", "proof-payload"),
                proof_requirements=("differential-evidence", "impact-statement"),
                safety_class="high-impact",
            ),
        ],
        stop_conditions=("impact proven safely", "candidate disproved"),
        description="Never automatically execute high-impact database actions.",
    ),
    build_playbook(
        playbook_id="ssrf-validation",
        name="SSRF validation",
        category=ToolPlaybookCategory.VALIDATION,
        objective="Validate SSRF candidates via out-of-band interaction correlation.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="ssrf-validation-1",
                objective="Test candidate endpoints with OOB callback payloads.",
                required_capabilities=("oob-callback", "http-callback", "dns-callback"),
                preferred_tools=("interactsh",),
                evidence_requirements=("callback-token", "interaction", "timestamp"),
                safety_class="active",
            ),
            build_step(
                step_id="ssrf-validation-2",
                objective="Correlate interactions back to mission, target and request.",
                required_capabilities=("interaction-correlation",),
                preferred_tools=("interactsh",),
                evidence_requirements=("mission-id", "target", "request", "token"),
                proof_requirements=("correlated-interaction", "impact-statement"),
                safety_class="active",
            ),
        ],
        stop_conditions=("interaction correlated", "candidate disproved"),
        description="Every interaction must be correlated with mission, target, request and token.",
    ),
    build_playbook(
        playbook_id="ssti-validation",
        name="SSTI validation",
        category=ToolPlaybookCategory.VALIDATION,
        objective="Identify template engine and validate SSTI with safe proof.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="ssti-validation-1",
                objective="Detect template injection and identify the engine.",
                required_capabilities=("ssti-detection", "template-engine-identification"),
                preferred_tools=("sstimap",),
                fallback_tools=("tplmap",),
                evidence_requirements=("template-engine", "injection-point"),
                safety_class="high-impact",
            ),
            build_step(
                step_id="ssti-validation-2",
                objective="Confirm execution with a safe proof payload.",
                required_capabilities=("ssti-validation",),
                preferred_tools=("sstimap",),
                fallback_tools=("tplmap",),
                evidence_requirements=("execution-evidence", "payload"),
                proof_requirements=("execution-evidence", "impact-statement"),
                safety_class="high-impact",
            ),
        ],
        stop_conditions=("execution confirmed", "candidate disproved"),
        description="Engine identification precedes exploitation.",
    ),
    build_playbook(
        playbook_id="xxe-validation",
        name="XXE validation",
        category=ToolPlaybookCategory.VALIDATION,
        objective="Validate XXE candidates using direct and OOB XML interaction.",
        mission_types=("bug-bounty", "pentest", "web-assessment", "api-assessment"),
        steps=[
            build_step(
                step_id="xxe-validation-1",
                objective="Detect XXE via safe external entity resolution.",
                required_capabilities=("xxe-detection", "oob-xml-interaction"),
                preferred_tools=("xxeinjector",),
                fallback_tools=("interactsh",),
                evidence_requirements=("xml-interaction", "entity-reflection"),
                safety_class="high-impact",
            ),
            build_step(
                step_id="xxe-validation-2",
                objective="Correlate OOB interactions and confirm impact.",
                required_capabilities=("interaction-correlation",),
                preferred_tools=("interactsh",),
                evidence_requirements=("correlated-interaction", "token"),
                proof_requirements=("correlated-interaction", "impact-statement"),
                safety_class="high-impact",
            ),
        ],
        stop_conditions=("interaction correlated", "candidate disproved"),
        description="Pair XXE testing with an OOB callback server.",
    ),
    build_playbook(
        playbook_id="graphql-assessment",
        name="GraphQL assessment",
        category=ToolPlaybookCategory.ASSESSMENT,
        objective="Assess GraphQL endpoints for introspection, query abuse and authorization issues.",
        mission_types=("bug-bounty", "pentest", "api-assessment"),
        steps=[
            build_step(
                step_id="graphql-1",
                objective="Probe GraphQL schema and introspection status.",
                required_capabilities=("graphql-introspection", "graphql-analysis"),
                preferred_tools=("graphqlmap",),
                fallback_tools=("inql",),
                evidence_requirements=("schema", "introspection-status"),
                safety_class="active",
            ),
            build_step(
                step_id="graphql-2",
                objective="Analyze queries for abuse and misconfiguration.",
                required_capabilities=("query-analysis",),
                preferred_tools=("graphqlmap",),
                fallback_tools=("inql",),
                evidence_requirements=("query", "response"),
                safety_class="active",
            ),
        ],
        stop_conditions=("schema analyzed", "scope reached"),
        description="Introspection must be explicitly permitted by scope.",
    ),
    build_playbook(
        playbook_id="cloud-assessment",
        name="Cloud assessment",
        category=ToolPlaybookCategory.ASSESSMENT,
        objective="Assess cloud posture, misconfigurations and exposed assets.",
        mission_types=("cloud-assessment", "pentest"),
        steps=[
            build_step(
                step_id="cloud-1",
                objective="Audit cloud configuration against CIS-style frameworks.",
                required_capabilities=("cloud-misconfiguration", "aws-security", "azure-security", "gcp-security"),
                preferred_tools=("prowler",),
                fallback_tools=("scoutsuite",),
                evidence_requirements=("control-id", "resource", "finding"),
                safety_class="passive",
            ),
            build_step(
                step_id="cloud-2",
                objective="Discover exposed cloud assets and storage.",
                required_capabilities=("cloud-asset-discovery", "storage-analysis"),
                preferred_tools=("prowler",),
                fallback_tools=("scoutsuite",),
                evidence_requirements=("asset", "exposure"),
                safety_class="passive",
            ),
        ],
        stop_conditions=("all in-scope accounts audited",),
        description="Feeds Sprint 017 Cloud Intelligence as evidence provider.",
    ),
    build_playbook(
        playbook_id="container-assessment",
        name="Container and supply-chain assessment",
        category=ToolPlaybookCategory.ASSESSMENT,
        objective="Assess container images, dependencies and SBOMs for known vulnerabilities.",
        mission_types=("pentest", "cloud-assessment", "vulnerability-research"),
        steps=[
            build_step(
                step_id="container-1",
                objective="Generate SBOMs for in-scope images.",
                required_capabilities=("sbom-generation", "container-analysis"),
                preferred_tools=("syft",),
                evidence_requirements=("sbom", "package", "version"),
                safety_class="passive",
            ),
            build_step(
                step_id="container-2",
                objective="Scan images and dependencies for CVEs.",
                required_capabilities=("container-analysis", "cve-analysis", "dependency-analysis"),
                preferred_tools=("trivy",),
                fallback_tools=("grype", "osv-scanner"),
                evidence_requirements=("cve", "package", "affected-version"),
                safety_class="passive",
            ),
        ],
        stop_conditions=("all images scanned",),
        description="Report-only supply-chain analysis; no destructive actions.",
    ),
    build_playbook(
        playbook_id="active-directory-assessment",
        name="Active Directory assessment",
        category=ToolPlaybookCategory.ASSESSMENT,
        objective="Assess AD/Windows infrastructure within an authorized internal scope.",
        mission_types=("internal-assessment", "red-team", "pentest"),
        steps=[
            build_step(
                step_id="ad-1",
                objective="Enumerate SMB, RPC and LDAP surfaces.",
                required_capabilities=("smb-enumeration", "windows-enumeration", "ldap-enumeration"),
                preferred_tools=("netexec",),
                fallback_tools=("impacket", "enum4linux-ng", "rpcclient"),
                evidence_requirements=("share", "user", "rpc-endpoint"),
                preconditions=("explicit authorization granted",),
                safety_class="active",
            ),
            build_step(
                step_id="ad-2",
                objective="Extract AD attributes and trust information.",
                required_capabilities=("active-directory-intelligence", "domain-enumeration"),
                preferred_tools=("ldapsearch",),
                fallback_tools=("netexec", "impacket"),
                evidence_requirements=("object", "attribute", "trust"),
                safety_class="active",
            ),
        ],
        stop_conditions=("enumerated surface complete", "scope reached"),
        description="Internal-network capability family, separate from web tooling.",
    ),
)


def register_default_playbooks(engine) -> None:
    """Register every canonical playbook into a :class:`ToolPlaybookEngine`."""
    engine.register_all(list(PLAYBOOKS))
