# Copyright (c) 2026 Ahmed Awad (NullC0d3)
# SPDX-License-Identifier: Apache-2.0

"""JavaScript Intelligence domain package.

Pure, framework-free contracts and logic for the JavaScript Intelligence &
Client-Side Attack-Surface Discovery capability: data models, a safe tokenizer,
versioned detection rules, the core analyzers (endpoints, routes, configuration,
storage, authentication, workers, WebAssembly, security APIs, dynamic imports,
third-party services, external domains), technology & dependency detection,
secret scanning with strict masking, scope enforcement, confidence scoring,
normalization, correlation, conflict handling, historical comparison and
collection strategy.

The package depends only on the shared primitives and the recon domain for the
execution mode — no I/O, no tool calls and no persistence here.
"""

from hunterx.domain.javascript.analyzers import (
    AnalyzeContext,
    AnalyzerSet,
    AuthenticationAnalyzer,
    ConfigurationAnalyzer,
    DomainAnalyzer,
    DynamicImportAnalyzer,
    EndpointAnalyzer,
    RouteAnalyzer,
    SecurityAnalyzer,
    ServiceAnalyzer,
    StorageAnalyzer,
    WasmAnalyzer,
    WorkerAnalyzer,
)
from hunterx.domain.javascript.confidence import JSConfidenceEngine, JSConfidencePolicy
from hunterx.domain.javascript.conflicts import ConflictResolution, JSConflictResolver
from hunterx.domain.javascript.correlator import JSCorrelationResult, JSCorrelator
from hunterx.domain.javascript.history import JSHistory, JSHistorySnapshot
from hunterx.domain.javascript.models import (
    FINDINGS_KEY,
    ApiType,
    AuthReferenceKind,
    ChangeType,
    ConfidenceTier,
    ConfigurationKind,
    DomainRelation,
    EndpointKind,
    JavaScriptBatch,
    JSAcquisition,
    JSAssetAnalysis,
    JSAssetKind,
    JSAuthenticationReference,
    JSChange,
    JSConfigurationIndicator,
    JSDependency,
    JSDynamicImport,
    JSEndpoint,
    JSEvidence,
    JSExecutionSummary,
    JSExternalDomain,
    JSMode,
    JSRoute,
    JSSecretIndicator,
    JSSecurityIndicator,
    JSSourceMap,
    JSStorageIndicator,
    JSTechnologyEvidence,
    JSThirdPartyService,
    JSWasmReference,
    JSWorker,
    ParseStatus,
    RouteFramework,
    SecretClassification,
    SecurityApiKind,
    StorageType,
    TechnologyEvidenceKind,
    ThirdPartyCategory,
    WasmReferenceKind,
    WorkerKind,
    findings_from_payload,
    make_mode,
    make_target,
)
from hunterx.domain.javascript.normalizer import JSNormalizer, NormalizedUrl
from hunterx.domain.javascript.rules import (
    DEFAULT_RULES,
    JSRule,
    JSRuleRegistry,
    RuleCategory,
    RuleMatch,
)
from hunterx.domain.javascript.scope import (
    JSScopeDecision,
    JSScopeEnforcer,
    JSScopePolicy,
    normalize_domain,
    normalize_url,
)
from hunterx.domain.javascript.secrets import JSSecretScanner
from hunterx.domain.javascript.strategy import JSStrategy, JSStrategyBuilder
from hunterx.domain.javascript.technology import (
    JSDependencyDetector,
    JSTechnologyDetector,
    TechnologyDetection,
)
from hunterx.domain.javascript.tokenizer import (
    JSToken,
    JSTokenizer,
    JSTokenType,
    mask_template,
)

__all__ = [
    "AnalyzeContext",
    "AnalyzerSet",
    "ApiType",
    "AuthReferenceKind",
    "AuthenticationAnalyzer",
    "ChangeType",
    "ConfigurationAnalyzer",
    "ConfigurationKind",
    "ConfidenceTier",
    "ConflictResolution",
    "DEFAULT_RULES",
    "DomainAnalyzer",
    "DomainRelation",
    "DynamicImportAnalyzer",
    "EndpointAnalyzer",
    "EndpointKind",
    "FINDINGS_KEY",
    "JSAssetAnalysis",
    "JSAssetKind",
    "JSAcquisition",
    "JSAuthenticationReference",
    "JSChange",
    "JSConfigurationIndicator",
    "JSConfidenceEngine",
    "JSConfidencePolicy",
    "JSConflictResolver",
    "JSCorrelationResult",
    "JSCorrelator",
    "JSDependency",
    "JSDependencyDetector",
    "JSDynamicImport",
    "JSEndpoint",
    "JSEvidence",
    "JSExecutionSummary",
    "JSExternalDomain",
    "JSHistory",
    "JSHistorySnapshot",
    "JSMode",
    "JSNormalizer",
    "JSRoute",
    "JSRule",
    "JSRuleRegistry",
    "JSScopeDecision",
    "JSScopeEnforcer",
    "JSScopePolicy",
    "JSSecretIndicator",
    "JSSecretScanner",
    "JSSecurityIndicator",
    "JSSourceMap",
    "JSStorageIndicator",
    "JSStrategy",
    "JSStrategyBuilder",
    "JSTechnologyDetector",
    "JSTechnologyEvidence",
    "JSThirdPartyService",
    "JSToken",
    "JSTokenType",
    "JSTokenizer",
    "JSWasmReference",
    "JSWorker",
    "JavaScriptBatch",
    "NormalizedUrl",
    "ParseStatus",
    "RouteAnalyzer",
    "RouteFramework",
    "RuleCategory",
    "RuleMatch",
    "SecretClassification",
    "SecurityAnalyzer",
    "SecurityApiKind",
    "ServiceAnalyzer",
    "StorageAnalyzer",
    "StorageType",
    "TechnologyDetection",
    "TechnologyEvidenceKind",
    "ThirdPartyCategory",
    "WasmAnalyzer",
    "WasmReferenceKind",
    "WorkerAnalyzer",
    "WorkerKind",
    "findings_from_payload",
    "make_mode",
    "make_target",
    "mask_template",
    "normalize_domain",
    "normalize_url",
]
